In [1]:
import pandas as pd

In [3]:
file1=pd.read_csv('BasicCompanyData-2022-01-01-part2_6.csv')
file2=pd.read_csv('BasicCompanyData-2022-01-01-part3_6.csv')
file3=pd.read_csv('BasicCompanyData-2022-01-01-part4_6.csv')
file4=pd.read_csv('BasicCompanyData-2022-01-01-part5_6.csv')
file5=pd.read_csv('BasicCompanyData-2022-01-01-part6_6.csv')

C:\Users\user\anaconda3\envs\codingNJ\lib\site-packages\IPython\core\interactiveshell.py:3457: DtypeWarning: Columns (43,44,45,46,47,48,49,50,51,52) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [4]:
# 제출 포맷 갖고오기 
신영국4 = pd.read_excel('신영국4.xlsx')
신영국5 = pd.read_excel('신영국5.xlsx')

In [5]:
신영국_file1 = pd.DataFrame(columns = 신영국4.columns)
신영국_file2 = pd.DataFrame(columns = 신영국4.columns)
신영국_file3 = pd.DataFrame(columns = 신영국4.columns)
신영국_file4 = pd.DataFrame(columns = 신영국4.columns)
신영국_file5 = pd.DataFrame(columns = 신영국4.columns)

In [6]:
신영국4.columns

Index(['키값', '헤브론스타국가코드', '현지언어국가명', '영문국가명', '국가언어코드값', '현지언어언어명', '영문언어명',
       '현지언어기업명', '영문기업명', '현지언어한줄소개내용', '현지언어기업소개내용', '영문한줄소개내용', '영문기업소개내용',
       '현지언어대표이사명', '영문대표이사명', '기업대표전화번호', '대표팩스번호', '대표이메일', '기업홈페이지URL',
       '페이스북URL', '인스타그램URL', '유튜브URL', '링크드인URL', '현지언어담당자명', '영문담당자명',
       '현지언어직위명', '영문직위명', '담당자부서명', '기업담당자전화번호', '담당자이메일', '담당자팩스번호',
       '기업담당자이동전화번호', '현지언어기업주소', '현지언어기업상세주소', '영문기업주소', '영문기업상세주소', '기업우편번호',
       '현지언어산업군명', '영문산업군명', '현지언어주요제품내용', '영문주요제품내용', '설립일자', '기업종업원값',
       '외감법인구분값', '매출년도값', '매출액값', '기본화폐키값', '화폐단위명', '주식시장코드', '현지언어주식시장명',
       '영문주식시장명', '상장코드', '상장일자', '기업추가정보값', '작업구분코드', '데이터생성일자', '연계처리상태코드',
       '연계처리일자'],
      dtype='object')

In [7]:
file1.columns

Index(['CompanyName', ' CompanyNumber', 'RegAddress.CareOf',
       'RegAddress.POBox', 'RegAddress.AddressLine1',
       ' RegAddress.AddressLine2', 'RegAddress.PostTown', 'RegAddress.County',
       'RegAddress.Country', 'RegAddress.PostCode', 'CompanyCategory',
       'CompanyStatus', 'CountryOfOrigin', 'DissolutionDate',
       'IncorporationDate', 'Accounts.AccountRefDay',
       'Accounts.AccountRefMonth', 'Accounts.NextDueDate',
       'Accounts.LastMadeUpDate', 'Accounts.AccountCategory',
       'Returns.NextDueDate', 'Returns.LastMadeUpDate',
       'Mortgages.NumMortCharges', 'Mortgages.NumMortOutstanding',
       'Mortgages.NumMortPartSatisfied', 'Mortgages.NumMortSatisfied',
       'SICCode.SicText_1', 'SICCode.SicText_2', 'SICCode.SicText_3',
       'SICCode.SicText_4', 'LimitedPartnerships.NumGenPartners',
       'LimitedPartnerships.NumLimPartners', 'URI', 'PreviousName_1.CONDATE',
       ' PreviousName_1.CompanyName', ' PreviousName_2.CONDATE',
       ' PreviousName_2.CompanyName', 'PreviousName_3.CONDATE',
       ' PreviousName_3.CompanyName', 'PreviousName_4.CONDATE',
       ' PreviousName_4.CompanyName', 'PreviousName_5.CONDATE',
       ' PreviousName_5.CompanyName', 'PreviousName_6.CONDATE',
       ' PreviousName_6.CompanyName', 'PreviousName_7.CONDATE',
       ' PreviousName_7.CompanyName', 'PreviousName_8.CONDATE',
       ' PreviousName_8.CompanyName', 'PreviousName_9.CONDATE',
       ' PreviousName_9.CompanyName', 'PreviousName_10.CONDATE',
       ' PreviousName_10.CompanyName', 'ConfStmtNextDueDate',
       ' ConfStmtLastMadeUpDate'],
      dtype='object')

In [8]:
file1.head()

,CompanyName,CompanyNumber,RegAddress.CareOf,RegAddress.POBox,RegAddress.AddressLine1,RegAddress.AddressLine2,RegAddress.PostTown,RegAddress.County,RegAddress.Country,RegAddress.PostCode,...,PreviousName_7.CONDATE,PreviousName_7.CompanyName,PreviousName_8.CONDATE,PreviousName_8.CompanyName,PreviousName_9.CONDATE,PreviousName_9.CompanyName,PreviousName_10.CONDATE,PreviousName_10.CompanyName,ConfStmtNextDueDate,ConfStmtLastMadeUpDate
0,CARRINGTON CROSS LIMITED,08122928,NaN,NaN,SWAN HOUSE,LOWER HIGH STREET,CRADLEY HEATH,NaN,ENGLAND,B64 5AJ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,04/10/2022,20/09/2021
1,CARRINGTON DAY NURSERY LIMITED,07631838,NaN,NaN,315-317 MANSFIELD ROAD,NaN,NOTTINGHAM,NaN,NaN,NG5 2DA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26/05/2022,12/05/2021
2,CARRINGTON DEAN GROUP LIMITED,SC225672,NaN,NaN,76 RENFIELD STREET,NaN,GLASGOW,NaN,SCOTLAND,G2 1NQ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23/11/2022,09/11/2021
3,CARRINGTON DEAN LIMITED,SC382881,NaN,NaN,76 RENFIELD STREET,NaN,GLASGOW,NaN,SCOTLAND,G2 1NQ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13/08/2022,30/07/2021
4,CARRINGTON DEAN NUMBER 2 LIMITED,SC475274,NaN,NaN,76 RENFIELD STREET,NaN,GLASGOW,NaN,SCOTLAND,G2 1NQ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/10/2022,17/09/2021

In [10]:
# 제출 포맷으로 맞추기 
#file1에 대해
신영국_file1['현지언어기업명'] = file1['CompanyName']
신영국_file1['영문기업명'] = file1['CompanyName']
신영국_file1['헤브론스타국가코드'] = 'GBR'
신영국_file1['현지언어국가명'] = 'Great Britain'
신영국_file1['영문국가명'] = 'Great Britain'
신영국_file1['현지언어기업주소'] = file1['RegAddress.PostTown']+","+file1['RegAddress.County']+","+file1['RegAddress.Country']
신영국_file1['현지언어기업상세주소'] = file1['RegAddress.AddressLine1']+", "+file1[' RegAddress.AddressLine2']
신영국_file1['기업홈페이지URL'] = file1['URI']
신영국_file1['영문기업주소'] = file1['RegAddress.PostTown']+","+file1['RegAddress.County']+","+file1['RegAddress.Country']
신영국_file1['영문기업상세주소'] = file1['RegAddress.AddressLine1']+", "+file1[' RegAddress.AddressLine2']
신영국_file1['기업우편번호'] = file1['RegAddress.PostCode']
신영국_file1['현지언어산업군명'] = file1['SICCode.SicText_1']
신영국_file1['영문산업군명'] = file1['SICCode.SicText_1']
신영국_file1['설립일자'] = file1['IncorporationDate']

#file2에 대해 
신영국_file2['현지언어기업명'] = file2['CompanyName']
신영국_file2['영문기업명'] = file2['CompanyName']
신영국_file2['헤브론스타국가코드'] = 'GBR'
신영국_file2['현지언어국가명'] = 'Great Britain'
신영국_file2['영문국가명'] = 'Great Britain'
신영국_file2['현지언어기업주소'] = file2['RegAddress.PostTown']+","+file2['RegAddress.County']+","+file2['RegAddress.Country']
신영국_file2['현지언어기업상세주소'] = file2['RegAddress.AddressLine1']+", "+file2[' RegAddress.AddressLine2']
신영국_file2['기업홈페이지URL'] = file2['URI']
신영국_file2['영문기업주소'] = file2['RegAddress.PostTown']+","+file2['RegAddress.County']+","+file2['RegAddress.Country']
신영국_file2['영문기업상세주소'] = file2['RegAddress.AddressLine1']+", "+file2[' RegAddress.AddressLine2']
신영국_file2['기업우편번호'] = file2['RegAddress.PostCode']
신영국_file2['현지언어산업군명'] = file2['SICCode.SicText_1']
신영국_file2['영문산업군명'] = file2['SICCode.SicText_1']
신영국_file2['설립일자'] = file2['IncorporationDate']
#file3에 대해
신영국_file3['현지언어기업명'] = file3['CompanyName']
신영국_file3['영문기업명'] = file3['CompanyName']
신영국_file3['헤브론스타국가코드'] = 'GBR'
신영국_file3['현지언어국가명'] = 'Great Britain'
신영국_file3['영문국가명'] = 'Great Britain'
신영국_file3['현지언어기업주소'] = file3['RegAddress.PostTown']+","+file3['RegAddress.County']+","+file3['RegAddress.Country']
신영국_file3['현지언어기업상세주소'] = file3['RegAddress.AddressLine1']+", "+file3[' RegAddress.AddressLine2']
신영국_file3['기업홈페이지URL'] = file3['URI']
신영국_file3['영문기업주소'] = file3['RegAddress.PostTown']+","+file3['RegAddress.County']+","+file3['RegAddress.Country']
신영국_file3['영문기업상세주소'] = file3['RegAddress.AddressLine1']+", "+file3[' RegAddress.AddressLine2']
신영국_file3['기업우편번호'] = file3['RegAddress.PostCode']
신영국_file3['현지언어산업군명'] = file3['SICCode.SicText_1']
신영국_file3['영문산업군명'] = file3['SICCode.SicText_1']
신영국_file3['설립일자'] = file3['IncorporationDate']
#file4에 대해
신영국_file4['현지언어기업명'] = file4['CompanyName']
신영국_file4['영문기업명'] = file4['CompanyName']
신영국_file4['헤브론스타국가코드'] = 'GBR'
신영국_file4['현지언어국가명'] = 'Great Britain'
신영국_file4['영문국가명'] = 'Great Britain'
신영국_file4['현지언어기업주소'] = file4['RegAddress.PostTown']+","+file4['RegAddress.County']+","+file4['RegAddress.Country']
신영국_file4['현지언어기업상세주소'] = file4['RegAddress.AddressLine1']+", "+file4[' RegAddress.AddressLine2']
신영국_file4['기업홈페이지URL'] = file4['URI']
신영국_file4['영문기업주소'] = file4['RegAddress.PostTown']+","+file4['RegAddress.County']+","+file4['RegAddress.Country']
신영국_file4['영문기업상세주소'] = file4['RegAddress.AddressLine1']+", "+file4[' RegAddress.AddressLine2']
신영국_file4['기업우편번호'] = file4['RegAddress.PostCode']
신영국_file4['현지언어산업군명'] = file4['SICCode.SicText_1']
신영국_file4['영문산업군명'] = file4['SICCode.SicText_1']
신영국_file4['설립일자'] = file4['IncorporationDate']
#file5에 대해
신영국_file5['현지언어기업명'] = file5['CompanyName']
신영국_file5['영문기업명'] = file5['CompanyName']
신영국_file5['헤브론스타국가코드'] = 'GBR'
신영국_file5['현지언어국가명'] = 'Great Britain'
신영국_file5['영문국가명'] = 'Great Britain'
신영국_file5['현지언어기업주소'] = file5['RegAddress.PostTown']+","+file5['RegAddress.County']+","+file5['RegAddress.Country']
신영국_file5['현지언어기업상세주소'] = file5['RegAddress.AddressLine1']+", "+file5[' RegAddress.AddressLine2']
신영국_file5['기업홈페이지URL'] = file5['URI']
신영국_file5['영문기업주소'] = file5['RegAddress.PostTown']+","+file5['RegAddress.County']+","+file5['RegAddress.Country']
신영국_file5['영문기업상세주소'] = file5['RegAddress.AddressLine1']+", "+file5[' RegAddress.AddressLine2']
신영국_file5['기업우편번호'] = file5['RegAddress.PostCode']
신영국_file5['현지언어산업군명'] = file5['SICCode.SicText_1']
신영국_file5['영문산업군명'] = file5['SICCode.SicText_1']
신영국_file5['설립일자'] = file5['IncorporationDate']

In [11]:
신영국6 = 신영국_file1.iloc[:200000,:]
신영국6['키값'] = 신영국4['키값']
신영국7 =신영국_file1.iloc[200001:400000,:]
신영국7['키값'] = 신영국4['키값']
신영국8 =신영국_file1.iloc[400001:600000,:]
신영국8['키값'] = 신영국4['키값']
신영국9 =신영국_file1.iloc[600001:800000,:]
신영국9['키값'] = 신영국4['키값']
신영국10 =신영국_file1.iloc[800001:8500000,:]
신영국10['키값'] = 신영국5['키값']

C:\Users\user\AppData\Local\Temp/ipykernel_15212/576805.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  신영국6['키값'] = 신영국4['키값']
C:\Users\user\AppData\Local\Temp/ipykernel_15212/576805.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  신영국7['키값'] = 신영국4['키값']
C:\Users\user\AppData\Local\Temp/ipykernel_15212/576805.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  신영국8['키값'] = 신영국4['키값']
C:\Users\user\AppData\Local\Temp/ipykernel_15212/576805.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  신영국9['키값'] = 신영국4['키값']
C:\Users\user\AppData\Local\Temp/ipykernel_15212/576805.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  신영국10['키값'] = 신영국5['키값']

In [12]:
신영국6.to_excel('신영국6.xlsx', index = False)
신영국7.to_excel('신영국7.xlsx', index = False) 
신영국8.to_excel('신영국8.xlsx', index = False)
신영국9.to_excel('신영국9.xlsx', index = False)
신영국10.to_excel('신영국10.xlsx', index = False)

In [13]:
신영국11 = 신영국_file2.iloc[:200000,:]
신영국11['키값'] = 신영국4['키값']
신영국12 =신영국_file2.iloc[200001:400000,:]
신영국12['키값'] = 신영국4['키값']
신영국13 =신영국_file2.iloc[400001:600000,:]
신영국13['키값'] = 신영국4['키값']
신영국14 =신영국_file2.iloc[600001:800000,:]
신영국14['키값'] = 신영국4['키값']
신영국15=신영국_file2.iloc[800001:8500000,:]
신영국15['키값'] = 신영국5['키값']

신영국11.to_excel('신영국11.xlsx', index = False)
신영국12.to_excel('신영국12.xlsx', index = False)
신영국13.to_excel('신영국13.xlsx', index = False)
신영국14.to_excel('신영국14.xlsx', index = False)
신영국15.to_excel('신영국15.xlsx', index = False)

C:\Users\user\AppData\Local\Temp/ipykernel_15212/1333439099.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  신영국11['키값'] = 신영국4['키값']
C:\Users\user\AppData\Local\Temp/ipykernel_15212/1333439099.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  신영국12['키값'] = 신영국4['키값']
C:\Users\user\AppData\Local\Temp/ipykernel_15212/1333439099.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  신영국13['키값'] = 신영국4['키값']
C:\Users\user\AppData\Local\Temp/ipykernel_15212/1333439099.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  신영국14['키값'] = 신영국4['키값']
C:\Users\user\AppData\Local\Temp/ipykernel_15212/1333439099.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  신영국15['키값'] = 신영국5['키값']

In [14]:
신영국16 = 신영국_file3.iloc[:200000,:]
신영국16['키값'] = 신영국4['키값']
신영국17 =신영국_file3.iloc[200001:400000,:]
신영국17['키값'] = 신영국4['키값']
신영국18 =신영국_file3.iloc[400001:600000,:]
신영국18['키값'] = 신영국4['키값']
신영국19 =신영국_file3.iloc[600001:800000,:]
신영국19['키값'] = 신영국4['키값']
신영국20=신영국_file3.iloc[800001:8500000,:]
신영국20['키값'] = 신영국5['키값']

신영국16.to_excel('신영국16.xlsx', index = False)  
신영국17.to_excel('신영국17.xlsx', index = False)
신영국18.to_excel('신영국18.xlsx', index = False)
신영국19.to_excel('신영국19.xlsx', index = False)
신영국20.to_excel('신영국20.xlsx', index = False)

C:\Users\user\AppData\Local\Temp/ipykernel_15212/3007235176.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  신영국16['키값'] = 신영국4['키값']
C:\Users\user\AppData\Local\Temp/ipykernel_15212/3007235176.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  신영국17['키값'] = 신영국4['키값']
C:\Users\user\AppData\Local\Temp/ipykernel_15212/3007235176.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  신영국18['키값'] = 신영국4['키값']
C:\Users\user\AppData\Local\Temp/ipykernel_15212/3007235176.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  신영국19['키값'] = 신영국4['키값']
C:\Users\user\AppData\Local\Temp/ipykernel_15212/3007235176.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  신영국20['키값'] = 신영국5['키값']

In [15]:
신영국21 = 신영국_file4.iloc[:200000,:]
신영국21['키값'] = 신영국4['키값']
신영국22 =신영국_file4.iloc[200001:400000,:]
신영국22['키값'] = 신영국4['키값']
신영국23 =신영국_file4.iloc[400001:600000,:]
신영국23['키값'] = 신영국4['키값']
신영국24 =신영국_file4.iloc[600001:800000,:]
신영국24['키값'] = 신영국4['키값']
신영국25=신영국_file4.iloc[800001:8500000,:]
신영국25['키값'] = 신영국5['키값']

신영국21.to_excel('신영국21.xlsx', index = False)
신영국22.to_excel('신영국22.xlsx', index = False)
신영국23.to_excel('신영국23.xlsx', index = False)
신영국24.to_excel('신영국24.xlsx', index = False)

신영국25.to_excel('신영국25.xlsx', index = False)

C:\Users\user\AppData\Local\Temp/ipykernel_15212/656994278.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  신영국21['키값'] = 신영국4['키값']
C:\Users\user\AppData\Local\Temp/ipykernel_15212/656994278.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  신영국22['키값'] = 신영국4['키값']
C:\Users\user\AppData\Local\Temp/ipykernel_15212/656994278.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  신영국23['키값'] = 신영국4['키값']
C:\Users\user\AppData\Local\Temp/ipykernel_15212/656994278.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  신영국24['키값'] = 신영국4['키값']
C:\Users\user\AppData\Local\Temp/ipykernel_15212/656994278.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  신영국25['키값'] = 신영국5['키값']

In [16]:
신영국26 = 신영국_file5.iloc[:200000,:]
신영국26['키값'] = 신영국4['키값']
신영국27 =신영국_file5.iloc[200001:400000,:]
신영국27['키값'] = 신영국4['키값']
신영국28 =신영국_file5.iloc[400001:600000,:]
신영국28['키값'] = 신영국4['키값']
신영국29 =신영국_file5.iloc[600001:800000,:]
신영국29['키값'] = 신영국4['키값']
신영국30=신영국_file5.iloc[800001:8500000,:]
신영국30['키값'] = 신영국5['키값']

신영국26.to_excel('신영국26.xlsx', index = False)
신영국27.to_excel('신영국27.xlsx', index = False)
신영국28.to_excel('신영국28.xlsx', index = False)
신영국29.to_excel('신영국29.xlsx', index = False)
신영국30.to_excel('신영국30.xlsx', index = False)

C:\Users\user\AppData\Local\Temp/ipykernel_15212/300197528.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  신영국26['키값'] = 신영국4['키값']
C:\Users\user\AppData\Local\Temp/ipykernel_15212/300197528.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  신영국27['키값'] = 신영국4['키값']
C:\Users\user\AppData\Local\Temp/ipykernel_15212/300197528.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  신영국28['키값'] = 신영국4['키값']
C:\Users\user\AppData\Local\Temp/ipykernel_15212/300197528.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  신영국29['키값'] = 신영국4['키값']
C:\Users\user\AppData\Local\Temp/ipykernel_15212/300197528.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  신영국30['키값'] = 신영국5['키값']

In [ ]:
len(신영국29)