## 1. 국가별로 재무제표가 있는 상장사 Symbol 갖고오기  

OVERVIEW  
This endpoint allows you to get a list of all companies for which the API has financial statements. We cover the New York Stock Exchange (NYSE), the New York Stock Exchange (NASDAQ), international exchanges, and more. Because we're growing all the time, this list will be updated on a regular basis.  

If you are looking for endpoint that will allow you to retrieve statements for those companies you can check out this endpoint.

아래 코드는 공식 가이드에 첨부된 코드들이다.

먼저, FMP가 제공하는 모든 심볼들을 갖고 오고, 그 심볼들을 국가마다 구분해야 한다.

### 1-1. 모든 Symbol Listup 

FMP에서는 Fianancial Statements를 갖고 있는 Symbol을 추출하는 API를 제공한다.     
  
ex) https://financialmodelingprep.com/api/v3/financial-statement-symbol-lists?apikey=YOUR_API_KEY

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import json
# Financial Statments가 있는 기업들의 Symbol을 가져오기 위한 모듈 설치 
try:
    # For Python 3.0 and later
    from urllib.request import urlopen
except ImportError:
    # Fall back to Python 2's urllib2
    from urllib2 import urlopen

import certifi

아래 get_jsonparsed_data는 는 FMP document에서 갖고 온 코드로서, 재무제표가 있는 Symbol을 추출할 때 필요한 함수이다.

In [42]:
def get_jsonparsed_data(url):
    """
    Receive the content of ``url``, parse it as JSON and return the object.

    Parameters
    ----------
    url : str

    Returns
    -------
    dict
    """
    response = urlopen(url, cafile=certifi.where())
    data = response.read().decode("utf-8")
    return json.loads(data)

Financial Statments가 있는 기업들의 Symbol을 가져오기 위한 QueryString.

In [45]:
# Financial Statments가 있는 기업들의 Symbol을 가져오기 위한 QueryString. API Key = 33d67d9c5e5ed94ff134e9bf93f9d818
url = ("https://financialmodelingprep.com/api/v3/financial-statement-symbol-lists?apikey=33d67d9c5e5ed94ff134e9bf93f9d818")

In [46]:
Symbols = get_jsonparsed_data(url)

C:\Users\user\AppData\Local\Temp/ipykernel_14308/3606349989.py:13: DeprecationWarning: cafile, capath and cadefault are deprecated, use a custom context instead.
  response = urlopen(url, cafile=certifi.where())

### 1-2. Symbol들을 국가별로 분류한다.

In [47]:
US_symbols = []          # 
Canada_symbols = []      #TO
France_symbols = []      #PA ? 
Germany_symbols = []     #DE
India_symbols = []       #NS
London_symbols = []      #L
Hongkong_symbols = []    #HK
Austrailia_symbols = []  #AX
Swiss_symbols = []       #SW
Korea_symbols = []       #KR

for Symbol in Symbols : 
    if ".TO" in Symbol : 
        Canada_symbols.append(Symbol) 
    elif ".PA" in Symbol : 
        France_symbols.append(Symbol) 
    elif ".DE" in Symbol : 
        Germany_symbols.append(Symbol) 
    elif ".NS" in Symbol : 
        India_symbols.append(Symbol) 
    elif ".L" in Symbol : 
        London_symbols.append(Symbol) 
    elif ".HK" in Symbol : 
        Hongkong_symbols.append(Symbol) 
    elif ".AX" in Symbol : 
        Austrailia_symbols.append(Symbol) 
    elif ".SW" in Symbol : 
        Swiss_symbols.append(Symbol) 
    elif ".KS" in Symbol :
        Korea_symbols.append(Symbol)
    elif "." not in Symbol :
        US_symbols.append(Symbol)

In [48]:
# 국가별 재무정보 추출 기업 수 
print(f"US에서 뽑아낼 수 있는 상장기업 수 : {len(US_symbols)}")
print(f"Canada에서 뽑아낼 수 있는 상장기업 수 : {len(Canada_symbols)}")
print(f"France에서 뽑아낼 수 있는 상장기업 수 : {len(France_symbols)}")
print(f"Germany에서 뽑아낼 수 있는 상장기업 수 : {len(Germany_symbols)}")
print(f"India에서 뽑아낼 수 있는 상장기업 수 : {len(India_symbols)}")
print(f"London에서 뽑아낼 수 있는 상장기업 수 : {len(London_symbols)}")
print(f"Hongkong에서 뽑아낼 수 있는 상장기업 수 : {len(Hongkong_symbols)}")
print(f"Australia에서 뽑아낼 수 있는 상장기업 수 : {len(Austrailia_symbols)}")
print(f"Swiss에서 뽑아낼 수 있는 상장기업 수 : {len(Swiss_symbols)}")
print(f"Korea에서 뽑아낼 수 있는 상장기업 수 : {len(Korea_symbols)}")

US에서 뽑아낼 수 있는 상장기업 수 : 14604
Canada에서 뽑아낼 수 있는 상장기업 수 : 842
France에서 뽑아낼 수 있는 상장기업 수 : 711
Germany에서 뽑아낼 수 있는 상장기업 수 : 957
India에서 뽑아낼 수 있는 상장기업 수 : 1834
London에서 뽑아낼 수 있는 상장기업 수 : 2067
Hongkong에서 뽑아낼 수 있는 상장기업 수 : 2575
Australia에서 뽑아낼 수 있는 상장기업 수 : 1899
Swiss에서 뽑아낼 수 있는 상장기업 수 : 407
Korea에서 뽑아낼 수 있는 상장기업 수 : 990

# 2. 나라마다 재무제표 추출

API를 통해 원하는 재무정보를 갖고 오기 위해는 FMP의 international Filings(해외기업 재무제표) API의 구조를 알아야 한다.  
FMP API는 아래의 Query String에 APIKey를 기입하여 requests.get()으로 손쉽게 데이터를 가져올 수 있는 구조이다.  
API는 json 형태로 데이터를 반환한다. 

ex) https://financialmodelingprep.com/api/v3/income-statement/RY.TO?limit=10&apikey=YOUR_API_KEY 

API Query String 분석 : 
* RY.TO : 요청하고자 하는 상장사 Symbol. 예시로 든 RY.TO는 Toronto(캐나다)에 상장된, Symbol이 RY인 회사이다. 
* limit=   : limit 뒤에 있는 숫자로 현재로부터 과거 몇년간의 데이터를 가져올지를 결정한다. limit=3은 과거 3년간의 데이터 를 갖고오게 됌. 
* apikey=  : 구입한 API key를 기입한다.

한 나라에 대해 재무제표를 추출하고 전처리 하는 과정을 정해두면, 다른 나라에 대해서도 코드를 재활용할 수 있다.  
프랑스를 기준으로 데이터 수집 및 전처리 코드를 먼저 작성한 후 이를 전체 국가로 확장해본다.

### 2-1. 프랑스 상장사들의 재무제표 갖고오기

API는 json 형태로 데이터를 반환한다. 아래 extractor 함수는 URL을 입력하면 API를 통해 반환받은 json을 pandas dataframe으로 반환하는 함수이다.

In [58]:
def extractor(url) : 
    try:
        from pandas import json_normalize
    except ImportError:
        from pandas.io.json import json_normalize
    # 데이터 갖고오기
    req=requests.get(url)
    # json load
    data = json.loads(req.text)
    # json to pandas
    preprocessed = json_normalize(data)
    return preprocessed

아래 url_generator 함수는 세가지 인풋을 입력받는다. 
* 재무제표를 수집하려는 기업의 Symbol
* 재무제표 타입(filing_type) : is(income-statement), bs(balance-sheet), cf(cash-flow) 
* 현재부터 과거 몇년치까지 수집할 것인지 제한 : limit  
인풋 변수를 입력하면 각각에 맞는 url을 반환하는 함수이다.

In [63]:
def url_generator(target_Symbol, filing_type, limit) : 
    base_url = 'https://financialmodelingprep.com/api/v3/income-statement/RY.TO?limit=5&apikey=89d4891348727c3950b79b9067127c3f'
    is_url = base_url.replace('RY.TO', target_Symbol)
    is_url = is_url.replace('=5', '='+str(limit))
    bs_url = is_url.replace('income-statement','balance-sheet-statement')
    cf_url = is_url.replace('income-statement','cash-flow-statement')
    
    if filing_type == 'is' : 
        return is_url
    elif filing_type == 'bs' : 
        return bs_url
    elif filing_type == 'cf' : 
        return cf_url 
    else :
        return "Please input proper filing_type"

In [89]:
extractor('https://financialmodelingprep.com/api/v3/cash-flow-statement/RY.TO?limit=5&apikey=89d4891348727c3950b79b9067127c3f')

,date,symbol,reportedCurrency,cik,fillingDate,acceptedDate,calendarYear,period,netIncome,depreciationAndAmortization,...,netCashUsedProvidedByFinancingActivities,effectOfForexChangesOnCash,netChangeInCash,cashAtEndOfPeriod,cashAtBeginningOfPeriod,operatingCashFlow,capitalExpenditure,freeCashFlow,link,finalLink
0,2021-10-31,RY.TO,CAD,None,2021-10-31,2021-10-31,2021,FY,16038000000,2592000000,...,-5928000000,-2810000000,-5042000000,113846000000,118888000000,61044000000,-2186000000,58858000000,https://www.sedar.com/ModifyCompanyDocumentSea...,https://www.sedar.com/ModifyCompanyDocumentSea...
1,2020-10-31,RY.TO,CAD,None,2020-10-31,2020-10-31,2020,FY,11432000000,2648000000,...,-7746000000,1062000000,92578000000,118888000000,26310000000,138819000000,-2629000000,136190000000,https://www.sedar.com/ModifyCompanyDocumentSea...,https://www.sedar.com/ModifyCompanyDocumentSea...
2,2019-10-31,RY.TO,CAD,None,2019-10-31,2019-10-31,2019,FY,12860000000,1934000000,...,-7457000000,419000000,-3899000000,26310000000,30209000000,14265000000,-2261000000,12004000000,https://www.sedar.com/ModifyCompanyDocumentSea...,https://www.sedar.com/ModifyCompanyDocumentSea...
3,2018-10-31,RY.TO,CAD,None,2018-10-31,2018-10-31,2018,FY,12400000000,1652000000,...,-7720000000,66000000,1802000000,30209000000,28407000000,17474000000,-1980000000,15494000000,https://www.sedar.com/ModifyCompanyDocumentSea...,https://www.sedar.com/ModifyCompanyDocumentSea...
4,2017-10-31,RY.TO,CAD,None,2017-10-31,2017-10-31,2017,FY,11428000000,1617000000,...,-8651000000,-138000000,13478000000,28407000000,14929000000,37725000000,-1364000000,36361000000,https://www.sedar.com/ModifyCompanyDocumentSea...,https://www.sedar.com/ModifyCompanyDocumentSea...

FMP API에서 갖고 올 수 있는 계정과목들은 많다. 그러나 2022년 BDC과제에서 작성한 테이블 명세서에 근거하여 추출하고자 하는 계정과목이름만 리스트에 저장한다. 이렇게 만들어진 리스트들로 필요한 열들만 추출한다.

In [79]:
bs_cols = ['fillingDate','totalCurrentAssets','totalNonCurrentAssets','totalAssets', 'totalCurrentLiabilities','totalNonCurrentLiabilities',
           'totalLiabilities','totalEquity','totalLiabilitiesAndTotalEquity']
is_cols = ['revenue','costOfRevenue','sellingGeneralAndAdministrativeExpenses','operatingIncome','interestIncome','interestExpense',
          'incomeBeforeTax','netIncome','operatingIncomeRatio'] 
cf_cols = ['netCashProvidedByOperatingActivities','netCashUsedForInvestingActivites','netCashUsedProvidedByFinancingActivities',
          'cashAtBeginningOfPeriod','cashAtEndOfPeriod']

In [100]:
result_df = pd.DataFrame() 



for target_Symbol in France_symbols[2:3] :  
    
    # 기업별 URL 생성 
    is_url = url_generator(target_Symbol, 'is', 3)
    bs_url = url_generator(target_Symbol, 'bs', 3)
    cf_url = url_generator(target_Symbol, 'cf', 3)
    
    # extractor 함수를 이용하여 API를 통한 데이터를 판다스 데이터프레임으로 갖고옴. 
    df_is = extractor(is_url)
    df_bs = extractor(bs_url)
    df_cf = extractor(cf_url)
    
    # merge above three dataframes 
    company_df = pd.merge(df_is, df_bs)
    company_df = pd.merge(company_df, df_cf)
    
    # 필요한 열들만 
    company_df = company_df[bs_cols+is_cols+cf_cols]

In [101]:
company_df

,fillingDate,totalCurrentAssets,totalNonCurrentAssets,totalAssets,totalCurrentLiabilities,totalNonCurrentLiabilities,totalLiabilities,totalEquity,totalLiabilitiesAndTotalEquity,revenue,...,interestIncome,interestExpense,incomeBeforeTax,netIncome,operatingIncomeRatio,netCashProvidedByOperatingActivities,netCashUsedForInvestingActivites,netCashUsedProvidedByFinancingActivities,cashAtBeginningOfPeriod,cashAtEndOfPeriod
0,2020-12-31,7839000000,14115000000,21954000000,5975000000,9864000000,15839000000,6115000000,21954000000,15848000000,...,48000000,178000000,1355000000,957000000,0.110929,1661000000,-1714000000,562000000,2450000000,2828000000
1,2019-12-31,6563000000,11572000000,18135000000,5120000000,4596000000,9716000000,8419000000,18135000000,14125000000,...,62000000,114000000,1354000000,856000000,0.110796,1794000000,-868000000,-468000000,2004000000,2450000000
2,2018-12-31,6154000000,10344000000,16498000000,4230000000,4789000000,9019000000,7479000000,16498000000,13197000000,...,49000000,88000000,1171000000,730000000,0.106918,1396000000,-728000000,-611000000,1988000000,2004000000

In [97]:
company_df

,fillingDate,totalCurrentAssets,totalNonCurrentAssets,totalAssets,totalCurrentLiabilities,totalNonCurrentLiabilities,totalLiabilities,totalEquity,totalLiabilitiesAndTotalEquity,revenue,costOfRevenue,sellingGeneralAndAdministrativeExpenses,operatingIncome,interestIncome,interestExpense,incomeBeforeTax,netIncome,operatingIncomeRatio
0,2020-12-31,1153821000,2668528000,3822349000,368599000,1674159000,2042758000,1779591000,3822349000,434933000,496786000,0.0,-233463000,0.0,33217000.0,-272425000,-87465000,-0.536779
1,2019-12-31,1066340000,3303589000,4369929000,269970000,1987451000,2257421000,2112508000,4369929000,807793000,208780000,0.0,117766000,988000.0,0.0,120740000,50378000,0.145787
2,2018-12-31,887252000,3360171000,4247423000,214177000,1923297000,2137474000,2109949000,4247423000,904874000,148508000,0.0,214707000,0.0,2438000.0,291809000,258766000,0.237278

In [78]:
merge_right = pd.merge(df_is, df_bs)
merge_right.to_excel('./trial.xlsx')

In [74]:
df_bs

,date,symbol,reportedCurrency,cik,fillingDate,acceptedDate,calendarYear,period,cashAndCashEquivalents,shortTermInvestments,...,totalStockholdersEquity,totalLiabilitiesAndStockholdersEquity,minorityInterest,totalEquity,totalLiabilitiesAndTotalEquity,totalInvestments,totalDebt,netDebt,link,finalLink
0,2020-12-31,EC.PA,USD,None,2020-12-31,2020-12-31,2020,FY,450052000,0.0,...,1778649000,3821407000,942000,1779591000,3822349000,0.0,23046000,-427006000,https://www.infogreffe.com/recherche-entrepris...,https://www.infogreffe.com/recherche-entrepris...
1,2019-12-31,EC.PA,USD,None,2019-12-31,2019-12-31,2019,FY,699650000,0.0,...,2113310000,4370731000,-802000,2112508000,4369929000,0.0,67188000,-632462000,https://www.infogreffe.com/recherche-entrepris...,https://www.infogreffe.com/recherche-entrepris...
2,2018-12-31,EC.PA,USD,None,2018-12-31,2018-12-31,2018,FY,408114000,0.0,...,2109989000,4247463000,-40000,2109949000,4247423000,0.0,14419000,-393695000,https://www.infogreffe.com/recherche-entrepris...,https://www.infogreffe.com/recherche-entrepris...

In [75]:
df_cf

,date,symbol,reportedCurrency,cik,fillingDate,acceptedDate,calendarYear,period,netIncome,depreciationAndAmortization,...,netCashUsedProvidedByFinancingActivities,effectOfForexChangesOnCash,netChangeInCash,cashAtEndOfPeriod,cashAtBeginningOfPeriod,operatingCashFlow,capitalExpenditure,freeCashFlow,link,finalLink
0,2020-12-31,EC.PA,USD,None,2020-12-31,2020-12-31,2020,FY,-87465000,377377000,...,-301614000,0.0,-249599000,450052000,699651000,112152000,-60272000,51880000,https://www.infogreffe.com/recherche-entrepris...,https://www.infogreffe.com/recherche-entrepris...
1,2019-12-31,EC.PA,USD,None,2019-12-31,2019-12-31,2019,FY,50378000,263065000,...,-53781000,0.0,291536000,699651000,408115000,480164000,-127640000,352524000,https://www.infogreffe.com/recherche-entrepris...,https://www.infogreffe.com/recherche-entrepris...
2,2018-12-31,EC.PA,USD,None,2018-12-31,2018-12-31,2018,FY,258766000,275560000,...,-19658000,0.0,270964000,408114000,137150000,398398000,-158536000,239862000,https://www.infogreffe.com/recherche-entrepris...,https://www.infogreffe.com/recherche-entrepris...

In [15]:
# financialmodelprep.com API의 query string 
# cashflow
canada_cf = canada_income.replace('income-statement','cash-flow-statement')
euronext_cf = euronext_income.replace('income-statement','cash-flow-statement')
germany_cf = germany_income.replace('income-statement','cash-flow-statement')
india_cf = india_income.replace('income-statement','cash-flow-statement')
london_cf = london_income.replace('income-statement','cash-flow-statement')
hongkong_cf = hongkong_income.replace('income-statement','cash-flow-statement')
austrailia_cf = austrailia_income.replace('income-statement','cash-flow-statement')
swiss_cf = swiss_income.replace('income-statement','cash-flow-statement')

In [29]:
canada_income

'https://financialmodelingprep.com/api/v3/income-statement/RY.TO?limit=100&apikey=89d4891348727c3950b79b9067127c3f'

In [16]:
url_income_list = [canada_income, euronext_income, germany_income,india_income, london_income, hongkong_income, austrailia_income, swiss_income]
url_bs_list = [canada_bs, euronext_bs, germany_bs, india_bs, london_bs, hongkong_bs, austrailia_bs, swiss_bs]
url_cf_list = [canada_cf,euronext_cf,germany_cf,india_cf,london_cf,hongkong_cf,austrailia_cf,swiss_cf]

In [30]:
nation_example = extractor('https://financialmodelingprep.com/api/v3/income-statement/RY.TO?limit=400&apikey=89d4891348727c3950b79b9067127c3f')

In [31]:
nation_example

,date,symbol,reportedCurrency,cik,fillingDate,acceptedDate,calendarYear,period,revenue,costOfRevenue,...,incomeBeforeTaxRatio,incomeTaxExpense,netIncome,netIncomeRatio,eps,epsdiluted,weightedAverageShsOut,weightedAverageShsOutDil,link,finalLink
0,2021-10-31,RY.TO,CAD,None,2021-10-31,2021-10-31,2021,FY,45646000000,0.0,...,0.451978,4.581000e+09,16038000000,0.351356,11.263313,11.263313,1423915000,1423915000,https://www.sedar.com/ModifyCompanyDocumentSea...,https://www.sedar.com/ModifyCompanyDocumentSea...
1,2020-10-31,RY.TO,CAD,None,2020-10-31,2020-10-31,2020,FY,43421000000,0.0,...,0.331383,2.952000e+09,11432000000,0.263283,7.840000,7.820000,1423915000,1428770000,https://www.sedar.com/ModifyCompanyDocumentSea...,https://www.sedar.com/ModifyCompanyDocumentSea...
2,2019-10-31,RY.TO,CAD,None,2019-10-31,2019-10-31,2019,FY,41683000000,0.0,...,0.381786,3.043000e+09,12860000000,0.308519,8.780000,8.750000,1434779000,1440682000,https://www.sedar.com/ModifyCompanyDocumentSea...,https://www.sedar.com/ModifyCompanyDocumentSea...
3,2018-10-31,RY.TO,CAD,None,2018-10-31,2018-10-31,2018,FY,39839000000,0.0,...,0.395592,3.329000e+09,12400000000,0.311253,8.390000,8.360000,1443894000,1450485000,https://www.sedar.com/ModifyCompanyDocumentSea...,https://www.sedar.com/ModifyCompanyDocumentSea...
4,2017-10-31,RY.TO,CAD,None,2017-10-31,2017-10-31,2017,FY,37069000000,0.0,...,0.395802,3.203000e+09,11428000000,0.308290,7.590000,7.560000,1466988000,1474421000,https://www.sedar.com/ModifyCompanyDocumentSea...,https://www.sedar.com/ModifyCompanyDocumentSea...
5,2016-10-31,RY.TO,CAD,None,2016-10-31,2016-10-31,2016,FY,34250000000,0.0,...,0.388292,2.841000e+09,10405000000,0.303796,6.800000,6.780000,1485876000,1494137000,https://www.sedar.com/ModifyCompanyDocumentSea...,https://www.sedar.com/ModifyCompanyDocumentSea...
6,2015-10-31,RY.TO,CAD,None,2015-10-31,2015-10-31,2015,FY,32132000000,0.0,...,0.392848,2.597000e+09,9925000000,0.308882,6.750000,6.730000,1442935000,1449509000,https://www.sedar.com/ModifyCompanyDocumentSea...,https://www.sedar.com/ModifyCompanyDocumentSea...
7,2014-10-31,RY.TO,CAD,None,2014-10-31,2014-10-31,2014,FY,30373000000,0.0,...,0.385540,2.706000e+09,8910000000,0.293353,6.030000,6.000000,1442553000,1452003000,https://www.sedar.com/ModifyCompanyDocumentSea...,https://www.sedar.com/ModifyCompanyDocumentSea...
8,2013-10-31,RY.TO,CAD,None,2013-10-31,2013-10-31,2013,FY,28077000000,0.0,...,0.378139,2.188000e+09,8331000000,0.296720,5.600000,5.540000,1443735000,1466529000,https://www.sedar.com/ModifyCompanyDocumentSea...,https://www.sedar.com/ModifyCompanyDocumentSea...
9,2012-10-31,RY.TO,CAD,None,2012-10-31,2012-10-31,2012,FY,26128000000,0.0,...,0.370867,2.100000e+09,7442000000,0.284829,4.980000,4.930000,1442167000,1468287000,https://www.sedar.com/ModifyCompanyDocumentSea...,https://www.sedar.com/ModifyCompanyDocumentSea...
10,2011-10-31,RY.TO,CAD,None,2011-10-31,2011-10-31,2011,FY,24070000000,0.0,...,0.359036,1.888000e+09,4852000000,0.201579,3.210000,3.190000,1430722000,1437904000,https://www.sedar.com/ModifyCompanyDocumentSea...,https://www.sedar.com/ModifyCompanyDocumentSea...
11,2010-10-31,RY.TO,CAD,None,2010-10-31,2010-10-31,2010,FY,23222000000,0.0,...,0.300060,1.646000e+09,5223000000,0.224916,3.490000,3.460000,1420719000,1433754000,https://www.sedar.com/ModifyCompanyDocumentSea...,https://www.sedar.com/ModifyCompanyDocumentSea...
12,2009-10-31,RY.TO,CAD,None,2009-10-31,2009-10-31,2009,FY,24497000000,0.0,...,0.225579,1.568000e+09,3858000000,0.157489,2.590000,2.570000,1398675000,1412126000,https://www.sedar.com/ModifyCompanyDocumentSea...,https://www.sedar.com/ModifyCompanyDocumentSea...
13,2008-10-31,RY.TO,CAD,None,2008-10-31,2008-10-31,2008,FY,19951000000,0.0,...,0.300987,1.369000e+09,4555000000,0.228309,3.410000,3.380000,1305706000,1319744000,https://www.sedar.com/ModifyCompanyDocumentSea...,https://www.sedar.com/ModifyCompanyDocumentSea...
14,2007-10-31,RY.TO,CAD,None,2007-10-31,2007-10-31,2007,FY,19963000000,0.0,...,0.351901,1.392000e+09,5492000000,0.275109,4.240000,4.190000,1273185000,1289314000,https://www.sedar.com/ModifyCompanyDocumentSea...,https://www.sedar.com/ModifyCompanyDocumentSea...
15,2006-10-31,RY.TO,CAD,None,2006-10-31,2006-10-31,2006,FY,18128000000,0.0,...,0.342233,1.403000e+09,4728000000,0.260812,3.650000,3.590000,1279956000,1299785000,https://www.sedar.com/ModifyCompanyDocumentSea...,https://www.sedar.com/ModifyCompanyDocumentSea...
16,2005-10-31,RY.TO,CAD,None,2005-10-31,2005-10-31,2005,FY,19215964104,0.0,...,0.245361,1.277601e+09,3387649073,0.176293,2.610000,2.565000,1283434000,1304680000,https://www.sedar.com/ModifyCompanyDocumentSea...,https://www.sedar.com/ModifyCompanyDocumentSea...
17,2004-10-31,RY.TO,CAD,None,2004-10-31,2004-10-31,2004,FY,18121189953,0.0,...,0.223441,1.231407e+09,2817605462,0.155487,2.155000,2.125000,1292046000,1312094000,https://www.sedar.com/ModifyCompanyDocumentSea...,https://www.sedar.com/ModifyCompanyDocumentSea...
18,2003-10-31,RY.TO,CAD,None,2003-10-31,2003-10-31,2003,FY,17417908480,0.0,...,0.256360,1.459844e+09,3005406831,0.172547,2.240000,2.215000,1324160000,1339250000,https://www.sedar.com/ModifyCompanyDocumentSea...,https://www.sedar.com/ModifyCompanyDocumentSea...
19,2002-10-31,RY.TO,CAD,None,2002-10-31,2002-10-31,2002,FY,15719626169,0.0,...,0.262485,1.364486e+09,2761682243,0.175684,2.080000,2.060000,1345142000,1358306000,https://www.sedar.com/ModifyCompanyDocumentSea...,https://www.sedar.com/ModifyCompanyDocumentSea...
20,2001-10-31,RY.TO,CAD,None,2001-10-31,2001-10-31,2001,FY,14730995081,0.0,...,0.254579,1.339470e+09,2410728456,0.163650,1.790000,1.775000,1283032000,1294432000,https://www.sedar.com/ModifyCompanyDocumentSea...,https://www.sedar.com/ModifyCompanyDocumentSea...
21,2000-10-31,RY.TO,CAD,None,2000-10-31,2000-10-31,2000,FY,11958574474,0.0,...,0.302725,1.411818e+09,2208346025,0.184666,1.710000,1.700000,1212778000,1220189568,https://www.sedar.com/ModifyCompanyDocumentSea...,https://www.sedar.com/ModifyCompanyDocumentSea...
22,1999-10-31,RY.TO,CAD,None,1999-10-31,1999-10-31,1999,FY,10607915258,0.0,...,0.254431,9.739591e+08,1725025747,0.162617,1.257620,1.242910,1246835074,1261591528,https://www.sedar.com/ModifyCompanyDocumentSea...,https://www.sedar.com/ModifyCompanyDocumentSea...
23,1998-10-31,RY.TO,CAD,None,1998-10-31,1998-10-31,1998,FY,10049081648,0.0,...,0.298443,1.175027e+09,1824046921,0.181514,1.361320,1.330390,1233447792,1262124000,https://www.sedar.com/ModifyCompanyDocumentSea...,https://www.sedar.com/ModifyCompanyDocumentSea...
24,1997-10-31,RY.TO,CAD,None,1997-10-31,1997-10-31,1997,FY,9278974792,0.0,...,0.298422,1.089987e+09,1679059287,0.180953,1.253980,1.232850,1234542671,1255701681,https://www.sedar.com/ModifyCompanyDocumentSea...,https://www.sedar.com/ModifyCompanyDocumentSea...
25,1996-10-31,RY.TO,CAD,None,1996-10-31,1996-10-31,1996,FY,7911036789,0.0,...,0.291993,8.800000e+08,1429966555,0.180756,1.025920,1.025920,1253528606,1253528606,https://www.sedar.com/ModifyCompanyDocumentSea...,https://www.sedar.com/ModifyCompanyDocumentSea...
26,1995-10-31,RY.TO,CAD,None,1995-10-31,1995-10-31,1995,FY,7257127561,0.0,...,0.277952,7.550529e+08,1262080043,0.173909,0.880980,0.880980,1241757276,1241757276,https://www.sedar.com/ModifyCompanyDocumentSea...,https://www.sedar.com/ModifyCompanyDocumentSea...
27,1994-10-31,RY.TO,CAD,None,1994-10-31,1994-10-31,1994,FY,7365075072,0.0,...,0.247603,6.550791e+08,1168537806,0.158659,0.798030,0.798030,1253763708,1253763708,https://www.sedar.com/ModifyCompanyDocumentSea...,https://www.sedar.com/ModifyCompanyDocumentSea...
28,1993-10-31,RY.TO,CAD,None,1993-10-31,1993-10-31,1993,FY,6490000000,0.0,...,0.045455,-5.000000e+06,300000000,0.046225,0.115000,0.115000,1269565217,1269565217,https://www.sedar.com/ModifyCompanyDocumentSea...,https://www.sedar.com/ModifyCompanyDocumentSea...

In [33]:
extractor('https://financialmodelingprep.com/api/v3/income-statement/RY.TO?limit=3&apikey=89d4891348727c3950b79b9067127c3f')

,date,symbol,reportedCurrency,cik,fillingDate,acceptedDate,calendarYear,period,revenue,costOfRevenue,...,incomeBeforeTaxRatio,incomeTaxExpense,netIncome,netIncomeRatio,eps,epsdiluted,weightedAverageShsOut,weightedAverageShsOutDil,link,finalLink
0,2021-10-31,RY.TO,CAD,None,2021-10-31,2021-10-31,2021,FY,45646000000,0.0,...,0.451978,4581000000,16038000000,0.351356,11.263313,11.263313,1423915000,1423915000,https://www.sedar.com/ModifyCompanyDocumentSea...,https://www.sedar.com/ModifyCompanyDocumentSea...
1,2020-10-31,RY.TO,CAD,None,2020-10-31,2020-10-31,2020,FY,43421000000,0.0,...,0.331383,2952000000,11432000000,0.263283,7.840000,7.820000,1423915000,1428770000,https://www.sedar.com/ModifyCompanyDocumentSea...,https://www.sedar.com/ModifyCompanyDocumentSea...
2,2019-10-31,RY.TO,CAD,None,2019-10-31,2019-10-31,2019,FY,41683000000,0.0,...,0.381786,3043000000,12860000000,0.308519,8.780000,8.750000,1434779000,1440682000,https://www.sedar.com/ModifyCompanyDocumentSea...,https://www.sedar.com/ModifyCompanyDocumentSea...

In [28]:
url_cf_list

['https://financialmodelingprep.com/api/v3/cash-flow-statement/RY.TO?limit=100&apikey=89d4891348727c3950b79b9067127c3f',
 'https://financialmodelingprep.com/api/v3/cash-flow-statement/EDF.PA?limit=100&apikey=89d4891348727c3950b79b9067127c3f',
 'https://financialmodelingprep.com/api/v3/cash-flow-statement/SAP.DE?limit=100&apikey=89d4891348727c3950b79b9067127c3f',
 'https://financialmodelingprep.com/api/v3/cash-flow-statement/RELIANCE.NS?limit=100&apikey=89d4891348727c3950b79b9067127c3f',
 'https://financialmodelingprep.com/api/v3/cash-flow-statement/GLEN.L?limit=100&apikey=89d4891348727c3950b79b9067127c3f',
 'https://financialmodelingprep.com/api/v3/cash-flow-statement/1797.HK?limit=100&apikey=89d4891348727c3950b79b9067127c3f',
 'https://financialmodelingprep.com/api/v3/cash-flow-statement/APT.AX?limit=100&apikey=89d4891348727c3950b79b9067127c3f',
 'https://financialmodelingprep.com/api/v3/cash-flow-statement/FHZN.SW?limit=100&apikey=89d4891348727c3950b79b9067127c3f']

In [19]:
for url in url_income_list : 
    nation_example = extractor(url)
    print(nation_example)

          date symbol reportedCurrency   cik fillingDate acceptedDate  \
0   2021-10-31  RY.TO              CAD  None  2021-10-31   2021-10-31
1   2020-10-31  RY.TO              CAD  None  2020-10-31   2020-10-31
2   2019-10-31  RY.TO              CAD  None  2019-10-31   2019-10-31
3   2018-10-31  RY.TO              CAD  None  2018-10-31   2018-10-31
4   2017-10-31  RY.TO              CAD  None  2017-10-31   2017-10-31
5   2016-10-31  RY.TO              CAD  None  2016-10-31   2016-10-31
6   2015-10-31  RY.TO              CAD  None  2015-10-31   2015-10-31
7   2014-10-31  RY.TO              CAD  None  2014-10-31   2014-10-31
8   2013-10-31  RY.TO              CAD  None  2013-10-31   2013-10-31
9   2012-10-31  RY.TO              CAD  None  2012-10-31   2012-10-31
10  2011-10-31  RY.TO              CAD  None  2011-10-31   2011-10-31
11  2010-10-31  RY.TO              CAD  None  2010-10-31   2010-10-31
12  2009-10-31  RY.TO              CAD  None  2009-10-31   2009-10-31
13  2008-10-31  RY.TO              CAD  None  2008-10-31   2008-10-31
14  2007-10-31  RY.TO              CAD  None  2007-10-31   2007-10-31
15  2006-10-31  RY.TO              CAD  None  2006-10-31   2006-10-31
16  2005-10-31  RY.TO              CAD  None  2005-10-31   2005-10-31
17  2004-10-31  RY.TO              CAD  None  2004-10-31   2004-10-31
18  2003-10-31  RY.TO              CAD  None  2003-10-31   2003-10-31
19  2002-10-31  RY.TO              CAD  None  2002-10-31   2002-10-31
20  2001-10-31  RY.TO              CAD  None  2001-10-31   2001-10-31
21  2000-10-31  RY.TO              CAD  None  2000-10-31   2000-10-31
22  1999-10-31  RY.TO              CAD  None  1999-10-31   1999-10-31
23  1998-10-31  RY.TO              CAD  None  1998-10-31   1998-10-31
24  1997-10-31  RY.TO              CAD  None  1997-10-31   1997-10-31
25  1996-10-31  RY.TO              CAD  None  1996-10-31   1996-10-31
26  1995-10-31  RY.TO              CAD  None  1995-10-31   1995-10-31
27  1994-10-31  RY.TO              CAD  None  1994-10-31   1994-10-31
28  1993-10-31  RY.TO              CAD  None  1993-10-31   1993-10-31

   calendarYear period      revenue  costOfRevenue  ...  incomeBeforeTaxRatio  \
0          2021     FY  45646000000            0.0  ...              0.451978
1          2020     FY  43421000000            0.0  ...              0.331383
2          2019     FY  41683000000            0.0  ...              0.381786
3          2018     FY  39839000000            0.0  ...              0.395592
4          2017     FY  37069000000            0.0  ...              0.395802
5          2016     FY  34250000000            0.0  ...              0.388292
6          2015     FY  32132000000            0.0  ...              0.392848
7          2014     FY  30373000000            0.0  ...              0.385540
8          2013     FY  28077000000            0.0  ...              0.378139
9          2012     FY  26128000000            0.0  ...              0.370867
10         2011     FY  24070000000            0.0  ...              0.359036
11         2010     FY  23222000000            0.0  ...              0.300060
12         2009     FY  24497000000            0.0  ...              0.225579
13         2008     FY  19951000000            0.0  ...              0.300987
14         2007     FY  19963000000            0.0  ...              0.351901
15         2006     FY  18128000000            0.0  ...              0.342233
16         2005     FY  19215964104            0.0  ...              0.245361
17         2004     FY  18121189953            0.0  ...              0.223441
18         2003     FY  17417908480            0.0  ...              0.256360
19         2002     FY  15719626169            0.0  ...              0.262485
20         2001     FY  14730995081            0.0  ...              0.254579
21         2000     FY  11958574474            0.0  ...              0.302725
22         1999     FY  10607915258            0.0  ...              0.254431
23         1998     FY  10049081648            0.0  ...              0.298443
24         1997     FY   9278974792            0.0  ...              0.298422
25         1996     FY   7911036789            0.0  ...              0.291993
26         1995     FY   7257127561            0.0  ...              0.277952
27         1994     FY   7365075072            0.0  ...              0.247603
28         1993     FY   6490000000            0.0  ...              0.045455

    incomeTaxExpense    netIncome  netIncomeRatio        eps  epsdiluted  \
0       4.581000e+09  16038000000        0.351356  11.263313   11.263313
1       2.952000e+09  11432000000        0.263283   7.840000    7.820000
2       3.043000e+09  12860000000        0.308519   8.780000    8.750000
3       3.329000e+09  12400000000        0.311253   8.390000    8.360000
4       3.203000e+09  11428000000        0.308290   7.590000    7.560000
5       2.841000e+09  10405000000        0.303796   6.800000    6.780000
6       2.597000e+09   9925000000        0.308882   6.750000    6.730000
7       2.706000e+09   8910000000        0.293353   6.030000    6.000000
8       2.188000e+09   8331000000        0.296720   5.600000    5.540000
9       2.100000e+09   7442000000        0.284829   4.980000    4.930000
10      1.888000e+09   4852000000        0.201579   3.210000    3.190000
11      1.646000e+09   5223000000        0.224916   3.490000    3.460000
12      1.568000e+09   3858000000        0.157489   2.590000    2.570000
13      1.369000e+09   4555000000        0.228309   3.410000    3.380000
14      1.392000e+09   5492000000        0.275109   4.240000    4.190000
15      1.403000e+09   4728000000        0.260812   3.650000    3.590000
16      1.277601e+09   3387649073        0.176293   2.610000    2.565000
17      1.231407e+09   2817605462        0.155487   2.155000    2.125000
18      1.459844e+09   3005406831        0.172547   2.240000    2.215000
19      1.364486e+09   2761682243        0.175684   2.080000    2.060000
20      1.339470e+09   2410728456        0.163650   1.790000    1.775000
21      1.411818e+09   2208346025        0.184666   1.710000    1.700000
22      9.739591e+08   1725025747        0.162617   1.257620    1.242910
23      1.175027e+09   1824046921        0.181514   1.361320    1.330390
24      1.089987e+09   1679059287        0.180953   1.253980    1.232850
25      8.800000e+08   1429966555        0.180756   1.025920    1.025920
26      7.550529e+08   1262080043        0.173909   0.880980    0.880980
27      6.550791e+08   1168537806        0.158659   0.798030    0.798030
28     -5.000000e+06    300000000        0.046225   0.115000    0.115000

    weightedAverageShsOut  weightedAverageShsOutDil  \
0              1423915000                1423915000
1              1423915000                1428770000
2              1434779000                1440682000
3              1443894000                1450485000
4              1466988000                1474421000
5              1485876000                1494137000
6              1442935000                1449509000
7              1442553000                1452003000
8              1443735000                1466529000
9              1442167000                1468287000
10             1430722000                1437904000
11             1420719000                1433754000
12             1398675000                1412126000
13             1305706000                1319744000
14             1273185000                1289314000
15             1279956000                1299785000
16             1283434000                1304680000
17             1292046000                1312094000
18             1324160000                1339250000
19             1345142000                1358306000
20             1283032000                1294432000
21             1212778000                1220189568
22             1246835074                1261591528
23             1233447792                1262124000
24             1234542671                1255701681
25             1253528606                1253528606
26             1241757276                1241757276
27             1253763708                1253763708
28             1269565217                1269565217

                                                 link  \
0   https://www.sedar.com/ModifyCompanyDocumentSea...
1   https://www.sedar.com/ModifyCompanyDocumentSea...
2   https://www.sedar.com/ModifyCompanyDocumentSea...
3   https://www.sedar.com/ModifyCompanyDocumentSea...
4   https://www.sedar.com/ModifyCompanyDocumentSea...
5   https://www.sedar.com/ModifyCompanyDocumentSea...
6   https://www.sedar.com/ModifyCompanyDocumentSea...
7   https://www.sedar.com/ModifyCompanyDocumentSea...
8   https://www.sedar.com/ModifyCompanyDocumentSea...
9   https://www.sedar.com/ModifyCompanyDocumentSea...
10  https://www.sedar.com/ModifyCompanyDocumentSea...
11  https://www.sedar.com/ModifyCompanyDocumentSea...
12  https://www.sedar.com/ModifyCompanyDocumentSea...
13  https://www.sedar.com/ModifyCompanyDocumentSea...
14  https://www.sedar.com/ModifyCompanyDocumentSea...
15  https://www.sedar.com/ModifyCompanyDocumentSea...
16  https://www.sedar.com/ModifyCompanyDocumentSea...
17  https://www.sedar.com/ModifyCompanyDocumentSea...
18  https://www.sedar.com/ModifyCompanyDocumentSea...
19  https://www.sedar.com/ModifyCompanyDocumentSea...
20  https://www.sedar.com/ModifyCompanyDocumentSea...
21  https://www.sedar.com/ModifyCompanyDocumentSea...
22  https://www.sedar.com/ModifyCompanyDocumentSea...
23  https://www.sedar.com/ModifyCompanyDocumentSea...
24  https://www.sedar.com/ModifyCompanyDocumentSea...
25  https://www.sedar.com/ModifyCompanyDocumentSea...
26  https://www.sedar.com/ModifyCompanyDocumentSea...
27  https://www.sedar.com/ModifyCompanyDocumentSea...
28  https://www.sedar.com/ModifyCompanyDocumentSea...

                                            finalLink
0   https://www.sedar.com/ModifyCompanyDocumentSea...
1   https://www.sedar.com/ModifyCompanyDocumentSea...
2   https://www.sedar.com/ModifyCompanyDocumentSea...
3   https://www.sedar.com/ModifyCompanyDocumentSea...
4   https://www.sedar.com/ModifyCompanyDocumentSea...
5   https://www.sedar.com/ModifyCompanyDocumentSea...
6   https://www.sedar.com/ModifyCompanyDocumentSea...
7   https://www.sedar.com/ModifyCompanyDocumentSea...
8   https://www.sedar.com/ModifyCompanyDocumentSea...
9   https://www.sedar.com/ModifyCompanyDocumentSea...
10  https://www.sedar.com/ModifyCompanyDocumentSea...
11  https://www.sedar.com/ModifyCompanyDocumentSea...
12  https://www.sedar.com/ModifyCompanyDocumentSea...
13  https://www.sedar.com/ModifyCompanyDocumentSea...
14  https://www.sedar.com/ModifyCompanyDocumentSea...
15  https://www.sedar.com/ModifyCompanyDocumentSea...
16  https://www.sedar.com/ModifyCompanyDocumentSea...
17  https://www.sedar.com/ModifyCompanyDocumentSea...
18  https://www.sedar.com/ModifyCompanyDocumentSea...
19  https://www.sedar.com/ModifyCompanyDocumentSea...
20  https://www.sedar.com/ModifyCompanyDocumentSea...
21  https://www.sedar.com/ModifyCompanyDocumentSea...
22  https://www.sedar.com/ModifyCompanyDocumentSea...
23  https://www.sedar.com/ModifyCompanyDocumentSea...
24  https://www.sedar.com/ModifyCompanyDocumentSea...
25  https://www.sedar.com/ModifyCompanyDocumentSea...
26  https://www.sedar.com/ModifyCompanyDocumentSea...
27  https://www.sedar.com/ModifyCompanyDocumentSea...
28  https://www.sedar.com/ModifyCompanyDocumentSea...

[29 rows x 38 columns]

          date  symbol reportedCurrency   cik fillingDate acceptedDate  \
0   2020-12-31  EDF.PA              EUR  None  2020-12-31   2020-12-31
1   2019-12-31  EDF.PA              EUR  None  2019-12-31   2019-12-31
2   2018-12-31  EDF.PA              EUR  None  2018-12-31   2018-12-31
3   2017-12-31  EDF.PA              EUR  None  2017-12-31   2017-12-31
4   2016-12-31  EDF.PA              EUR  None  2016-12-31   2016-12-31
5   2015-12-31  EDF.PA              EUR  None  2015-12-31   2015-12-31
6   2014-12-31  EDF.PA              EUR  None  2014-12-31   2014-12-31
7   2013-12-31  EDF.PA              EUR  None  2013-12-31   2013-12-31
8   2012-12-31  EDF.PA              EUR  None  2012-12-31   2012-12-31
9   2011-12-31  EDF.PA              EUR  None  2011-12-31   2011-12-31
10  2010-12-31  EDF.PA              EUR  None  2010-12-31   2010-12-31
11  2009-12-31  EDF.PA              EUR  None  2009-12-31   2009-12-31
12  2008-12-31  EDF.PA              EUR  None  2008-12-31   2008-12-31
13  2007-12-31  EDF.PA              EUR  None  2007-12-31   2007-12-31
14  2006-12-31  EDF.PA              EUR  None  2006-12-31   2006-12-31
15  2005-12-31  EDF.PA              EUR  None  2005-12-31   2005-12-31
16  2004-12-31  EDF.PA              EUR  None  2004-12-31   2004-12-31
17  2003-12-31  EDF.PA              EUR  None  2003-12-31   2003-12-31
18  2002-12-31  EDF.PA              EUR  None  2002-12-31   2002-12-31

   calendarYear period      revenue  costOfRevenue  ...  incomeBeforeTaxRatio  \
0          2020     FY  69031000000    28061000000  ...              0.018731
1          2019     FY  71317000000    30757000000  ...              0.089726
2          2018     FY  68976000000    29377000000  ...              0.006857
3          2017     FY  69632000000    34862000000  ...              0.048842
4          2016     FY  71203000000    33808000000  ...              0.058719
5          2015     FY  75006000000    36883000000  ...              0.022558
6          2014     FY  72874000000    34738000000  ...              0.074553
7          2013     FY  75594000000    37852000000  ...              0.070402
8          2012     FY  72729000000    35457000000  ...              0.067140
9          2011     FY  65307000000    40126000000  ...              0.068997
10         2010     FY  65165000000    26021000000  ...              0.027837
11         2009     FY  66336000000    26558000000  ...              0.084147
12         2008     FY  64279000000    27022000000  ...              0.073803
13         2007     FY  59637000000    23215000000  ...              0.125040
14         2006     FY  58932000000    23949000000  ...              0.112927
15         2005     FY  51051000000    16693000000  ...              0.090478
16         2004     FY  46928000000    23476000000  ...              0.073794
17         2003     FY  44919000000    22554000000  ...              0.073911
18         2002     FY  48359000000    25588000000  ...              0.043198

    incomeTaxExpense   netIncome  netIncomeRatio       eps  epsdiluted  \
0          945000000   650000000        0.009416  0.050000    0.050000
1         1581000000  5155000000        0.072283  1.500000    1.500000
2         -149000000  1177000000        0.017064  0.200000    0.200000
3          147000000  3173000000        0.045568  0.980000    0.980000
4         1388000000  2851000000        0.040040  1.066326    1.066326
5          483000000  1187000000        0.015825  0.296717    0.296717
6         1839000000  3701000000        0.050786  1.650488    1.650488
7         1942000000  3517000000        0.046525  1.706122    1.706122
8         1586000000  3316000000        0.045594  1.669033    1.669033
9         1305000000  3010000000        0.046090  1.511402    1.511402
10        1079000000  1249000000        0.019167  0.509982    0.509982
11        1614000000  4088000000        0.061626  1.984294    1.984294
12        1561000000  3535000000        0.054995  1.733940    1.733940
13        1841000000  5618000000        0.094203  2.855900    2.855900
14        1146000000  5605000000        0.095110  2.855900    2.846628
15        1451000000  3350000000        0.065621  1.826664    1.826664
16        1494000000  1327000000        0.028277  0.760337    0.760337
17        1567000000   935000000        0.020815  0.488772    0.488772
18         986000000   415000000        0.008582  0.274328    0.274328

    weightedAverageShsOut  weightedAverageShsOutDil  link  finalLink
0              3106323609                3115472740
1              3029504511                3029504511
2              2968327473                2968327473
3              2660243412                2660243412
4              2136050242                2136050242
5              2005939557                2005939557
6              2004299591                2004299591
7              1997889633                1997889633
8              1992302110                1992302110
9              1992275364                1992275364
10             1993445680                1993445680
11             1965545643                1965545643
12             1962337094                1962337094
13             1965056056                1965056056
14             1965046108                1965046108
15             1777520464                1777520464
16             1753374900                1753374900
17             1753374900                1753374900
18             1753374900                1753374900

[19 rows x 38 columns]
          date  symbol reportedCurrency   cik fillingDate acceptedDate  \
0   2021-12-31  SAP.DE              EUR  None  2021-12-31   2021-12-31
1   2020-12-31  SAP.DE              EUR  None  2020-12-31   2020-12-31
2   2019-12-31  SAP.DE              EUR  None  2019-12-31   2019-12-31
3   2018-12-31  SAP.DE              EUR  None  2018-12-31   2018-12-31
4   2017-12-31  SAP.DE              EUR  None  2017-12-31   2017-12-31
5   2016-12-31  SAP.DE              EUR  None  2016-12-31   2016-12-31
6   2015-12-31  SAP.DE              EUR  None  2015-12-31   2015-12-31
7   2014-12-31  SAP.DE              EUR  None  2014-12-31   2014-12-31
8   2013-12-31  SAP.DE              EUR  None  2013-12-31   2013-12-31
9   2012-12-31  SAP.DE              EUR  None  2012-12-31   2012-12-31
10  2011-12-31  SAP.DE              EUR  None  2011-12-31   2011-12-31
11  2010-12-31  SAP.DE              EUR  None  2010-12-31   2010-12-31
12  2009-12-31  SAP.DE              EUR  None  2009-12-31   2009-12-31
13  2008-12-31  SAP.DE              EUR  None  2008-12-31   2008-12-31
14  2007-12-31  SAP.DE              EUR  None  2007-12-31   2007-12-31
15  2006-12-31  SAP.DE              EUR  None  2006-12-31   2006-12-31
16  2005-12-31  SAP.DE              EUR  None  2005-12-31   2005-12-31
17  2004-12-31  SAP.DE              EUR  None  2004-12-31   2004-12-31
18  2003-12-31  SAP.DE              EUR  None  2003-12-31   2003-12-31
19  2002-12-31  SAP.DE              EUR  None  2002-12-31   2002-12-31
20  2001-12-31  SAP.DE              EUR  None  2001-12-31   2001-12-31
21  2000-12-31  SAP.DE              EUR  None  2000-12-31   2000-12-31
22  1999-12-31  SAP.DE              EUR  None  1999-12-31   1999-12-31
23  1998-12-31  SAP.DE              EUR  None  1998-12-31   1998-12-31
24  1997-12-31  SAP.DE              EUR  None  1997-12-31   1997-12-31
25  1996-12-31  SAP.DE              EUR  None  1996-12-31   1996-12-31

   calendarYear period       revenue  costOfRevenue  ...  \
0          2021     FY  2.784200e+10   7.946000e+09  ...
1          2020     FY  2.733800e+10   7.886000e+09  ...
2          2019     FY  2.755300e+10   8.355000e+09  ...
3          2018     FY  2.470800e+10   7.462000e+09  ...
4          2017     FY  2.346000e+10   7.051000e+09  ...
5          2016     FY  2.206200e+10   6.583000e+09  ...
6          2015     FY  2.079300e+10   6.626000e+09  ...
7          2014     FY  1.756100e+10   5.272000e+09  ...
8          2013     FY  1.681500e+10   4.999000e+09  ...
9          2012     FY  1.622300e+10   5.065000e+09  ...
10         2011     FY  1.423300e+10   4.355000e+09  ...
11         2010     FY  1.246400e+10   3.894000e+09  ...
12         2009     FY  1.067200e+10   3.565000e+09  ...
13         2008     FY  1.156312e+10   3.941532e+09  ...
14         2007     FY  1.025856e+10   3.406030e+09  ...
15         2006     FY  9.401404e+09   3.177734e+09  ...
16         2005     FY  8.505967e+09   2.915626e+09  ...
17         2004     FY  7.508942e+09   2.585853e+09  ...
18         2003     FY  7.012345e+09   2.528681e+09  ...
19         2002     FY  7.419542e+09   2.818705e+09  ...
20         2001     FY  7.343628e+09   2.853607e+09  ...
21         2000     FY  6.261951e+09   2.247786e+09  ...
22         1999     FY  5.114027e+09   2.006136e+09  ...
23         1998     FY  4.325800e+09   1.761340e+09  ...
24         1997     FY  3.083221e+09   3.061633e+08  ...
25         1996     FY  3.722150e+09   3.943840e+08  ...

    incomeBeforeTaxRatio  incomeTaxExpense     netIncome  netIncomeRatio  \
0               0.245923      1.471000e+09  5.256000e+09        0.188780
1               0.264101      1.938000e+09  5.145000e+09        0.188200
2               0.166806      1.226000e+09  3.321000e+09        0.120531
3               0.226647      1.511000e+09  4.083000e+09        0.165250
4               0.214237      9.700000e+08  4.018000e+09        0.171270
5               0.220424      1.229000e+09  3.646000e+09        0.165262
6               0.191940      9.350000e+08  3.064000e+09        0.147357
7               0.247993      1.075000e+09  3.280000e+09        0.186778
8               0.261433      1.071000e+09  3.326000e+09        0.197800
9               0.235715      1.000000e+09  2.823000e+09        0.174012
10              0.334996      1.329000e+09  3.438000e+09        0.241551
11              0.187580      5.250000e+08  1.811000e+09        0.145298
12              0.228167      6.850000e+08  1.748000e+09        0.163793
13              0.238057      8.246543e+08  1.867684e+09        0.161521
14              0.279000      9.224952e+08  1.922494e+09        0.187404
15              0.284489      8.015504e+08  1.871234e+09        0.199038
16              0.272115      8.164326e+08  1.495271e+09        0.175791
17              0.275819      7.567099e+08  1.309553e+09        0.174399
18              0.251929      6.914310e+08  1.075183e+09        0.153327
19              0.149379      5.992466e+08  5.090737e+08        0.068613
20              0.144016      4.765378e+08  5.810615e+08        0.079125
21              0.163799      3.916422e+08  6.340569e+08        0.101255
22              0.191267      3.766971e+08  6.014497e+08        0.117608
23              0.221138      4.203614e+08  5.362379e+08        0.123963
24              0.267825      3.580406e+08  4.677241e+08        0.151700
25              0.259853      3.996770e+08  5.675360e+08        0.152475

         eps  epsdiluted  weightedAverageShsOut  weightedAverageShsOutDil  \
0   4.560948    4.560948             1179579340                1179579340
1   4.350000    4.350000             1182000000                1182000000
2   2.800000    2.800000             1194000000                1194000000
3   3.420000    3.420000             1194000000                1194000000
4   3.360000    3.350000             1197000000                1198000000
5   3.030000    3.030000             1198000000                1199000000
6   2.560000    2.560000             1197000000                1198000000
7   2.740000    2.740000             1195000000                1198000000
8   2.790000    2.780000             1193000000                1195000000
9   2.370000    2.370000             1191000000                1192000000
10  2.890000    2.890000             1189000000                1190000000
11  1.530000    1.530000             1188000000                1188000000
12  1.500000    1.500000             1188000000                1188000000
13  1.567687    1.567687             1190000000                1191000000
14  1.594417    1.594417             1205766169                1205766169
15  1.528668    1.518677             1224094416                1232147347
16  1.202558    1.197578             1243409213                1248579308
17  1.057839    1.052826             1237950821                1243845826
18  0.868846    0.866342             1237484498                1241060895
19  0.405017    0.405017             1256919330                1256919330
20  0.462838    0.462838             1255432569                1255432569
21  0.502311    0.502311             1257073000                1257073000
22  0.480000    0.480000             1254768000                1254768000
23  0.426330    0.426330             1254768000                1254768000
24  0.373636    0.373636             1251600000                1251600000
25  0.453448    0.453448             1251600000                1251600000

                                                 link  \
0   https://www.bundesanzeiger.de/pub/de/suche;www...
1   https://www.bundesanzeiger.de/pub/de/suche;www...
2   https://www.bundesanzeiger.de/pub/de/suche;www...
3   https://www.bundesanzeiger.de/pub/de/suche;www...
4   https://www.bundesanzeiger.de/pub/de/suche;www...
5   https://www.bundesanzeiger.de/pub/de/suche;www...
6   https://www.bundesanzeiger.de/pub/de/suche;www...
7   https://www.bundesanzeiger.de/pub/de/suche;www...
8   https://www.bundesanzeiger.de/pub/de/suche;www...
9   https://www.bundesanzeiger.de/pub/de/suche;www...
10  https://www.bundesanzeiger.de/pub/de/suche;www...
11  https://www.bundesanzeiger.de/pub/de/suche;www...
12  https://www.bundesanzeiger.de/pub/de/suche;www...
13  https://www.bundesanzeiger.de/pub/de/suche;www...
14  https://www.bundesanzeiger.de/pub/de/suche;www...
15  https://www.bundesanzeiger.de/pub/de/suche;www...
16  https://www.bundesanzeiger.de/pub/de/suche;www...
17  https://www.bundesanzeiger.de/pub/de/suche;www...
18  https://www.bundesanzeiger.de/pub/de/suche;www...
19  https://www.bundesanzeiger.de/pub/de/suche;www...
20  https://www.bundesanzeiger.de/pub/de/suche;www...
21  https://www.bundesanzeiger.de/pub/de/suche;www...
22  https://www.bundesanzeiger.de/pub/de/suche;www...
23  https://www.bundesanzeiger.de/pub/de/suche;www...
24  https://www.bundesanzeiger.de/pub/de/suche;www...
25  https://www.bundesanzeiger.de/pub/de/suche;www...

                                            finalLink
0   https://www.bundesanzeiger.de/pub/de/suche;www...
1   https://www.bundesanzeiger.de/pub/de/suche;www...
2   https://www.bundesanzeiger.de/pub/de/suche;www...
3   https://www.bundesanzeiger.de/pub/de/suche;www...
4   https://www.bundesanzeiger.de/pub/de/suche;www...
5   https://www.bundesanzeiger.de/pub/de/suche;www...
6   https://www.bundesanzeiger.de/pub/de/suche;www...
7   https://www.bundesanzeiger.de/pub/de/suche;www...
8   https://www.bundesanzeiger.de/pub/de/suche;www...
9   https://www.bundesanzeiger.de/pub/de/suche;www...
10  https://www.bundesanzeiger.de/pub/de/suche;www...
11  https://www.bundesanzeiger.de/pub/de/suche;www...
12  https://www.bundesanzeiger.de/pub/de/suche;www...
13  https://www.bundesanzeiger.de/pub/de/suche;www...
14  https://www.bundesanzeiger.de/pub/de/suche;www...
15  https://www.bundesanzeiger.de/pub/de/suche;www...
16  https://www.bundesanzeiger.de/pub/de/suche;www...
17  https://www.bundesanzeiger.de/pub/de/suche;www...
18  https://www.bundesanzeiger.de/pub/de/suche;www...
19  https://www.bundesanzeiger.de/pub/de/suche;www...
20  https://www.bundesanzeiger.de/pub/de/suche;www...
21  https://www.bundesanzeiger.de/pub/de/suche;www...
22  https://www.bundesanzeiger.de/pub/de/suche;www...
23  https://www.bundesanzeiger.de/pub/de/suche;www...
24  https://www.bundesanzeiger.de/pub/de/suche;www...
25  https://www.bundesanzeiger.de/pub/de/suche;www...

[26 rows x 38 columns]

          date       symbol reportedCurrency   cik fillingDate acceptedDate  \
0   2021-03-31  RELIANCE.NS              INR  None  2021-03-31   2021-03-31
1   2020-03-31  RELIANCE.NS              INR  None  2020-03-31   2020-03-31
2   2019-03-31  RELIANCE.NS              INR  None  2019-03-31   2019-03-31
3   2018-03-31  RELIANCE.NS              INR  None  2018-03-31   2018-03-31
4   2017-03-31  RELIANCE.NS              INR  None  2017-03-31   2017-03-31
5   2016-03-31  RELIANCE.NS              INR  None  2016-03-31   2016-03-31
6   2015-03-31  RELIANCE.NS              INR  None  2015-03-31   2015-03-31
7   2014-03-31  RELIANCE.NS              INR  None  2014-03-31   2014-03-31
8   2013-03-31  RELIANCE.NS              INR  None  2013-03-31   2013-03-31
9   2012-03-31  RELIANCE.NS              INR  None  2012-03-31   2012-03-31
10  2011-03-31  RELIANCE.NS              INR  None  2011-03-31   2011-03-31
11  2010-03-31  RELIANCE.NS              INR  None  2010-03-31   2010-03-31
12  2009-03-31  RELIANCE.NS              INR  None  2009-03-31   2009-03-31
13  2008-03-31  RELIANCE.NS              INR  None  2008-03-31   2008-03-31
14  2007-03-31  RELIANCE.NS              INR  None  2007-03-31   2007-03-31
15  2006-03-31  RELIANCE.NS              INR  None  2006-03-31   2006-03-31
16  2005-03-31  RELIANCE.NS              INR  None  2005-03-31   2005-03-31

   calendarYear period        revenue  costOfRevenue  ...  \
0          2021     FY  4669240000000  3390610000000  ...
1          2020     FY  5967430000000  4514360000000  ...
2          2019     FY  5671350000000  4436640000000  ...
3          2018     FY  3916770000000  3076120000000  ...
4          2017     FY  3053820000000  2443320000000  ...
5          2016     FY  2765440000000  2203480000000  ...
6          2015     FY  3754350000000  3271770000000  ...
7          2014     FY  4344600000000  3925880000000  ...
8          2013     FY  3970620000000  3583300000000  ...
9          2012     FY  3585010000000  3099420000000  ...
10         2011     FY  2658106000000  2141778000000  ...
11         2010     FY  2037397200000  1633864400000  ...
12         2009     FY  1512240100000  1211307100000  ...
13         2008     FY  1371466600000  1037762300000  ...
14         2007     FY  1137701100000   851961100000  ...
15         2006     FY   830248100000   610354400000  ...
16         2005     FY   665976600000   497436000000  ...

    incomeBeforeTaxRatio  incomeTaxExpense     netIncome  netIncomeRatio  \
0               0.118780       17220000000  491280000000        0.105216
1               0.089831      137260000000  393540000000        0.065948
2               0.097379      153900000000  395880000000        0.069803
3               0.126191      133460000000  360750000000        0.092104
4               0.131095      102010000000  299010000000        0.097913
5               0.130102       82640000000  276300000000        0.099912
6               0.082875       74740000000  235660000000        0.062770
7               0.066204       62150000000  224930000000        0.051772
8               0.066027       53310000000  208790000000        0.052584
9               0.070873       56910000000  197170000000        0.054998
10              0.090497       47834400000  192715200000        0.072501
11              0.140767       42562800000  244235800000        0.119876
12              0.118163       29188300000  149503100000        0.098862
13              0.167783       34875900000  195232400000        0.142353
14              0.128742      -25722900000  120747400000        0.106133
15              0.132783       16295000000   93947600000        0.113156
16              0.137024       14972200000   76282300000        0.114542

          eps  epsdiluted  weightedAverageShsOut  weightedAverageShsOutDil  \
0   76.370000   75.210000             6432874848                6532138901
1   62.893829   62.893829             6256889765                6257175880
2   66.192561   66.172749             5980960539                5982387168
3   60.367774   60.318243             5975926139                5981030543
4   50.189256   50.095148             5957570975                5968863160
5   46.449703   46.449703             5947773511                5947773511
6   39.678884   39.678884             5939489320                5939489320
7   37.915598   37.915598             5932219874                5932219874
8   34.993299   34.993299             5951100493                5951100493
9   32.764426   32.764426             6020273552                6020273552
10  32.070999   32.070999             6015478102                6015478102
11  40.758649   40.758649             6011464042                6011464042
12  26.803430   26.803430             5585713829                5585713829
13  33.257254   33.257254             5869710944                5869710944
14  20.572493   20.572493             5869710944                5869710944
15  16.701685   16.701685             5626868414                5626868414
16  13.534209   13.534209             5636565139                5636565139

                                                 link  \
0   https://www.nseindia.com/companies-listing/cor...
1   https://www.nseindia.com/companies-listing/cor...
2   https://www.nseindia.com/companies-listing/cor...
3   https://www.nseindia.com/companies-listing/cor...
4   https://www.nseindia.com/companies-listing/cor...
5   https://www.nseindia.com/companies-listing/cor...
6   https://www.nseindia.com/companies-listing/cor...
7   https://www.nseindia.com/companies-listing/cor...
8   https://www.nseindia.com/companies-listing/cor...
9   https://www.nseindia.com/companies-listing/cor...
10  https://www.nseindia.com/companies-listing/cor...
11  https://www.nseindia.com/companies-listing/cor...
12  https://www.nseindia.com/companies-listing/cor...
13  https://www.nseindia.com/companies-listing/cor...
14  https://www.nseindia.com/companies-listing/cor...
15  https://www.nseindia.com/companies-listing/cor...
16  https://www.nseindia.com/companies-listing/cor...

                                            finalLink
0   https://www.nseindia.com/companies-listing/cor...
1   https://www.nseindia.com/companies-listing/cor...
2   https://www.nseindia.com/companies-listing/cor...
3   https://www.nseindia.com/companies-listing/cor...
4   https://www.nseindia.com/companies-listing/cor...
5   https://www.nseindia.com/companies-listing/cor...
6   https://www.nseindia.com/companies-listing/cor...
7   https://www.nseindia.com/companies-listing/cor...
8   https://www.nseindia.com/companies-listing/cor...
9   https://www.nseindia.com/companies-listing/cor...
10  https://www.nseindia.com/companies-listing/cor...
11  https://www.nseindia.com/companies-listing/cor...
12  https://www.nseindia.com/companies-listing/cor...
13  https://www.nseindia.com/companies-listing/cor...
14  https://www.nseindia.com/companies-listing/cor...
15  https://www.nseindia.com/companies-listing/cor...
16  https://www.nseindia.com/companies-listing/cor...

[17 rows x 38 columns]
          date  symbol reportedCurrency   cik fillingDate acceptedDate  \
0   2021-12-31  GLEN.L              USD  None  2021-12-31   2021-12-31
1   2020-12-31  GLEN.L              USD  None  2020-12-31   2020-12-31
2   2019-12-31  GLEN.L              USD  None  2019-12-31   2019-12-31
3   2018-12-31  GLEN.L              USD  None  2018-12-31   2018-12-31
4   2017-12-31  GLEN.L              USD  None  2017-12-31   2017-12-31
5   2016-12-31  GLEN.L              USD  None  2016-12-31   2016-12-31
6   2015-12-31  GLEN.L              USD  None  2015-12-31   2015-12-31
7   2014-12-31  GLEN.L              USD  None  2014-12-31   2014-12-31
8   2013-12-31  GLEN.L              USD  None  2013-12-31   2013-12-31
9   2012-12-31  GLEN.L              USD  None  2012-12-31   2012-12-31
10  2011-12-31  GLEN.L              USD  None  2011-12-31   2011-12-31
11  2010-12-31  GLEN.L              USD  None  2010-12-31   2010-12-31
12  2009-12-31  GLEN.L              USD  None  2009-12-31   2009-12-31
13  2008-12-31  GLEN.L              USD  None  2008-12-31   2008-12-31

   calendarYear period       revenue  costOfRevenue  ...  \
0          2021     FY  2.037510e+11   1.913700e+11  ...
1          2020     FY  1.423380e+11   1.386400e+11  ...
2          2019     FY  2.151110e+11   2.104340e+11  ...
3          2018     FY  2.197540e+11   2.106980e+11  ...
4          2017     FY  2.054760e+11   1.976950e+11  ...
5          2016     FY  1.529480e+11   1.497630e+11  ...
6          2015     FY  1.704970e+11   1.669820e+11  ...
7          2014     FY  2.210730e+11   2.143440e+11  ...
8          2013     FY  2.326940e+11   2.271450e+11  ...
9          2012     FY  2.144360e+11   2.104350e+11  ...
10         2011     FY  1.861520e+11   1.819380e+11  ...
11         2010     FY  1.449780e+11   1.404670e+11  ...
12         2009     FY  1.063640e+11   1.031330e+11  ...
13         2008     FY  1.522360e+11   1.475650e+11  ...

    incomeBeforeTaxRatio  incomeTaxExpense     netIncome  netIncomeRatio  \
0               0.036196      3.026000e+09  4.974000e+09        0.024412
1              -0.035943     -1.170000e+09 -1.903000e+09       -0.013370
2              -0.004128      6.180000e+08 -4.040000e+08       -0.001878
3               0.021292      2.063000e+09  3.408000e+09        0.015508
4               0.033683      1.759000e+09  5.777000e+09        0.028115
5              -0.003589      6.380000e+08  1.379000e+09        0.009016
6              -0.047015      9.800000e+07 -4.964000e+09       -0.029115
7               0.019238      1.809000e+09  2.308000e+09        0.010440
8              -0.030272      2.540000e+08 -7.402000e+09       -0.031810
9               0.005018     -7.600000e+07  1.004000e+09        0.004682
10              0.021509     -2.639996e+08  4.048000e+09        0.021746
11              0.029936      2.340001e+08  1.291000e+09        0.008905
12              0.018493      2.379996e+08  9.829992e+08        0.009242
13              0.008776      2.679997e+08  3.669998e+08        0.002411

         eps  epsdiluted  weightedAverageShsOut  weightedAverageShsOutDil  \
0   0.376337    0.376337            13216886000               13216886000
1  -0.140000   -0.140000            13216886000               13216886000
2  -0.030000   -0.030000            13684091000               13776565000
3   0.240000    0.240000            14151826000               14253527000
4   0.410000    0.400000            14256020000               14423044000
5   0.100000    0.100000            14224100000               14358279000
6  -0.370000   -0.370000            13317970000               13317970000
7   0.180000    0.180000            13098766000               13151345000
8  -0.670000   -0.670000            11093184000               11093184000
9   0.140000    0.140000             6961936000                6988783000
10  0.720000    0.690000             5657794000                6087322000
11  0.190000    0.190000             6922714000                6922714000
12  0.142000    0.142000             6922714000                6922714000
13  0.053000    0.053000             6922714000                6922714000

                                                 link  \
0   https://find-and-update.company-information.se...
1   https://find-and-update.company-information.se...
2   https://find-and-update.company-information.se...
3   https://find-and-update.company-information.se...
4   https://find-and-update.company-information.se...
5   https://find-and-update.company-information.se...
6   https://find-and-update.company-information.se...
7   https://find-and-update.company-information.se...
8   https://find-and-update.company-information.se...
9   https://find-and-update.company-information.se...
10  https://find-and-update.company-information.se...
11  https://find-and-update.company-information.se...
12  https://find-and-update.company-information.se...
13  https://find-and-update.company-information.se...

                                            finalLink
0   https://find-and-update.company-information.se...
1   https://find-and-update.company-information.se...
2   https://find-and-update.company-information.se...
3   https://find-and-update.company-information.se...
4   https://find-and-update.company-information.se...
5   https://find-and-update.company-information.se...
6   https://find-and-update.company-information.se...
7   https://find-and-update.company-information.se...
8   https://find-and-update.company-information.se...
9   https://find-and-update.company-information.se...
10  https://find-and-update.company-information.se...
11  https://find-and-update.company-information.se...
12  https://find-and-update.company-information.se...
13  https://find-and-update.company-information.se...

[14 rows x 38 columns]

         date   symbol reportedCurrency   cik fillingDate acceptedDate  \
0  2021-05-31  1797.HK              CNY  None  2021-05-31   2021-05-31
1  2020-05-31  1797.HK              CNY  None  2020-05-31   2020-05-31
2  2019-05-31  1797.HK              CNY  None  2019-05-31   2019-05-31
3  2018-05-31  1797.HK              CNY  None  2018-05-31   2018-05-31
4  2017-05-31  1797.HK              CNY  None  2017-05-31   2017-05-31
5  2016-05-31  1797.HK              CNY  None  2016-05-31   2016-05-31

  calendarYear period     revenue  costOfRevenue  ...  incomeBeforeTaxRatio  \
0         2021     FY  1418655000     1006447000  ...             -1.169694
1         2020     FY  1080587000      587501000  ...             -0.662095
2         2019     FY   918911000      412502000  ...             -0.081597
3         2018     FY   650457000      252531000  ...              0.142483
4         2017     FY   446215000      142603000  ...              0.228435
5         2016     FY   334205000      109075000  ...              0.200889

   incomeTaxExpense   netIncome  netIncomeRatio       eps  epsdiluted  \
0        -1000000.0 -1658392000       -1.168989 -1.768380   -1.768380
1        42788000.0  -742005000       -0.686668 -0.790000   -0.790000
2       -10871000.0   -39773000       -0.043283 -0.060000   -0.060000
3        10653000.0    91375000        0.140478  0.100000    0.100000
4         9719000.0    93960000        0.210571  0.102805    0.102805
5         7587000.0    59551000        0.178187  0.065157    0.065157

   weightedAverageShsOut  weightedAverageShsOutDil  \
0              937803161                 937803161
1              937803161                 937803161
2              653236574                 653236574
3              913959102                 913959102
4              913959102                 913959102
5              913959102                 913959102

                                                link  \
0  https://www1.hkexnews.hk/search/titlesearch.xhtml
1  https://www1.hkexnews.hk/search/titlesearch.xhtml
2  https://www1.hkexnews.hk/search/titlesearch.xhtml
3  https://www1.hkexnews.hk/search/titlesearch.xhtml
4  https://www1.hkexnews.hk/search/titlesearch.xhtml
5  https://www1.hkexnews.hk/search/titlesearch.xhtml

                                           finalLink
0  https://www1.hkexnews.hk/search/titlesearch.xhtml
1  https://www1.hkexnews.hk/search/titlesearch.xhtml
2  https://www1.hkexnews.hk/search/titlesearch.xhtml
3  https://www1.hkexnews.hk/search/titlesearch.xhtml
4  https://www1.hkexnews.hk/search/titlesearch.xhtml
5  https://www1.hkexnews.hk/search/titlesearch.xhtml

[6 rows x 38 columns]
         date  symbol reportedCurrency   cik fillingDate acceptedDate  \
0  2021-06-30  APT.AX              AUD  None  2021-06-30   2021-06-30
1  2020-06-30  APT.AX              AUD  None  2020-06-30   2020-06-30
2  2019-06-30  APT.AX              AUD  None  2019-06-30   2019-06-30
3  2018-06-30  APT.AX              AUD  None  2018-06-30   2018-06-30
4  2017-06-30  APT.AX              AUD  None  2017-06-30   2017-06-30
5  2016-12-31  APT.AX              AUD  None  2016-12-31   2016-12-31

  calendarYear period      revenue  costOfRevenue  ...  incomeBeforeTaxRatio  \
0         2021     FY  924261000.0    249564000.0  ...             -0.210129
1         2020     FY  519151000.0    134295000.0  ...             -0.051588
2         2019     FY  264112000.0     59562000.0  ...             -0.161999
3         2018     FY  142345000.0     28210000.0  ...             -0.053293
4         2017     FY   29025831.0      5263468.0  ...             -0.496892
5         2016     FY          0.0            0.0  ...              0.000000

   incomeTaxExpense    netIncome  netIncomeRatio       eps  epsdiluted  \
0       -34819000.0 -156298000.0       -0.169106 -0.673934   -0.673934
1        -3925000.0  -19780000.0       -0.038101 -0.080000   -0.080000
2         1013000.0  -42861000.0       -0.162283 -0.180000   -0.180000
3         1390000.0   -8976000.0       -0.063058 -0.040000   -0.040000
4        -4803070.0   -9619630.0       -0.331416 -0.054800   -0.054800
5               0.0          0.0        0.000000  0.000000    0.000000

   weightedAverageShsOut  weightedAverageShsOutDil  link  finalLink
0              231919000                 231919000
1              259147000                 259147000
2              231919000                 231919000
3              214551000                 214551000
4              175463325                 175463325
5              161755550                 161755550

[6 rows x 38 columns]
          date   symbol reportedCurrency   cik fillingDate acceptedDate  \
0   2021-12-31  FHZN.SW              CHF  None  2021-12-31   2021-12-31
1   2020-12-31  FHZN.SW              CHF  None  2020-12-31   2020-12-31
2   2019-12-31  FHZN.SW              CHF  None  2019-12-31   2019-12-31
3   2018-12-31  FHZN.SW              CHF  None  2018-12-31   2018-12-31
4   2017-12-31  FHZN.SW              CHF  None  2017-12-31   2017-12-31
5   2016-12-31  FHZN.SW              CHF  None  2016-12-31   2016-12-31
6   2015-12-31  FHZN.SW              CHF  None  2015-12-31   2015-12-31
7   2014-12-31  FHZN.SW              CHF  None  2014-12-31   2014-12-31
8   2013-12-31  FHZN.SW              CHF  None  2013-12-31   2013-12-31
9   2012-12-31  FHZN.SW              CHF  None  2012-12-31   2012-12-31
10  2011-12-31  FHZN.SW              CHF  None  2011-12-31   2011-12-31
11  2010-12-31  FHZN.SW              CHF  None  2010-12-31   2010-12-31
12  2009-12-31  FHZN.SW              CHF  None  2009-12-31   2009-12-31
13  2008-12-31  FHZN.SW              CHF  None  2008-12-31   2008-12-31
14  2007-12-31  FHZN.SW              CHF  None  2007-12-31   2007-12-31
15  2006-12-31  FHZN.SW              CHF  None  2006-12-31   2006-12-31
16  2005-12-31  FHZN.SW              CHF  None  2005-12-31   2005-12-31

   calendarYear period     revenue  costOfRevenue  ...  incomeBeforeTaxRatio  \
0          2021     FY   680000000    471500000.0  ...             -0.020147
1          2020     FY   623974000    455241000.0  ...             -0.135393
2          2019     FY  1210084000    597898000.0  ...              0.319447
3          2018     FY  1152897000    555691000.0  ...              0.259463
4          2017     FY  1037125000    503493000.0  ...              0.342077
5          2016     FY  1012804000    491290000.0  ...              0.310618
6          2015     FY   988973000    459418000.0  ...              0.235901
7          2014     FY   963479000    472832000.0  ...              0.269261
8          2013     FY   975094000    474596000.0  ...              0.174909
9          2012     FY   948820000    578549000.0  ...              0.123699
10         2011     FY   905404000     63288000.0  ...              0.233857
11         2010     FY   862991000            0.0  ...              0.201798
12         2009     FY   820207000     40697000.0  ...              0.291387
13         2008     FY   855103000     43907000.0  ...              0.172199
14         2007     FY   802868000            0.0  ...              0.206107
15         2006     FY   737109000            0.0  ...              0.148232
16         2005     FY   702229000            0.0  ...              0.107446

    incomeTaxExpense  netIncome  netIncomeRatio        eps  epsdiluted  \
0         -3600000.0  -10100000       -0.014853  -0.329013   -0.329013
1        -15363000.0  -69133000       -0.110795  -2.250000   -2.250000
2         77413000.0  309135000        0.255466  10.070000   10.070000
3         61293000.0  237832000        0.206291   7.750000    7.750000
4         69250000.0  285225000        0.275015   9.290000    9.290000
5         66577000.0  247728000        0.244596   8.070000    8.070000
6         53493000.0  179643000        0.181646   5.852000    5.852000
7         53506000.0  205801000        0.213602   6.706000    6.704000
8         33501000.0  137084000        0.140585   4.468000    4.466000
9         22636000.0   94732000        0.099842   3.104000    3.102000
10        40825000.0  170910000        0.188767   5.568000    5.564000
11        35631000.0  138519000        0.160510   4.514000    4.512000
12        48388000.0  190610000        0.232393   6.240000    6.236000
13        25934000.0  121314000        0.141871   3.956000    3.954000
14        34802000.0  130675000        0.162760   4.260000    4.256000
15        21815000.0   87448000        0.118636   3.070000    3.068000
16        16329000.0   59123000        0.084193   2.400128    2.396154

    weightedAverageShsOut  weightedAverageShsOutDil  \
0                30697891                  30697891
1                30697891                  30702501
2                30690962                  30698770
3                30691512                  30700385
4                30698833                  30705879
5                30697277                  30705563
6                30694025                  30702740
7                30689425                  30700325
8                30683275                  30695670
9                30528430                  30545515
10               30695280                  30714160
11               30684710                  30700325
12               30543570                  30568410
13               30661985                  30686390
14               30680315                  30710465
15               28479885                  28497555
16               24637094                  24675235

                                                 link  \
0   https://www.six-group.com/en/products-services...
1   https://www.six-group.com/en/products-services...
2   https://www.six-group.com/en/products-services...
3   https://www.six-group.com/en/products-services...
4   https://www.six-group.com/en/products-services...
5   https://www.six-group.com/en/products-services...
6   https://www.six-group.com/en/products-services...
7   https://www.six-group.com/en/products-services...
8   https://www.six-group.com/en/products-services...
9   https://www.six-group.com/en/products-services...
10  https://www.six-group.com/en/products-services...
11  https://www.six-group.com/en/products-services...
12  https://www.six-group.com/en/products-services...
13  https://www.six-group.com/en/products-services...
14  https://www.six-group.com/en/products-services...
15  https://www.six-group.com/en/products-services...
16  https://www.six-group.com/en/products-services...

                                            finalLink
0   https://www.six-group.com/en/products-services...
1   https://www.six-group.com/en/products-services...
2   https://www.six-group.com/en/products-services...
3   https://www.six-group.com/en/products-services...
4   https://www.six-group.com/en/products-services...
5   https://www.six-group.com/en/products-services...
6   https://www.six-group.com/en/products-services...
7   https://www.six-group.com/en/products-services...
8   https://www.six-group.com/en/products-services...
9   https://www.six-group.com/en/products-services...
10  https://www.six-group.com/en/products-services...
11  https://www.six-group.com/en/products-services...
12  https://www.six-group.com/en/products-services...
13  https://www.six-group.com/en/products-services...
14  https://www.six-group.com/en/products-services...
15  https://www.six-group.com/en/products-services...
16  https://www.six-group.com/en/products-services...

[17 rows x 38 columns]

In [55]:
for url in url_bs_list : 
    nation_example = extractor(url)
    print(nation_example.columns)

Index(['date', 'symbol', 'reportedCurrency', 'cik', 'fillingDate',
       'acceptedDate', 'calendarYear', 'period', 'cashAndCashEquivalents',
       'shortTermInvestments', 'cashAndShortTermInvestments', 'netReceivables',
       'inventory', 'otherCurrentAssets', 'totalCurrentAssets',
       'propertyPlantEquipmentNet', 'goodwill', 'intangibleAssets',
       'goodwillAndIntangibleAssets', 'longTermInvestments', 'taxAssets',
       'otherNonCurrentAssets', 'totalNonCurrentAssets', 'otherAssets',
       'totalAssets', 'accountPayables', 'shortTermDebt', 'taxPayables',
       'deferredRevenue', 'otherCurrentLiabilities', 'totalCurrentLiabilities',
       'longTermDebt', 'deferredRevenueNonCurrent',
       'deferredTaxLiabilitiesNonCurrent', 'otherNonCurrentLiabilities',
       'totalNonCurrentLiabilities', 'otherLiabilities',
       'capitalLeaseObligations', 'totalLiabilities', 'preferredStock',
       'commonStock', 'retainedEarnings',
       'accumulatedOtherComprehensiveIncomeLoss',
       'othertotalStockholdersEquity', 'totalStockholdersEquity',
       'totalLiabilitiesAndStockholdersEquity', 'minorityInterest',
       'totalEquity', 'totalLiabilitiesAndTotalEquity', 'totalInvestments',
       'totalDebt', 'netDebt', 'link', 'finalLink'],
      dtype='object')
Index(['date', 'symbol', 'reportedCurrency', 'cik', 'fillingDate',
       'acceptedDate', 'calendarYear', 'period', 'cashAndCashEquivalents',
       'shortTermInvestments', 'cashAndShortTermInvestments', 'netReceivables',
       'inventory', 'otherCurrentAssets', 'totalCurrentAssets',
       'propertyPlantEquipmentNet', 'goodwill', 'intangibleAssets',
       'goodwillAndIntangibleAssets', 'longTermInvestments', 'taxAssets',
       'otherNonCurrentAssets', 'totalNonCurrentAssets', 'otherAssets',
       'totalAssets', 'accountPayables', 'shortTermDebt', 'taxPayables',
       'deferredRevenue', 'otherCurrentLiabilities', 'totalCurrentLiabilities',
       'longTermDebt', 'deferredRevenueNonCurrent',
       'deferredTaxLiabilitiesNonCurrent', 'otherNonCurrentLiabilities',
       'totalNonCurrentLiabilities', 'otherLiabilities',
       'capitalLeaseObligations', 'totalLiabilities', 'preferredStock',
       'commonStock', 'retainedEarnings',
       'accumulatedOtherComprehensiveIncomeLoss',
       'othertotalStockholdersEquity', 'totalStockholdersEquity',
       'totalLiabilitiesAndStockholdersEquity', 'minorityInterest',
       'totalEquity', 'totalLiabilitiesAndTotalEquity', 'totalInvestments',
       'totalDebt', 'netDebt', 'link', 'finalLink'],
      dtype='object')
Index(['date', 'symbol', 'reportedCurrency', 'cik', 'fillingDate',
       'acceptedDate', 'calendarYear', 'period', 'cashAndCashEquivalents',
       'shortTermInvestments', 'cashAndShortTermInvestments', 'netReceivables',
       'inventory', 'otherCurrentAssets', 'totalCurrentAssets',
       'propertyPlantEquipmentNet', 'goodwill', 'intangibleAssets',
       'goodwillAndIntangibleAssets', 'longTermInvestments', 'taxAssets',
       'otherNonCurrentAssets', 'totalNonCurrentAssets', 'otherAssets',
       'totalAssets', 'accountPayables', 'shortTermDebt', 'taxPayables',
       'deferredRevenue', 'otherCurrentLiabilities', 'totalCurrentLiabilities',
       'longTermDebt', 'deferredRevenueNonCurrent',
       'deferredTaxLiabilitiesNonCurrent', 'otherNonCurrentLiabilities',
       'totalNonCurrentLiabilities', 'otherLiabilities',
       'capitalLeaseObligations', 'totalLiabilities', 'preferredStock',
       'commonStock', 'retainedEarnings',
       'accumulatedOtherComprehensiveIncomeLoss',
       'othertotalStockholdersEquity', 'totalStockholdersEquity',
       'totalLiabilitiesAndStockholdersEquity', 'minorityInterest',
       'totalEquity', 'totalLiabilitiesAndTotalEquity', 'totalInvestments',
       'totalDebt', 'netDebt', 'link', 'finalLink'],
      dtype='object')
Index(['date', 'symbol', 'reportedCurrency', 'cik', 'fillingDate',
       'acceptedDate', 'calendarYear', 'period', 'cashAndCashEquivalents',
       'shortTermInvestments', 'cashAndShortTermInvestments', 'netReceivables',
       'inventory', 'otherCurrentAssets', 'totalCurrentAssets',
       'propertyPlantEquipmentNet', 'goodwill', 'intangibleAssets',
       'goodwillAndIntangibleAssets', 'longTermInvestments', 'taxAssets',
       'otherNonCurrentAssets', 'totalNonCurrentAssets', 'otherAssets',
       'totalAssets', 'accountPayables', 'shortTermDebt', 'taxPayables',
       'deferredRevenue', 'otherCurrentLiabilities', 'totalCurrentLiabilities',
       'longTermDebt', 'deferredRevenueNonCurrent',
       'deferredTaxLiabilitiesNonCurrent', 'otherNonCurrentLiabilities',
       'totalNonCurrentLiabilities', 'otherLiabilities',
       'capitalLeaseObligations', 'totalLiabilities', 'preferredStock',
       'commonStock', 'retainedEarnings',
       'accumulatedOtherComprehensiveIncomeLoss',
       'othertotalStockholdersEquity', 'totalStockholdersEquity',
       'totalLiabilitiesAndStockholdersEquity', 'minorityInterest',
       'totalEquity', 'totalLiabilitiesAndTotalEquity', 'totalInvestments',
       'totalDebt', 'netDebt', 'link', 'finalLink'],
      dtype='object')
Index(['date', 'symbol', 'reportedCurrency', 'cik', 'fillingDate',
       'acceptedDate', 'calendarYear', 'period', 'cashAndCashEquivalents',
       'shortTermInvestments', 'cashAndShortTermInvestments', 'netReceivables',
       'inventory', 'otherCurrentAssets', 'totalCurrentAssets',
       'propertyPlantEquipmentNet', 'goodwill', 'intangibleAssets',
       'goodwillAndIntangibleAssets', 'longTermInvestments', 'taxAssets',
       'otherNonCurrentAssets', 'totalNonCurrentAssets', 'otherAssets',
       'totalAssets', 'accountPayables', 'shortTermDebt', 'taxPayables',
       'deferredRevenue', 'otherCurrentLiabilities', 'totalCurrentLiabilities',
       'longTermDebt', 'deferredRevenueNonCurrent',
       'deferredTaxLiabilitiesNonCurrent', 'otherNonCurrentLiabilities',
       'totalNonCurrentLiabilities', 'otherLiabilities',
       'capitalLeaseObligations', 'totalLiabilities', 'preferredStock',
       'commonStock', 'retainedEarnings',
       'accumulatedOtherComprehensiveIncomeLoss',
       'othertotalStockholdersEquity', 'totalStockholdersEquity',
       'totalLiabilitiesAndStockholdersEquity', 'minorityInterest',
       'totalEquity', 'totalLiabilitiesAndTotalEquity', 'totalInvestments',
       'totalDebt', 'netDebt', 'link', 'finalLink'],
      dtype='object')
Index(['date', 'symbol', 'reportedCurrency', 'cik', 'fillingDate',
       'acceptedDate', 'calendarYear', 'period', 'cashAndCashEquivalents',
       'shortTermInvestments', 'cashAndShortTermInvestments', 'netReceivables',
       'inventory', 'otherCurrentAssets', 'totalCurrentAssets',
       'propertyPlantEquipmentNet', 'goodwill', 'intangibleAssets',
       'goodwillAndIntangibleAssets', 'longTermInvestments', 'taxAssets',
       'otherNonCurrentAssets', 'totalNonCurrentAssets', 'otherAssets',
       'totalAssets', 'accountPayables', 'shortTermDebt', 'taxPayables',
       'deferredRevenue', 'otherCurrentLiabilities', 'totalCurrentLiabilities',
       'longTermDebt', 'deferredRevenueNonCurrent',
       'deferredTaxLiabilitiesNonCurrent', 'otherNonCurrentLiabilities',
       'totalNonCurrentLiabilities', 'otherLiabilities',
       'capitalLeaseObligations', 'totalLiabilities', 'preferredStock',
       'commonStock', 'retainedEarnings',
       'accumulatedOtherComprehensiveIncomeLoss',
       'othertotalStockholdersEquity', 'totalStockholdersEquity',
       'totalLiabilitiesAndStockholdersEquity', 'minorityInterest',
       'totalEquity', 'totalLiabilitiesAndTotalEquity', 'totalInvestments',
       'totalDebt', 'netDebt', 'link', 'finalLink'],
      dtype='object')
Index(['date', 'symbol', 'reportedCurrency', 'cik', 'fillingDate',
       'acceptedDate', 'calendarYear', 'period', 'cashAndCashEquivalents',
       'shortTermInvestments', 'cashAndShortTermInvestments', 'netReceivables',
       'inventory', 'otherCurrentAssets', 'totalCurrentAssets',
       'propertyPlantEquipmentNet', 'goodwill', 'intangibleAssets',
       'goodwillAndIntangibleAssets', 'longTermInvestments', 'taxAssets',
       'otherNonCurrentAssets', 'totalNonCurrentAssets', 'otherAssets',
       'totalAssets', 'accountPayables', 'shortTermDebt', 'taxPayables',
       'deferredRevenue', 'otherCurrentLiabilities', 'totalCurrentLiabilities',
       'longTermDebt', 'deferredRevenueNonCurrent',
       'deferredTaxLiabilitiesNonCurrent', 'otherNonCurrentLiabilities',
       'totalNonCurrentLiabilities', 'otherLiabilities',
       'capitalLeaseObligations', 'totalLiabilities', 'preferredStock',
       'commonStock', 'retainedEarnings',
       'accumulatedOtherComprehensiveIncomeLoss',
       'othertotalStockholdersEquity', 'totalStockholdersEquity',
       'totalLiabilitiesAndStockholdersEquity', 'minorityInterest',
       'totalEquity', 'totalLiabilitiesAndTotalEquity', 'totalInvestments',
       'totalDebt', 'netDebt', 'link', 'finalLink'],
      dtype='object')

Index(['date', 'symbol', 'reportedCurrency', 'cik', 'fillingDate',
       'acceptedDate', 'calendarYear', 'period', 'cashAndCashEquivalents',
       'shortTermInvestments', 'cashAndShortTermInvestments', 'netReceivables',
       'inventory', 'otherCurrentAssets', 'totalCurrentAssets',
       'propertyPlantEquipmentNet', 'goodwill', 'intangibleAssets',
       'goodwillAndIntangibleAssets', 'longTermInvestments', 'taxAssets',
       'otherNonCurrentAssets', 'totalNonCurrentAssets', 'otherAssets',
       'totalAssets', 'accountPayables', 'shortTermDebt', 'taxPayables',
       'deferredRevenue', 'otherCurrentLiabilities', 'totalCurrentLiabilities',
       'longTermDebt', 'deferredRevenueNonCurrent',
       'deferredTaxLiabilitiesNonCurrent', 'otherNonCurrentLiabilities',
       'totalNonCurrentLiabilities', 'otherLiabilities',
       'capitalLeaseObligations', 'totalLiabilities', 'preferredStock',
       'commonStock', 'retainedEarnings',
       'accumulatedOtherComprehensiveIncomeLoss',
       'othertotalStockholdersEquity', 'totalStockholdersEquity',
       'totalLiabilitiesAndStockholdersEquity', 'minorityInterest',
       'totalEquity', 'totalLiabilitiesAndTotalEquity', 'totalInvestments',
       'totalDebt', 'netDebt', 'link', 'finalLink'],
      dtype='object')

In [65]:
pd.DataFrame(nation_example.columns)

                                           0
0                                       date
1                                     symbol
2                           reportedCurrency
3                                        cik
4                                fillingDate
5                               acceptedDate
6                               calendarYear
7                                     period
8                                  netIncome
9                depreciationAndAmortization
10                         deferredIncomeTax
11                    stockBasedCompensation
12                    changeInWorkingCapital
13                       accountsReceivables
14                                 inventory
15                          accountsPayables
16                       otherWorkingCapital
17                         otherNonCashItems
18      netCashProvidedByOperatingActivities
19    investmentsInPropertyPlantAndEquipment
20                           acquisitionsNet
21                    purchasesOfInvestments
22              salesMaturitiesOfInvestments
23                   otherInvestingActivites
24          netCashUsedForInvestingActivites
25                             debtRepayment
26                         commonStockIssued
27                    commonStockRepurchased
28                             dividendsPaid
29                   otherFinancingActivites
30  netCashUsedProvidedByFinancingActivities
31                effectOfForexChangesOnCash
32                           netChangeInCash
33                         cashAtEndOfPeriod
34                   cashAtBeginningOfPeriod
35                         operatingCashFlow
36                        capitalExpenditure
37                              freeCashFlow
38                                      link
39                                 finalLink

json.load와 json.loads는 다르다.  
* json.loads는 json 파일 형태가 아니라 string 형태의 객체에서 json 형식 내용을 추출할 때 사용한다.  
* json.load는 json 파일을 통째로 들고오는 방법이다. with open( ) as json file : json = json.load(json file)   이런 식으로  
json은 key와 value를 가진 map 구조. json.load는 dict자료구조로 인식되고

참고하면 좋은 사이트 : 
    https://medium.com/swlh/looking-for-a-financial-data-api-look-no-further-than-financial-modeling-prep-972d33b1cb08