이 노트북은 https://bright-ocean.tistory.com/79 블로그의 코드를 조금더 stable하게 수정한 것입니다.   
최초 작성일 : 2022년 4월 14일, 임낙준

인베스팅 닷컴의 크롤링방법을 설명하기 위해서, 먼저 해당 문서는 각 부분별로 설명을 하고

# 1. 필요한 모듈 가져오기

In [1]:
import pandas as pd
import numpy as np
import requests
import re
from bs4 import BeautifulSoup
import time
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

# 2. 국가별 주식 종목 긁어오기

이번 2022년 헤브론스타가 인베스팅닷컴에서 갖고와야할 국가들은 아래와 같습니다. 
* 말레이시아  
* 싱가포르  
* 콜롬비아  
* 멕시코  
* 스페인  
* 이탈리아  
한 국가를 기준으로 잡고 코드를 작성하면, 코드를 국가별로 재활용 할 수 있기 때문에, 먼저 멕시코를 기준으로 코드를 작성하겠습니다.  
또한 인베스팅 닷컴은 한국어페이지도 존재하지만, 인베스팅 닷컴에서 영어표기를 우선한다고 명시해 놓았기에, 영어권 국가 사이트(예시에서는 호주)로 접속해서 멕시코의 상장사 재무정보에 접근합니다.

### 2-1. 주식시장 페이지 접속

아래 코드의 first_url 링크 맨 뒤에있는 'mexico'를 바꾸면 다른 국가에서도 재활용 할 수 있음

In [2]:
# 멕시코 주식시장 정보 페이지 접속
driver = webdriver.Chrome('./chromedriver.exe')
first_url = 'https://investing.com/equities/mexico'    #맨 뒤에 'mexico'를 바꾸면 다른 국가에서도 재활용 할 수 있음
driver.get(first_url)

### 2-2. 주식시장 페이지에서 모든 주식 종목소개 페이지로 전환

멕시코 주식 시장 페이지에 접근한 후, 페이지에 표시되는 주식을 'all stocks' 즉 모든 상장 주식으로 바꿉니다.    
이 때, 인베스팅 닷컴의 팝업 광고창 때문에 오류가 발생하는 경우가 있으니 try, except로 오류를 회피합니다.    
except에서는 광고 팝업창의 x버튼을 누르는 코드가 추가되었습니다.

In [3]:
#페이지에 표시되는 주식을 'all stocks'로 바꿈 
try : 
    select_box = driver.find_element_by_xpath('//*[@id="stocksFilter"]').click()
    select_all_stock = driver.find_element_by_xpath('//*[@id="all"]').click()
    #time.sleep(8)

# Avoid error. 만약 광고 팝업창으로 인해 에러가 발생할 경우 except로 에러 회피
except : 
    # 광고 팝업창 닫기 
    driver.find_element_by_xpath('//*[@id="PromoteSignUpPopUp"]/div[2]/i').click()
    # try와 동일
    select_box = driver.find_element_by_xpath('//*[@id="stocksFilter"]').click()
    select_all_stock = driver.find_element_by_xpath('//*[@id="all"]').click()
    #time.sleep(8)

### 2-3. 모든 주식 종목 소개 페이지에서 각 종목(기업)별 상세 정보 페이지 링크 추출

인베스팅 닷컴은 동적 페이지입니다. 모든 주식 종목 코드를 긁어 올 수 있도록, 스크롤을 끝까지 내렸다가 다시 올립니다.

In [4]:
# 인베스팅 닷컴은 동적페이지이다. 
# BeautifulSoup을 사용할수 있도록 스크롤을 한번 끝까지 내렸다 올린다.
SCROLL_PAUSE_SEC = 3

# 스크롤 높이 가져옴
last_height = driver.execute_script("return document.body.scrollHeight")

while True:
    # 끝까지 스크롤 다운
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

    # 1초 대기
    time.sleep(SCROLL_PAUSE_SEC)

    # 스크롤 다운 후 스크롤 높이 다시 가져옴
    new_height = driver.execute_script("return document.body.scrollHeight")
    if new_height == last_height:
        break
    last_height = new_height

주식 종목 표를 Beautifulsoup을 이용해 갖고 옵니다. 이후 상세 정보 페이지의 링크를 추출하여, company_links란 리스트에 저장합니다.

In [6]:
soup = BeautifulSoup(driver.page_source,"html.parser")

# 주식 테이블을 가지고 온다. 
maintable = soup.find('table', id='cross_rate_markets_stocks_1')

# 메인 주식 테이블에서 회사 페이지로
all_atag_maintable = maintable.find_all('a')

# soup의 find 메서드를 이용해서 갖고 오게 되면, 링크 뿐 아니라 다른 정보들도 같이 갖고 오게 됩니다. 
# 따라서 아래 for문으로 순수한 href 링크만을 추출하여, company_links에 저장합니다. 
company_links = []
for a in all_atag_maintable:
    company_link = a.attrs["href"] #find로 한번더 돌려준다.
    company_links.append(company_link)

In [7]:
len(company_links)

656

# 3. 기업 일반정보 추출

In [8]:
# 예시를 위해 company_links에서 기업 하나를 갖고 옴 
company = company_links[0]

In [12]:
base_url = 'https://au.investing.com'
PROFILE_suffix = '-company-profile'
IS_suffix = '-income-statement'
BS_suffix = '-balance-sheet'
CF_suffix = '-cash-flow'

In [13]:
#company profile page
driver.get(base_url+company+PROFILE_suffix)
time.sleep(1)

In [11]:
#  description : 기업 설명
soup = BeautifulSoup(driver.page_source, "html.parser")
desciption_info = soup.find('div', attrs = {'class' : 'companyProfileBody'}).text
desciption_info = desciption_info.replace('\n','')

In [12]:
profile_header = soup.find('div', attrs = {'class' : 'companyProfileHeader'}).text

# 정규표현식으로 Industry, Sector
industry_info =  re.search(r'Industry\w+[\s]?\w+', profile_header).group()
sector_info = re.search(r'Sector\w+[\s]?\w+', profile_header).group()

#처음에 발견되는 1개만 삭제
industry_info = industry_info.replace('Industry', '', 1)
sector_info = sector_info.replace('Sector', '', 1)

# contact info 
address_info = soup.find('div', attrs = {'class' : 'companyAddress'}).text
phone_info = soup.find('div', attrs = {'class' : 'companyPhone'}).text
fax_info = soup.find('div', attrs = {'class' : 'companyFax'}).text
webpage_info = soup.find('div', attrs = {'class' : 'companyWeb'}).text

# 정규표현식으로 특수문자 제거 
phone_info = phone_info.replace('\n','')
phone_info = phone_info.replace('Phone','')
fax_info = fax_info.replace('\n','')
fax_info = fax_info.replace('Fax','')
webpage_info = webpage_info.replace('\n','')
webpage_info = webpage_info.replace('Web','')

# 3. 기업 재무정보 추출

### 3-1. 재무정보 페이지 링크  생성  
앞서 company_links에 기업별 상세 정보 페이지 링크를 추출하였습니다. 기업별 상세 정보 페이지 링크에 쿼리스트링처럼, 적절한 인자를 연결하면 재무정보에 접근할 수 있습니다.  

ex) America Movil이라는 멕시코 기업 :  
base url 뒤에 America Movil의 상세페이지로 넘어가는 company link를 붙이고, 손익계산서를 의미하는 -income-statement를 추가하게 되면 America Movil의 손익계산서 페이지로 넘어가게 됩니다.  

'https://au.investing.com/'  (baseurl) + 'equities/america-movil-l' (company link : Mmerica movil 상세정보페이지) + '-income-statement'   
=  https://au.investing.com/equities/america-movil-l-income-statement

손익계산서, 재무상태표(대차대조표), 현금흐름표에 해당하는 접미사들은 아래 코드와 같습니다.   
base_url + company_link + 원하는 표의 suffix   로 http 링크를 만들어 이동합니다.

In [13]:
base_url = 'https://au.investing.com'
IS_suffix = '-income-statement'
BS_suffix = '-balance-sheet'
CF_suffix = '-cash-flow'

### 3-2. 추출하고자 하는 계정과목(칼럼) 설정
인베스팅 닷컴에서 확인할 수 있는 계정과목들은 많습니다. 2022년 BDC과제에서 작성한 테이블 명세서에 근거하여 추출하고자 하는 계정과목이름들을 리스트에 저장합니다. 해당 리스트들은 3-3에서 사용됩니다.

In [14]:
# 추출하고자 하는 칼럼들 

is_targets =['Total Revenue','Cost of Revenue, Total','Selling/General/Admin. Expenses, Total','Operating Income',
             'Interest Income (Expense), Net Non-Operating', 'Interest Expense (Income) - Net Operating',
            'Net Income Before Taxes','Net Income After Taxes']

bs_targets = ['Total Current Assets','Total Assets','Total Current Liabilities','Total Liabilities','Total Equity']

cf_targets = ['Cash From Operating Activities','Cash From Financing Activities','Cash From Investing Activities']

### 3-3. 정보 추출
크롤링의 핵심이 되는 내용입니다. 손익계산서, 대차대조표, 현금흐름표의 데이터를 추출하고 전처리 하는 과정이 모두 같기 때문에 손익계산서 추출 코드를 설명한 후, 마지막 part4에서 이를 다른 재무제표에 대해서도 적용해보겠습니다.

In [15]:
company

'/equities/america-movil-l'

In [52]:
# 예시를 위해 company_links에서 기업 하나를 갖고 옴 
company = company_links[0]

3-1에서 설명한대로 base_url+company+IS_suffix 로 손익계산서 페이지에 접근하는 링크를 만들고, 브라우저를 손익계산서 페이지로 이동시킵니다.

In [53]:
#income statement 
driver.get(base_url+company+IS_suffix)
time.sleep(1)

연간 재무제표를 추출해 올 것이기 때문에, Annual 버튼을 클릭합니다.

In [54]:
# 'Annual', 'Quaterly' 버튼 중 'Annual' Click
driver.find_element_by_xpath('//*[@id="leftColumn"]/div[8]/div[1]/a[1]').click()
#//*[@id="leftColumn"]/div[8]/div[1]/a[1]

pd.read_html은 html 소스코드에서 table 속성에 해당하는 값을 가져오는 함수입니다. 
pd.read_html을 이용하여 웹페이지에 있는 표를 갖고 온 후, df_income 데이터프레임을 생성합니다.

In [55]:
df_income = pd.read_html(driver.page_source)[0].dropna()
df_income

,Period Ending:,202131/12,202031/12,201931/12,201831/12
0,Total Revenue,25900.66,24203.17,24583.31,23885.78
1,Revenue 25900.66 24203.17 24583.31 23885.78 O...,Revenue 25900.66 24203.17 24583.31 23885.78 O...,Revenue 25900.66 24203.17 24583.31 23885.78 O...,Revenue 25900.66 24203.17 24583.31 23885.78 O...,Revenue 25900.66 24203.17 24583.31 23885.78 O...
2,Revenue,25900.66,24203.17,24583.31,23885.78
3,"Other Revenue, Total",-,-,-,-
4,"Cost of Revenue, Total",8655.38,7916.39,8231.96,9268.19
5,Gross Profit,17245.28,16286.78,16351.35,14617.59
6,Total Operating Expenses,22082.58,21708.29,20351.19,26270.91
7,"Selling/General/Admin. Expenses, Total 5149.19...","Selling/General/Admin. Expenses, Total 5149.19...","Selling/General/Admin. Expenses, Total 5149.19...","Selling/General/Admin. Expenses, Total 5149.19...","Selling/General/Admin. Expenses, Total 5149.19..."
8,"Selling/General/Admin. Expenses, Total",5149.19,4964.69,5098.58,5682.73
9,Research & Development,-,-,-,-
10,Depreciation / Amortization,7576.01,8103.74,6950.35,7172.27
11,Interest Expense (Income) - Net Operating,-58.24,196.08,-5.42,-8.39
12,Unusual Expense (Income),316.88,-226.16,-477.62,3683.14
13,"Other Operating Expenses, Total",443.37,753.54,553.34,472.97
14,Operating Income,3818.08,2494.88,4232.13,-2385.13
15,"Interest Income (Expense), Net Non-Operating",-1644.46,-1323.77,-1452.39,-1688.01
16,Gain (Loss) on Sale of Assets,-,-,-,-
17,"Other, Net",-,-,-,-
18,Net Income Before Taxes,2173.62,1171.12,2779.74,-4073.14
19,Provision for Income Taxes,896.74,547.07,964.64,901.55
20,Net Income After Taxes,1276.88,624.04,1815.1,-4974.69
21,Minority Interest,-457.98,-258.89,-357.55,212.67
22,Equity In Affiliates,-,-,-,-
23,U.S GAAP Adjustment,-,-,-,-
24,Net Income Before Extraordinary Items,818.9,365.15,1457.55,-4762.02
25,Total Extraordinary Items,-,-,-,-
26,Net Income,818.9,365.15,1457.55,-4762.02
27,Total Adjustments to Net Income,-,-,-,-
28,Income Available to Common Excluding Extraordi...,818.9,365.15,1457.55,-4762.02
29,Dilution Adjustment,-,-,-,-
30,Diluted Net Income,818.9,365.15,1457.55,-4762.02
31,Diluted Weighted Average Shares,9180.32,9175.72,9120.71,9058.64
32,Diluted EPS Excluding Extraordinary Items,0.09,0.04,0.16,-0.53
33,DPS - Common Stock Primary Issue,0.1,0.07,0.09,0.1
34,Diluted Normalized EPS,0.11,0.03,0.13,-0.26

df_income 데이터프레임에 회사이름, 재무제표에서 사용한 통화 단위도 추가합니다.

In [56]:
df_income_unit = driver.find_element_by_xpath('//*[@id="leftColumn"]/div[10]').text             
company_name = driver.find_element_by_xpath('//*[@id="leftColumn"]/div[1]/h1').text

### 3-4. 데이터프레임 전처리 
3-3에서 추출한 데이터 프레임을 바로 사용할 수 없습니다. 우리가 원하는 형태로 데이터 프레임을 적절히 전처리 합니다.

In [57]:
# 행렬 전치. Matrix Transpose
df_income = df_income.T
df_income.head()

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
Period Ending:,Total Revenue,Revenue 25900.66 24203.17 24583.31 23885.78 O...,Revenue,"Other Revenue, Total","Cost of Revenue, Total",Gross Profit,Total Operating Expenses,"Selling/General/Admin. Expenses, Total 5149.19...","Selling/General/Admin. Expenses, Total",Research & Development,...,Total Extraordinary Items,Net Income,Total Adjustments to Net Income,Income Available to Common Excluding Extraordi...,Dilution Adjustment,Diluted Net Income,Diluted Weighted Average Shares,Diluted EPS Excluding Extraordinary Items,DPS - Common Stock Primary Issue,Diluted Normalized EPS
202131/12,25900.66,Revenue 25900.66 24203.17 24583.31 23885.78 O...,25900.66,-,8655.38,17245.28,22082.58,"Selling/General/Admin. Expenses, Total 5149.19...",5149.19,-,...,-,818.9,-,818.9,-,818.9,9180.32,0.09,0.1,0.11
202031/12,24203.17,Revenue 25900.66 24203.17 24583.31 23885.78 O...,24203.17,-,7916.39,16286.78,21708.29,"Selling/General/Admin. Expenses, Total 5149.19...",4964.69,-,...,-,365.15,-,365.15,-,365.15,9175.72,0.04,0.07,0.03
201931/12,24583.31,Revenue 25900.66 24203.17 24583.31 23885.78 O...,24583.31,-,8231.96,16351.35,20351.19,"Selling/General/Admin. Expenses, Total 5149.19...",5098.58,-,...,-,1457.55,-,1457.55,-,1457.55,9120.71,0.16,0.09,0.13
201831/12,23885.78,Revenue 25900.66 24203.17 24583.31 23885.78 O...,23885.78,-,9268.19,14617.59,26270.91,"Selling/General/Admin. Expenses, Total 5149.19...",5682.73,-,...,-,-4762.02,-,-4762.02,-,-4762.02,9058.64,-0.53,0.1,-0.26

In [58]:
# 계정과목을 column 이름으로 설정
df_income = df_income.rename(columns = df_income.iloc[0])
# 0번째 row를 삭제하고 나머지만 남긴다.
df_income = df_income.iloc[1:, :]
df_income.head()

,Total Revenue,"Revenue 25900.66 24203.17 24583.31 23885.78 Other Revenue, Total - - - -",Revenue,"Other Revenue, Total","Cost of Revenue, Total",Gross Profit,Total Operating Expenses,"Selling/General/Admin. Expenses, Total 5149.19 4964.69 5098.58 5682.73 Research & Development - - - - Depreciation / Amortization 7576.01 8103.74 6950.35 7172.27 Interest Expense (Income) - Net Operating -58.24 196.08 -5.42 -8.39 Unusual Expense (Income) 316.88 -226.16 -477.62 3683.14 Other Operating Expenses, Total 443.37 753.54 553.34 472.97","Selling/General/Admin. Expenses, Total",Research & Development,...,Total Extraordinary Items,Net Income,Total Adjustments to Net Income,Income Available to Common Excluding Extraordinary Items,Dilution Adjustment,Diluted Net Income,Diluted Weighted Average Shares,Diluted EPS Excluding Extraordinary Items,DPS - Common Stock Primary Issue,Diluted Normalized EPS
202131/12,25900.66,Revenue 25900.66 24203.17 24583.31 23885.78 O...,25900.66,-,8655.38,17245.28,22082.58,"Selling/General/Admin. Expenses, Total 5149.19...",5149.19,-,...,-,818.9,-,818.9,-,818.9,9180.32,0.09,0.1,0.11
202031/12,24203.17,Revenue 25900.66 24203.17 24583.31 23885.78 O...,24203.17,-,7916.39,16286.78,21708.29,"Selling/General/Admin. Expenses, Total 5149.19...",4964.69,-,...,-,365.15,-,365.15,-,365.15,9175.72,0.04,0.07,0.03
201931/12,24583.31,Revenue 25900.66 24203.17 24583.31 23885.78 O...,24583.31,-,8231.96,16351.35,20351.19,"Selling/General/Admin. Expenses, Total 5149.19...",5098.58,-,...,-,1457.55,-,1457.55,-,1457.55,9120.71,0.16,0.09,0.13
201831/12,23885.78,Revenue 25900.66 24203.17 24583.31 23885.78 O...,23885.78,-,9268.19,14617.59,26270.91,"Selling/General/Admin. Expenses, Total 5149.19...",5682.73,-,...,-,-4762.02,-,-4762.02,-,-4762.02,9058.64,-0.53,0.1,-0.26

3-2에서 만든 추출하고자 하는 데이터 컬럼명들로 df_income에서 필요한 열들만 뽑아냅니다. 여기까지 오면 필요한 정보들이 다 추가된 것 같습니다.

In [22]:
df_income = df_income[is_targets]
df_income

,Total Revenue,"Cost of Revenue, Total","Selling/General/Admin. Expenses, Total",Operating Income,"Interest Income (Expense), Net Non-Operating",Interest Expense (Income) - Net Operating,Net Income Before Taxes,Net Income After Taxes
202131/12,25900.66,8655.38,5149.19,3818.08,-1644.46,-58.24,2173.62,1276.88
202031/12,24203.17,7916.39,4964.69,2494.88,-1323.77,196.08,1171.12,624.04
201931/12,24583.31,8231.96,5098.58,4232.13,-1452.39,-5.42,2779.74,1815.1
201831/12,23885.78,9268.19,5682.73,-2385.13,-1688.01,-8.39,-4073.14,-4974.69

마지막으로, 데이터 프레임에 회계연도, 회사명, 통화단위 칼럼을 추가합니다.

In [23]:
df_income['df_income_unit'] = df_income_unit                 # 데이터프레임에 income statement 통화단위 삽입
df_income['time']= df_income.index                           # 데이터프레임에 '시간' 추가
df_income['company_name'] = company_name                     # 데이터 프레임에 회사 이름 삽입
df_income=df_income.reset_index(drop=True)                  # index 초기화

In [ ]:
df_income.to_excel('test.xlsx')

# 4. 전과정 자동화, 최종 완성코드

Part 1,2,3에서 설명했던 것을 for문을 이용해서 자동화 합니다.

In [13]:
import pandas as pd
import numpy as np
import requests
import re
from bs4 import BeautifulSoup
import time
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import datetime
from tqdm import tqdm

'first_url' 맨 뒤의 'mexico'를 바꾸면 다른 국가에서도 재활용 할 수 있음

In [23]:
# 멕시코 주식시장 정보 페이지 접속
driver = webdriver.Chrome('./chromedriver.exe')
first_url = 'https://au.investing.com/equities/mexico'    #맨 뒤에 'mexico'를 바꾸면 다른 국가에서도 재활용 할 수 있음
driver.get(first_url)

In [24]:
#페이지에 표시되는 주식을 'all stocks'로 바꿈 
try : 
    select_box = driver.find_element_by_xpath('//*[@id="stocksFilter"]').click()
    select_all_stock = driver.find_element_by_xpath('//*[@id="all"]').click()
    #time.sleep(8)

# Avoid error. 만약 광고 팝업창으로 인해 에러가 발생할 경우 except로 에러 회피
except : 
    # 광고 팝업창 닫기 
    driver.find_element_by_xpath('//*[@id="PromoteSignUpPopUp"]/div[2]/i').click()
    # try와 동일
    select_box = driver.find_element_by_xpath('//*[@id="stocksFilter"]').click()
    select_all_stock = driver.find_element_by_xpath('//*[@id="all"]').click()
    #time.sleep(20)

In [28]:
# 인베스팅 닷컴은 동적페이지이다. 
# BeautifulSoup을 사용할수 있도록 스크롤을 한번 끝까지 내렸다 올린다.
SCROLL_PAUSE_SEC = 3

# 스크롤 높이 가져옴
last_height = driver.execute_script("return document.body.scrollHeight")

while True:
    # 끝까지 스크롤 다운
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

    # 1초 대기
    time.sleep(SCROLL_PAUSE_SEC)

    # 스크롤 다운 후 스크롤 높이 다시 가져옴
    new_height = driver.execute_script("return document.body.scrollHeight")
    if new_height == last_height:
        break
    last_height = new_height

In [29]:
soup = BeautifulSoup(driver.page_source,"html.parser")

# 주식 테이블을 가지고 온다. 
maintable = soup.find('table', id='cross_rate_markets_stocks_1')

# 메인 주식 테이블에서 회사 페이지로
all_atag_maintable = maintable.find_all('a')

# soup의 find 메서드를 이용해서 갖고 오게 되면, 링크 뿐 아니라 다른 정보들도 같이 갖고 오게 됩니다. 
# 따라서 아래 for문으로 순수한 href 링크만을 추출하여, company_links에 저장합니다. 
company_links = []
for a in all_atag_maintable:
    company_link = a.attrs["href"] #find로 한번더 돌려준다.
    company_links.append(company_link)

In [30]:
base_url = 'https://au.investing.com'
PROFILE_suffix = '-company-profile'
IS_suffix = '-income-statement'
BS_suffix = '-balance-sheet'
CF_suffix = '-cash-flow'

In [36]:
# 인베스팅 닷컴의 계정과목 리스트들. 일반 기업, 은행, 보험업의 계정과목이 달랐다. 
column_listup = pd.read_excel('investingDotcomColumns.xlsx')

all_bs_cols = pd.concat([column_listup['BS'],column_listup['BANK BS'], column_listup['INSURANCE BS']]).dropna()
all_is_cols =  pd.concat([column_listup['IS'],column_listup['BANK IS'], column_listup['INSURANCE IS']]).dropna()
all_cols = pd.concat([column_listup['BS'],column_listup['BANK BS'], column_listup['INSURANCE BS'],column_listup['IS'],column_listup['BANK IS'], column_listup['INSURANCE IS']]).dropna()

# 일반기업, 은행, 보험업의 계정과목들중 겹치는 부분은 제거하여 중복없는 합집합을 사용한다. 
# drop_duplicates는 중복되는 것들중 하나만 제거, 
all_cols = all_cols.drop_duplicates()

In [35]:
# Version 3

wait_time = 1 # time.sleep의 변수 


# 일반기업, 은행, 보험업의 계정과목들중 겹치는 부분은 제거하여 중복없는 합집합을 사용한다. 
# drop_duplicates는 중복되는 것들중 하나만 제거, 그리고 리스트화 
all_cols = list(all_cols.drop_duplicates())
all_cols = all_cols+['is_unit','bs_unit','cf_unit','is_time','bs_time','cf_time','report_type','company_name','industry_info','sector_info',
                     'address_info','phone_info','fax_info','webpage_info','source','gathering_time','PIC']

# all_cols에 기업 이름, 일반정보 등을 추가한다. 

#cross_rate_markets_stocks_1

result_df = pd.DataFrame()
crawling_failed_companies = []
for company in tqdm(company_links) : 
    
    profile_url = base_url+company+PROFILE_suffix
    bs_url = base_url+company+BS_suffix
    is_url = base_url+company+IS_suffix
    cf_url = base_url+company+CF_suffix
    
    try : 
        # company_link를 보면 'cid='라 주소 맨 끝에 붙어져 있는, 링크가 특이한 기업들이 있다. 이런 기업들은 다루 처리를 해주어야 한다. 
        if company.__contains__('cid=') : 
            index = company.find('?')
            profile_url =  base_url+company[:index]+PROFILE_suffix+company[index:]
            bs_url = base_url+company[:index] +BS_suffix+company[index:]
            is_url = base_url+company[:index] +IS_suffix+company[index:]
            cf_url = base_url+company[:index] +CF_suffix+company[index:]

        ############## 기업 일반정보   #########
        #company profile page
        driver.get(profile_url)
        time.sleep(1)
        
        #  description : 기업 설명
        soup = BeautifulSoup(driver.page_source, "html.parser")
        desciption_info = soup.find('div', attrs = {'class' : 'companyProfileBody'}).text
        desciption_info = desciption_info.replace('\n','')
        
        profile_header = soup.find('div', attrs = {'class' : 'companyProfileHeader'}).text

        # Industry, Sector, Equity Type        
        industry_info =  profile_header.split('\n')[1].replace('Industry','')
        sector_info = profile_header.split('\n')[2].replace('Sector','')
    
        # contact info 
        address_info = soup.find('div', attrs = {'class' : 'companyAddress'}).text
        phone_info = soup.find('div', attrs = {'class' : 'companyPhone'}).text
        fax_info = soup.find('div', attrs = {'class' : 'companyFax'}).text
        webpage_info = soup.find('div', attrs = {'class' : 'companyWeb'}).text

        # 특수문자 제거 
        phone_info = phone_info.replace('\n','')
        phone_info = phone_info.replace('Phone','')
        fax_info = fax_info.replace('\n','')
        fax_info = fax_info.replace('Fax','')
        webpage_info = webpage_info.replace('\n','')
        webpage_info = webpage_info.replace('Web','')

        ############## 기업 재무정보   #########    
        # 분기별 Income Statement 
        driver.get(is_url)
        time.sleep(wait_time)

        for order, table in enumerate(pd.read_html(driver.page_source)) : 
            if len(table) > 20 :
                table_num = order
                break

        df_income_Q = pd.read_html(driver.page_source)[table_num].dropna()
        df_is_unit = driver.find_element_by_xpath('//*[@id="leftColumn"]/div[10]').text             # 통화 단위(Unit)
        company_name = driver.find_element_by_xpath('//*[@id="leftColumn"]/div[1]/h1').text             # 회사이름 추출

        # income statement dataframe preprocess
        df_income_Q = df_income_Q.T
        df_income_Q = df_income_Q.rename(columns = df_income_Q.iloc[0])         # 계정과목을 column 이름으로 설정
        df_income_Q = df_income_Q.iloc[1:, :]                                 # 0번째 row를 삭제하고 나머지만 남긴다.

        df_income_Q['is_unit'] = df_is_unit                 # 데이터프레임에 income statement 통화단위 삽입
        df_income_Q['is_time']= df_income_Q.index                  # 데이터프레임에 '시간' 추가
        df_income_Q['report_type'] = 'Quarter'                         # 데이터프레임에 분기보고서임을 표시 
        df_income_Q['company_name'] = company_name                     # 데이터프레임에 회사 이름 삽입
        df_income_Q=df_income_Q.reset_index(drop=True) 

        # 연간 Income Statement. 
        try : 
            driver.find_element_by_xpath('//*[@id="leftColumn"]/div[8]/div[1]/a[1]').click() # Annual 버튼 클릭
            time.sleep(2)
        except : 
            driver.find_element_by_xpath('//*[@id="leftColumn"]/div[9]/div[1]/a[1]').click()
            time.sleep(2)    

        for order, table in enumerate(pd.read_html(driver.page_source)) : 
            if len(table) > 20 :
                table_num = order
                break

        df_income_A = pd.read_html(driver.page_source)[table_num].dropna()

        # income statement dataframe preprocess
        df_income_A = df_income_A.T
        df_income_A = df_income_A.rename(columns = df_income_A.iloc[0])         # 계정과목을 column 이름으로 설정
        df_income_A = df_income_A.iloc[1:, :]                                 # 0번째 row를 삭제하고 나머지만 남긴다.

        df_income_A['is_unit'] = df_is_unit                 # 데이터프레임에 income statement 통화단위 삽입
        df_income_A['is_time']= df_income_A.index                  # 데이터프레임에 '시간' 추가
        df_income_A['report_type'] = 'Annual'                          # 데이터프레임에 분기보고서임을 표시 
        df_income_A['company_name'] = company_name                     # 데이터 프레임에 회사 이름 삽입
        df_income_A=df_income_A.reset_index(drop=True) 


        # balance data
        driver.get(bs_url)
        time.sleep(wait_time)

        for order, table in enumerate(pd.read_html(driver.page_source)) : 
            if len(table) > 20 :
                table_num = order


        # 분기별 balance sheet
        df_balance_Q = pd.read_html(driver.page_source)[table_num].dropna()
        df_bs_unit = driver.find_element_by_xpath('//*[@id="leftColumn"]/div[10]').text           # 통화 단위(Unit) 추출
        time.sleep(wait_time)
        # balance sheet dataframe preprocess
        df_balance_Q = df_balance_Q.T
        df_balance_Q = df_balance_Q.rename(columns = df_balance_Q.iloc[0])     # 계정과목을 column 이름으로 설정
        df_balance_Q = df_balance_Q.iloc[1:, :]                               # 0번째 row를 삭제하고 나머지만 남긴다.
        ##df_balance = df_balance[bs_targets]
        df_balance_Q['bs_unit'] = df_bs_unit                  # 데이터프레임에 cash flow 통화단위 삽입
        df_balance_Q['bs_time']= df_balance_Q.index
        #df_balance_Q['report_type'] = 'Quarter'                         # 데이터프레임에 분기보고서임을 표시 
        #df_balance_Q['company_name'] = company_name                     # 데이터 프레임에 회사 이름 삽입
        df_balance_Q=df_balance_Q.reset_index(drop=True)


        # 연간 balance sheet 
        try : 
            driver.find_element_by_xpath('//*[@id="leftColumn"]/div[8]/div[1]/a[1]').click() # Annual 버튼 클릭
        except :
            driver.find_element_by_xpath('//*[@id="leftColumn"]/div[9]/div[1]/a[1]').click() # Annual 버튼 클릭
        time.sleep(wait_time)

        for order, table in enumerate(pd.read_html(driver.page_source)) : 
            if len(table) > 20 :
                table_num = order
                break

        df_balance_A = pd.read_html(driver.page_source)[table_num].dropna()
        df_bs_unit = driver.find_element_by_xpath('//*[@id="leftColumn"]/div[10]').text           # 통화 단위(Unit) 추출
        time.sleep(wait_time)
        # balance sheet dataframe preprocess
        df_balance_A = df_balance_A.T
        df_balance_A = df_balance_A.rename(columns = df_balance_A.iloc[0])      # 계정과목을 column 이름으로 설정
        df_balance_A = df_balance_A.iloc[1:, :]                               # 0번째 row를 삭제하고 나머지만 남긴다.
        ##df_balance = df_balance[bs_targets]
        df_balance_A['bs_unit'] = df_bs_unit                  # 데이터프레임에 cash flow 통화단위 삽입
        df_balance_A['bs_time']= df_balance_A.index
        #df_balance_A['report_type'] = 'Annual'                          # 데이터프레임에 연간보고서임을 표시 
        #df_balance_A['company_name'] = company_name                     # 데이터 프레임에 회사 이름 삽입
        df_balance_A = df_balance_A.reset_index(drop=True)

        # cash flow
        driver.get(cf_url)
        time.sleep(2)

        for order, table in enumerate(pd.read_html(driver.page_source)) : 
            if len(table) > 20 :
                table_num = order
                break    

        # 분기별 cashflow 
        df_cash_flow_Q = pd.read_html(driver.page_source)[table_num].dropna()
        df_cf_unit = driver.find_element_by_xpath('//*[@id="leftColumn"]/div[10]').text           # 통화 단위(Unit) 추출
        time.sleep(wait_time)

        df_cash_flow_Q = df_cash_flow_Q.T 
        df_cash_flow_Q = df_cash_flow_Q.rename(columns = df_cash_flow_Q.iloc[0]) # 계정과목을 column 이름으로 설정
        df_cash_flow_Q = df_cash_flow_Q.iloc[1:, :]                              # 0번째 row를 삭제하고 나머지만 남긴다.
        df_cash_flow_Q['cf_unit'] = df_cf_unit                     # 데이터프레임에 cash flow 통화단위 삽입
        df_cash_flow_Q['cf_time']= df_cash_flow_Q.index        
        df_cash_flow_Q = df_cash_flow_Q.reset_index(drop=True)

        #연도별 cashflow 
        try : 
            driver.find_element_by_xpath('//*[@id="leftColumn"]/div[8]/div[1]/a[1]').click() # Annual 버튼 클릭
        except :                         
            driver.find_element_by_xpath('//*[@id="leftColumn"]/div[9]/div[1]/a[1]').click() # Annual 버튼 클릭
        time.sleep(wait_time)

        for order, table in enumerate(pd.read_html(driver.page_source)) : 
            if len(table) > 20 :
                table_num = order
                break        

        df_cash_flow_A = pd.read_html(driver.page_source)[table_num].dropna()
        df_cash_flow_unit = driver.find_element_by_xpath('//*[@id="leftColumn"]/div[10]').text            # 통화 단위(Unit) 추출

        #cash flow dataframe preprocess
        df_cash_flow_A = df_cash_flow_A.T 
        df_cash_flow_A = df_cash_flow_A.rename(columns = df_cash_flow_A.iloc[0]) # 계정과목을 column 이름으로 설정
        df_cash_flow_A = df_cash_flow_A.iloc[1:, :]                              # 0번째 row를 삭제하고 나머지만 남긴다.
        df_cash_flow_A['cf_unit'] = df_cf_unit                     # 데이터프레임에 cash flow 통화단위 삽입
        df_cash_flow_A['cf_time']= df_cash_flow_A.index  
        df_cash_flow_A = df_cash_flow_A.reset_index(drop=True) 

        # 일괄적으로 통합 열방향으로.
        company_df_A = pd.concat([df_balance_A, df_income_A, df_cash_flow_A],axis=1)# 데이터프레임에 분기보고서임을 표시 
        company_df_A['industry_info'] = industry_info
        company_df_A['sector_info'] = sector_info
        company_df_A['address_info'] = address_info
        company_df_A['phone_info'] = phone_info
        company_df_A['fax_info'] = fax_info
        company_df_A['webpage_info'] = webpage_info
        company_df_A['source'] = 'https://au.investing.com'+company+IS_suffix
        company_df_A['PIC'] = '임낙준'
        company_df_A['gathering_time'] = datetime.date.today()



        company_df_Q = pd.concat([df_balance_Q, df_income_Q, df_cash_flow_Q],axis=1)# 데이터프레임에 분기보고서임을 표시 
        company_df_Q['industry_info'] = industry_info
        company_df_Q['sector_info'] = sector_info
        company_df_Q['address_info'] = address_info
        company_df_Q['phone_info'] = phone_info
        company_df_Q['fax_info'] = fax_info
        company_df_Q['webpage_info'] = webpage_info
        company_df_Q['source'] = 'https://au.investing.com'+company+IS_suffix
        company_df_Q['PIC'] = '임낙준'
        company_df_Q['gathering_time'] = datetime.date.today()
        


        blank = pd.DataFrame(columns = all_cols)
        for code in blank.columns : 
        # 대응표의 ifrs코드로 필요한 정보를 추출한다. 
            try : 
                blank[code] = company_df_A[code] 
            except : 
                pass  

        result_df = result_df.append(blank)
        blank = pd.DataFrame(columns = all_cols)

        for code in blank.columns : 
        # 대응표의 ifrs코드로 필요한 정보를 추출한다. 
            try : 
                blank[code] = company_df_Q[code] 
            except : 
                pass  


        result_df = result_df.append(blank)
    
    except :
        # 만약 재무정보가 없어 에러가 났을 경우, 일반정보라도 추가한다. 
        ############## 기업 일반정보   #########
        #company profile page
        driver.get(profile_url)
        time.sleep(1)

        #  description : 기업 설명
        soup = BeautifulSoup(driver.page_source, "html.parser")
        try : 
            company_name = soup.find('h2').text.replace('Company Profile',"")
            #  description : 기업 설명
            desciption_info = soup.find('div', attrs = {'class' : 'companyProfileBody'}).text
            desciption_info = desciption_info.replace('\n','')
        except : 
            print(f"profile이 없어서 안되는 기업 {profile_url}")
            print(f"profile이 없어서 안되는 기업 {company}")
            continue
        
        desciption_info = soup.find('div', attrs = {'class' : 'companyProfileBody'}).text
        desciption_info = desciption_info.replace('\n','')

        profile_header = soup.find('div', attrs = {'class' : 'companyProfileHeader'}).text
        
        # Industry, Sector, Equity Type        
        industry_info =  profile_header.split('\n')[1].replace('Industry','')
        sector_info = profile_header.split('\n')[2].replace('Sector','')

        # contact info 
        address_info = soup.find('div', attrs = {'class' : 'companyAddress'}).text
        phone_info = soup.find('div', attrs = {'class' : 'companyPhone'}).text
        fax_info = soup.find('div', attrs = {'class' : 'companyFax'}).text
        webpage_info = soup.find('div', attrs = {'class' : 'companyWeb'}).text
        

        # 정규표현식으로 특수문자 제거 
        phone_info = phone_info.replace('\n','')
        phone_info = phone_info.replace('Phone','')
        fax_info = fax_info.replace('\n','')
        fax_info = fax_info.replace('Fax','')
        webpage_info = webpage_info.replace('\n','')
        webpage_info = webpage_info.replace('Web','')
        
        
        blank = pd.DataFrame(columns = all_cols)
        blank['company_name'] = company_name
        blank['industry_info'] = industry_info
        blank['sector_info'] = sector_info
        blank['address_info'] = address_info
        blank['phone_info'] = phone_info
        blank['fax_info'] = fax_info
        blank['webpage_info'] = webpage_info
        blank['source'] = 'https://au.investing.com'+company+PROFILE_suffix
        blank['PIC'] = '임낙준'
        blank['gathering_time'] = datetime.date.today()
        
        
        for code in blank.columns : 
            # 대응표의 ifrs코드로 필요한 정보를 추출한다. 
            try : 
                blank[code] = company_df_A[code] 
            except : 
                pass  

        result_df = result_df.append(blank)

AttributeError: 'list' object has no attribute 'drop_duplicates'

In [33]:
result_df.to_excel('investingDOTcom_mexico_original_220623.xlsx', index = False)

이탈리아 크롤링

In [37]:
# 멕시코 주식시장 정보 페이지 접속
driver = webdriver.Chrome('./chromedriver.exe')
first_url = 'https://au.investing.com/equities/italy'    #맨 뒤에 'mexico'를 바꾸면 다른 국가에서도 재활용 할 수 있음
driver.get(first_url)

#페이지에 표시되는 주식을 'all stocks'로 바꿈 
try : 
    select_box = driver.find_element_by_xpath('//*[@id="stocksFilter"]').click()
    select_all_stock = driver.find_element_by_xpath('//*[@id="all"]').click()
    #time.sleep(8)

# Avoid error. 만약 광고 팝업창으로 인해 에러가 발생할 경우 except로 에러 회피
except : 
    # 광고 팝업창 닫기 
    driver.find_element_by_xpath('//*[@id="PromoteSignUpPopUp"]/div[2]/i').click()
    # try와 동일
    select_box = driver.find_element_by_xpath('//*[@id="stocksFilter"]').click()
    select_all_stock = driver.find_element_by_xpath('//*[@id="all"]').click()
    time.sleep(8)
    
# 인베스팅 닷컴은 동적페이지이다. 
# BeautifulSoup을 사용할수 있도록 스크롤을 한번 끝까지 내렸다 올린다.
SCROLL_PAUSE_SEC = 3

# 스크롤 높이 가져옴
last_height = driver.execute_script("return document.body.scrollHeight")

while True:
    # 끝까지 스크롤 다운
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

    # 1초 대기
    time.sleep(SCROLL_PAUSE_SEC)

    # 스크롤 다운 후 스크롤 높이 다시 가져옴
    new_height = driver.execute_script("return document.body.scrollHeight")
    if new_height == last_height:
        break
    last_height = new_height
    
time.sleep(20)
soup = BeautifulSoup(driver.page_source,"html.parser")

# 주식 테이블을 가지고 온다. 
maintable = soup.find('table', id='cross_rate_markets_stocks_1')

# 메인 주식 테이블에서 회사 페이지로
all_atag_maintable = maintable.find_all('a')

# soup의 find 메서드를 이용해서 갖고 오게 되면, 링크 뿐 아니라 다른 정보들도 같이 갖고 오게 됩니다. 
# 따라서 아래 for문으로 순수한 href 링크만을 추출하여, company_links에 저장합니다. 
company_links = []
for a in all_atag_maintable:
    company_link = a.attrs["href"] #find로 한번더 돌려준다.
    company_links.append(company_link)
    
# Version 3

wait_time = 3 # time.sleep의 변수 


# 일반기업, 은행, 보험업의 계정과목들중 겹치는 부분은 제거하여 중복없는 합집합을 사용한다. 
# drop_duplicates는 중복되는 것들중 하나만 제거, 그리고 리스트화 
all_cols = list(all_cols.drop_duplicates())
all_cols = all_cols+['is_unit','bs_unit','cf_unit','is_time','bs_time','cf_time','report_type','company_name','industry_info','sector_info',
                     'address_info','phone_info','fax_info','webpage_info','source','gathering_time','PIC']

# all_cols에 기업 이름, 일반정보 등을 추가한다. 

#cross_rate_markets_stocks_1

result_df = pd.DataFrame()
crawling_failed_companies = []
for company in company_links : 
    
    profile_url = base_url+company+PROFILE_suffix
    bs_url = base_url+company+BS_suffix
    is_url = base_url+company+IS_suffix
    cf_url = base_url+company+CF_suffix
    
    try : 
        # company_link를 보면 'cid='라 주소 맨 끝에 붙어져 있는, 링크가 특이한 기업들이 있다. 이런 기업들은 다루 처리를 해주어야 한다. 
        if company.__contains__('cid=') : 
            index = company.find('?')
            profile_url =  base_url+company[:index]+PROFILE_suffix+company[index:]
            bs_url = base_url+company[:index] +BS_suffix+company[index:]
            is_url = base_url+company[:index] +IS_suffix+company[index:]
            cf_url = base_url+company[:index] +CF_suffix+company[index:]

        ############## 기업 일반정보   #########
        #company profile page
        driver.get(profile_url)
        time.sleep(1)

        #  description : 기업 설명
        soup = BeautifulSoup(driver.page_source, "html.parser")
        desciption_info = soup.find('div', attrs = {'class' : 'companyProfileBody'}).text
        desciption_info = desciption_info.replace('\n','')

        profile_header = soup.find('div', attrs = {'class' : 'companyProfileHeader'}).text

        # Industry, Sector, Equity Type        
        industry_info =  profile_header.split('\n')[1].replace('Industry','')
        sector_info = profile_header.split('\n')[2].replace('Sector','')
    
        # contact info 
        address_info = soup.find('div', attrs = {'class' : 'companyAddress'}).text
        phone_info = soup.find('div', attrs = {'class' : 'companyPhone'}).text
        fax_info = soup.find('div', attrs = {'class' : 'companyFax'}).text
        webpage_info = soup.find('div', attrs = {'class' : 'companyWeb'}).text

        # 특수문자 제거 
        phone_info = phone_info.replace('\n','')
        phone_info = phone_info.replace('Phone','')
        fax_info = fax_info.replace('\n','')
        fax_info = fax_info.replace('Fax','')
        webpage_info = webpage_info.replace('\n','')
        webpage_info = webpage_info.replace('Web','')

        ############## 기업 재무정보   #########    
        # 분기별 Income Statement 
        driver.get(is_url)
        time.sleep(wait_time)

        for order, table in enumerate(pd.read_html(driver.page_source)) : 
            if len(table) > 20 :
                table_num = order
                break

        df_income_Q = pd.read_html(driver.page_source)[table_num].dropna()
        df_is_unit = driver.find_element_by_xpath('//*[@id="leftColumn"]/div[10]').text             # 통화 단위(Unit)
        company_name = driver.find_element_by_xpath('//*[@id="leftColumn"]/div[1]/h1').text             # 회사이름 추출

        # income statement dataframe preprocess
        df_income_Q = df_income_Q.T
        df_income_Q = df_income_Q.rename(columns = df_income_Q.iloc[0])         # 계정과목을 column 이름으로 설정
        df_income_Q = df_income_Q.iloc[1:, :]                                 # 0번째 row를 삭제하고 나머지만 남긴다.

        df_income_Q['is_unit'] = df_is_unit                 # 데이터프레임에 income statement 통화단위 삽입
        df_income_Q['is_time']= df_income_Q.index                  # 데이터프레임에 '시간' 추가
        df_income_Q['report_type'] = 'Quarter'                         # 데이터프레임에 분기보고서임을 표시 
        df_income_Q['company_name'] = company_name                     # 데이터프레임에 회사 이름 삽입
        df_income_Q=df_income_Q.reset_index(drop=True) 

        # 연간 Income Statement. 
        try : 
            driver.find_element_by_xpath('//*[@id="leftColumn"]/div[8]/div[1]/a[1]').click() # Annual 버튼 클릭
            time.sleep(2)
        except : 
            driver.find_element_by_xpath('//*[@id="leftColumn"]/div[9]/div[1]/a[1]').click()
            time.sleep(2)    

        for order, table in enumerate(pd.read_html(driver.page_source)) : 
            if len(table) > 20 :
                table_num = order
                break

        df_income_A = pd.read_html(driver.page_source)[table_num].dropna()

        # income statement dataframe preprocess
        df_income_A = df_income_A.T
        df_income_A = df_income_A.rename(columns = df_income_A.iloc[0])         # 계정과목을 column 이름으로 설정
        df_income_A = df_income_A.iloc[1:, :]                                 # 0번째 row를 삭제하고 나머지만 남긴다.

        df_income_A['is_unit'] = df_is_unit                 # 데이터프레임에 income statement 통화단위 삽입
        df_income_A['is_time']= df_income_A.index                  # 데이터프레임에 '시간' 추가
        df_income_A['report_type'] = 'Annual'                          # 데이터프레임에 분기보고서임을 표시 
        df_income_A['company_name'] = company_name                     # 데이터 프레임에 회사 이름 삽입
        df_income_A=df_income_A.reset_index(drop=True) 


        # balance data
        driver.get(bs_url)
        time.sleep(wait_time)

        for order, table in enumerate(pd.read_html(driver.page_source)) : 
            if len(table) > 20 :
                table_num = order


        # 분기별 balance sheet
        df_balance_Q = pd.read_html(driver.page_source)[table_num].dropna()
        df_bs_unit = driver.find_element_by_xpath('//*[@id="leftColumn"]/div[10]').text           # 통화 단위(Unit) 추출
        time.sleep(wait_time)
        # balance sheet dataframe preprocess
        df_balance_Q = df_balance_Q.T
        df_balance_Q = df_balance_Q.rename(columns = df_balance_Q.iloc[0])     # 계정과목을 column 이름으로 설정
        df_balance_Q = df_balance_Q.iloc[1:, :]                               # 0번째 row를 삭제하고 나머지만 남긴다.
        ##df_balance = df_balance[bs_targets]
        df_balance_Q['bs_unit'] = df_bs_unit                  # 데이터프레임에 cash flow 통화단위 삽입
        df_balance_Q['bs_time']= df_balance_Q.index
        #df_balance_Q['report_type'] = 'Quarter'                         # 데이터프레임에 분기보고서임을 표시 
        #df_balance_Q['company_name'] = company_name                     # 데이터 프레임에 회사 이름 삽입
        df_balance_Q=df_balance_Q.reset_index(drop=True)


        # 연간 balance sheet 
        try : 
            driver.find_element_by_xpath('//*[@id="leftColumn"]/div[8]/div[1]/a[1]').click() # Annual 버튼 클릭
        except :
            driver.find_element_by_xpath('//*[@id="leftColumn"]/div[9]/div[1]/a[1]').click() # Annual 버튼 클릭
        time.sleep(wait_time)

        for order, table in enumerate(pd.read_html(driver.page_source)) : 
            if len(table) > 20 :
                table_num = order
                break

        df_balance_A = pd.read_html(driver.page_source)[table_num].dropna()
        df_bs_unit = driver.find_element_by_xpath('//*[@id="leftColumn"]/div[10]').text           # 통화 단위(Unit) 추출
        time.sleep(wait_time)
        # balance sheet dataframe preprocess
        df_balance_A = df_balance_A.T
        df_balance_A = df_balance_A.rename(columns = df_balance_A.iloc[0])      # 계정과목을 column 이름으로 설정
        df_balance_A = df_balance_A.iloc[1:, :]                               # 0번째 row를 삭제하고 나머지만 남긴다.
        ##df_balance = df_balance[bs_targets]
        df_balance_A['bs_unit'] = df_bs_unit                  # 데이터프레임에 cash flow 통화단위 삽입
        df_balance_A['bs_time']= df_balance_A.index
        #df_balance_A['report_type'] = 'Annual'                          # 데이터프레임에 연간보고서임을 표시 
        #df_balance_A['company_name'] = company_name                     # 데이터 프레임에 회사 이름 삽입
        df_balance_A = df_balance_A.reset_index(drop=True)

        # cash flow
        driver.get(cf_url)
        time.sleep(2)

        for order, table in enumerate(pd.read_html(driver.page_source)) : 
            if len(table) > 20 :
                table_num = order
                break    

        # 분기별 cashflow 
        df_cash_flow_Q = pd.read_html(driver.page_source)[table_num].dropna()
        df_cf_unit = driver.find_element_by_xpath('//*[@id="leftColumn"]/div[10]').text           # 통화 단위(Unit) 추출
        time.sleep(wait_time)

        df_cash_flow_Q = df_cash_flow_Q.T 
        df_cash_flow_Q = df_cash_flow_Q.rename(columns = df_cash_flow_Q.iloc[0]) # 계정과목을 column 이름으로 설정
        df_cash_flow_Q = df_cash_flow_Q.iloc[1:, :]                              # 0번째 row를 삭제하고 나머지만 남긴다.
        df_cash_flow_Q['cf_unit'] = df_cf_unit                     # 데이터프레임에 cash flow 통화단위 삽입
        df_cash_flow_Q['cf_time']= df_cash_flow_Q.index        
        df_cash_flow_Q = df_cash_flow_Q.reset_index(drop=True)

        #연도별 cashflow 
        try : 
            driver.find_element_by_xpath('//*[@id="leftColumn"]/div[8]/div[1]/a[1]').click() # Annual 버튼 클릭
        except :                         
            driver.find_element_by_xpath('//*[@id="leftColumn"]/div[9]/div[1]/a[1]').click() # Annual 버튼 클릭
        time.sleep(wait_time)

        for order, table in enumerate(pd.read_html(driver.page_source)) : 
            if len(table) > 20 :
                table_num = order
                break        

        df_cash_flow_A = pd.read_html(driver.page_source)[table_num].dropna()
        df_cash_flow_unit = driver.find_element_by_xpath('//*[@id="leftColumn"]/div[10]').text            # 통화 단위(Unit) 추출

        #cash flow dataframe preprocess
        df_cash_flow_A = df_cash_flow_A.T 
        df_cash_flow_A = df_cash_flow_A.rename(columns = df_cash_flow_A.iloc[0]) # 계정과목을 column 이름으로 설정
        df_cash_flow_A = df_cash_flow_A.iloc[1:, :]                              # 0번째 row를 삭제하고 나머지만 남긴다.
        df_cash_flow_A['cf_unit'] = df_cf_unit                     # 데이터프레임에 cash flow 통화단위 삽입
        df_cash_flow_A['cf_time']= df_cash_flow_A.index  
        df_cash_flow_A = df_cash_flow_A.reset_index(drop=True) 

        # 일괄적으로 통합 열방향으로.
        company_df_A = pd.concat([df_balance_A, df_income_A, df_cash_flow_A],axis=1)# 데이터프레임에 분기보고서임을 표시 
        company_df_A['industry_info'] = industry_info
        company_df_A['sector_info'] = sector_info
        company_df_A['address_info'] = address_info
        company_df_A['phone_info'] = phone_info
        company_df_A['fax_info'] = fax_info
        company_df_A['webpage_info'] = webpage_info
        company_df_A['source'] = 'https://au.investing.com'+company+IS_suffix
        company_df_A['PIC'] = '임낙준'
        company_df_A['gathering_time'] = datetime.date.today()



        company_df_Q = pd.concat([df_balance_Q, df_income_Q, df_cash_flow_Q],axis=1)# 데이터프레임에 분기보고서임을 표시 
        company_df_Q['industry_info'] = industry_info
        company_df_Q['sector_info'] = sector_info
        company_df_Q['address_info'] = address_info
        company_df_Q['phone_info'] = phone_info
        company_df_Q['fax_info'] = fax_info
        company_df_Q['webpage_info'] = webpage_info
        company_df_Q['source'] = 'https://au.investing.com'+company+IS_suffix
        company_df_Q['PIC'] = '임낙준'
        company_df_Q['gathering_time'] = datetime.date.today()
        


        blank = pd.DataFrame(columns = all_cols)
        for code in blank.columns : 
        # 대응표의 ifrs코드로 필요한 정보를 추출한다. 
            try : 
                blank[code] = company_df_A[code] 
            except : 
                pass  

        result_df = result_df.append(blank)
        blank = pd.DataFrame(columns = all_cols)

        for code in blank.columns : 
        # 대응표의 ifrs코드로 필요한 정보를 추출한다. 
            try : 
                blank[code] = company_df_Q[code] 
            except : 
                pass  


        result_df = result_df.append(blank)
    
    except :
        # 만약 재무정보가 없어 에러가 났을 경우, 일반정보라도 추가한다. 
        ############## 기업 일반정보   #########
        #company profile page
        driver.get(profile_url)
        time.sleep(1)
        
        #  description : 기업 설명
        soup = BeautifulSoup(driver.page_source, "html.parser")
        try : 
            company_name = soup.find('h2').text.replace('Company Profile',"")
            #  description : 기업 설명
            desciption_info = soup.find('div', attrs = {'class' : 'companyProfileBody'}).text
            desciption_info = desciption_info.replace('\n','')
        except : 
            print(f"profile이 없어서 안되는 기업 {profile_url}")
            print(f"profile이 없어서 안되는 기업 {company}")
            continue

        profile_header = soup.find('div', attrs = {'class' : 'companyProfileHeader'}).text
        
        # Industry, Sector, Equity Type        
        industry_info =  profile_header.split('\n')[1].replace('Industry','')
        sector_info = profile_header.split('\n')[2].replace('Sector','')

        # contact info 
        address_info = soup.find('div', attrs = {'class' : 'companyAddress'}).text
        phone_info = soup.find('div', attrs = {'class' : 'companyPhone'}).text
        fax_info = soup.find('div', attrs = {'class' : 'companyFax'}).text
        webpage_info = soup.find('div', attrs = {'class' : 'companyWeb'}).text
        

        # 정규표현식으로 특수문자 제거 
        phone_info = phone_info.replace('\n','')
        phone_info = phone_info.replace('Phone','')
        fax_info = fax_info.replace('\n','')
        fax_info = fax_info.replace('Fax','')
        webpage_info = webpage_info.replace('\n','')
        webpage_info = webpage_info.replace('Web','')
        
        
        blank = pd.DataFrame(columns = all_cols)
        blank['company_name'] = company_name
        blank['industry_info'] = industry_info
        blank['sector_info'] = sector_info
        blank['address_info'] = address_info
        blank['phone_info'] = phone_info
        blank['fax_info'] = fax_info
        blank['webpage_info'] = webpage_info
        blank['source'] = 'https://au.investing.com'+company+PROFILE_suffix
        blank['PIC'] = '임낙준'
        blank['gathering_time'] = datetime.date.today()
        
        
        for code in blank.columns : 
            # 대응표의 ifrs코드로 필요한 정보를 추출한다. 
            try : 
                blank[code] = company_df_A[code] 
            except : 
                pass  

        result_df = result_df.append(blank)

profile이 없어서 안되는 기업 https://au.investing.com/equities/seri-industrial-spa-wnt-company-profile
profile이 없어서 안되는 기업 /equities/seri-industrial-spa-wnt
profile이 없어서 안되는 기업 https://au.investing.com/equities/meglioquesto-wnt-company-profile
profile이 없어서 안되는 기업 /equities/meglioquesto-wnt
profile이 없어서 안되는 기업 https://au.investing.com/equities/sourcesense-spa-wnt-company-profile
profile이 없어서 안되는 기업 /equities/sourcesense-spa-wnt
profile이 없어서 안되는 기업 https://au.investing.com/equities/nusco-spa-con-unico-socio-wnt-24-company-profile
profile이 없어서 안되는 기업 /equities/nusco-spa-con-unico-socio-wnt-24
profile이 없어서 안되는 기업 https://au.investing.com/equities/osai-automation-system-spa-wnt-company-profile
profile이 없어서 안되는 기업 /equities/osai-automation-system-spa-wnt
profile이 없어서 안되는 기업 https://au.investing.com/equities/ulisse-biomed-spa-wnt-company-profile
profile이 없어서 안되는 기업 /equities/ulisse-biomed-spa-wnt
profile이 없어서 안되는 기업 https://au.investing.com/equities/qf-immobiliare-dinamico-company-profile
profile이 없어서 안되는 기업 /equities/qf-immobiliare-dinamico
profile이 없어서 안되는 기업 https://au.investing.com/equities/esi-spa-wnt-company-profile
profile이 없어서 안되는 기업 /equities/esi-spa-wnt
profile이 없어서 안되는 기업 https://au.investing.com/equities/cyberoo-wnt-company-profile
profile이 없어서 안되는 기업 /equities/cyberoo-wnt
profile이 없어서 안되는 기업 https://au.investing.com/equities/qf-socrate-company-profile
profile이 없어서 안되는 기업 /equities/qf-socrate
profile이 없어서 안되는 기업 https://au.investing.com/equities/industrie-chimiche-forestali-wnt-company-profile
profile이 없어서 안되는 기업 /equities/industrie-chimiche-forestali-wnt
profile이 없어서 안되는 기업 https://au.investing.com/equities/vontobel-financial-products-gmbh-company-profile
profile이 없어서 안되는 기업 /equities/vontobel-financial-products-gmbh
profile이 없어서 안되는 기업 https://au.investing.com/equities/tenax-international-spa-wnt-company-profile
profile이 없어서 안되는 기업 /equities/tenax-international-spa-wnt
profile이 없어서 안되는 기업 https://au.investing.com/equities/radici-pietro-industries-brands-wnt-company-profile
profile이 없어서 안되는 기업 /equities/radici-pietro-industries-brands-wnt
profile이 없어서 안되는 기업 https://au.investing.com/equities/trendevice-spa-wnt-company-profile
profile이 없어서 안되는 기업 /equities/trendevice-spa-wnt
profile이 없어서 안되는 기업 https://au.investing.com/equities/antares-vision-spa-wnt-company-profile
profile이 없어서 안되는 기업 /equities/antares-vision-spa-wnt
profile이 없어서 안되는 기업 https://au.investing.com/equities/id-entity-wnt-company-profile
profile이 없어서 안되는 기업 /equities/id-entity-wnt
profile이 없어서 안되는 기업 https://au.investing.com/equities/trawell-co-spa-wnt-company-profile
profile이 없어서 안되는 기업 /equities/trawell-co-spa-wnt
profile이 없어서 안되는 기업 https://au.investing.com/equities/revo-spa-warrants-company-profile
profile이 없어서 안되는 기업 /equities/revo-spa-warrants
profile이 없어서 안되는 기업 https://au.investing.com/equities/destination-italia-wnt-company-profile
profile이 없어서 안되는 기업 /equities/destination-italia-wnt
profile이 없어서 안되는 기업 https://au.investing.com/equities/matica-fintec-wnt-company-profile
profile이 없어서 안되는 기업 /equities/matica-fintec-wnt
profile이 없어서 안되는 기업 https://au.investing.com/equities/fos-wnt-company-profile
profile이 없어서 안되는 기업 /equities/fos-wnt
profile이 없어서 안되는 기업 https://au.investing.com/equities/vontobel-financial-products-wnt-company-profile
profile이 없어서 안되는 기업 /equities/vontobel-financial-products-wnt
profile이 없어서 안되는 기업 https://au.investing.com/equities/cofle-wnt-company-profile
profile이 없어서 안되는 기업 /equities/cofle-wnt
profile이 없어서 안되는 기업 https://au.investing.com/equities/alfonsino-wnt-company-profile
profile이 없어서 안되는 기업 /equities/alfonsino-wnt
profile이 없어서 안되는 기업 https://au.investing.com/equities/4aim-societa-di-investimento-company-profile
profile이 없어서 안되는 기업 /equities/4aim-societa-di-investimento

In [49]:
driver = webdriver.Chrome('./chromedriver.exe')

driver.get('https://au.investing.com/equities/ulisse-biomed-spa-wnt-company-profile')

soup = BeautifulSoup(driver.page_source, "html.parser")
company_name = soup.find('h2').text.replace('Overview',"")
blank = pd.DataFrame(columns = all_cols)
blank['company_name'] = company_name 
result_df = result_df.append(blank)

UBM_t

In [39]:
result_df.to_excel('G:/공유 드라이브/HBS_DRN/2022년 데이터 수집/인베스팅닷컴/investingDOTcom_italy_original_220623.xlsx', index = False)

말레이시아

In [51]:
# 인베스팅 닷컴의 계정과목 리스트들. 일반 기업, 은행, 보험업의 계정과목이 달랐다. 
column_listup = pd.read_excel('investingDotcomColumns.xlsx')

all_bs_cols = pd.concat([column_listup['BS'],column_listup['BANK BS'], column_listup['INSURANCE BS']]).dropna()
all_is_cols =  pd.concat([column_listup['IS'],column_listup['BANK IS'], column_listup['INSURANCE IS']]).dropna()
all_cols = pd.concat([column_listup['BS'],column_listup['BANK BS'], column_listup['INSURANCE BS'],column_listup['IS'],column_listup['BANK IS'], column_listup['INSURANCE IS']]).dropna()

# 일반기업, 은행, 보험업의 계정과목들중 겹치는 부분은 제거하여 중복없는 합집합을 사용한다. 
# drop_duplicates는 중복되는 것들중 하나만 제거, 
all_cols = all_cols.drop_duplicates()

In [ ]:
# 멕시코 주식시장 정보 페이지 접속
driver = webdriver.Chrome('./chromedriver.exe')
first_url = 'https://au.investing.com/equities/malaysia'    #맨 뒤에 'mexico'를 바꾸면 다른 국가에서도 재활용 할 수 있음
driver.get(first_url)

#페이지에 표시되는 주식을 'all stocks'로 바꿈 
try : 
    select_box = driver.find_element_by_xpath('//*[@id="stocksFilter"]').click()
    select_all_stock = driver.find_element_by_xpath('//*[@id="all"]').click()
    #time.sleep(8)

# Avoid error. 만약 광고 팝업창으로 인해 에러가 발생할 경우 except로 에러 회피
except : 
    # 광고 팝업창 닫기 
    driver.find_element_by_xpath('//*[@id="PromoteSignUpPopUp"]/div[2]/i').click()
    # try와 동일
    select_box = driver.find_element_by_xpath('//*[@id="stocksFilter"]').click()
    select_all_stock = driver.find_element_by_xpath('//*[@id="all"]').click()
    time.sleep(8)
    
# 인베스팅 닷컴은 동적페이지이다. 
# BeautifulSoup을 사용할수 있도록 스크롤을 한번 끝까지 내렸다 올린다.
SCROLL_PAUSE_SEC = 3

# 스크롤 높이 가져옴
last_height = driver.execute_script("return document.body.scrollHeight")

while True:
    # 끝까지 스크롤 다운
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

    # 1초 대기
    time.sleep(SCROLL_PAUSE_SEC)

    # 스크롤 다운 후 스크롤 높이 다시 가져옴
    new_height = driver.execute_script("return document.body.scrollHeight")
    if new_height == last_height:
        break
    last_height = new_height
    
time.sleep(15)
soup = BeautifulSoup(driver.page_source,"html.parser")

# 주식 테이블을 가지고 온다. 
maintable = soup.find('table', id='cross_rate_markets_stocks_1')

# 메인 주식 테이블에서 회사 페이지로
all_atag_maintable = maintable.find_all('a')

# soup의 find 메서드를 이용해서 갖고 오게 되면, 링크 뿐 아니라 다른 정보들도 같이 갖고 오게 됩니다. 
# 따라서 아래 for문으로 순수한 href 링크만을 추출하여, company_links에 저장합니다. 
company_links = []
for a in all_atag_maintable:
    company_link = a.attrs["href"] #find로 한번더 돌려준다.
    company_links.append(company_link)
    
# Version 3

wait_time = 3 # time.sleep의 변수 


# 일반기업, 은행, 보험업의 계정과목들중 겹치는 부분은 제거하여 중복없는 합집합을 사용한다. 
# drop_duplicates는 중복되는 것들중 하나만 제거, 그리고 리스트화 
all_cols = list(all_cols.drop_duplicates())
all_cols = all_cols+['is_unit','bs_unit','cf_unit','is_time','bs_time','cf_time','report_type','company_name','industry_info','sector_info',
                     'address_info','phone_info','fax_info','webpage_info','source','gathering_time','PIC']

# all_cols에 기업 이름, 일반정보 등을 추가한다. 

#cross_rate_markets_stocks_1

result_df = pd.DataFrame()
crawling_failed_companies = []
for company in company_links : 
    
    profile_url = base_url+company+PROFILE_suffix
    bs_url = base_url+company+BS_suffix
    is_url = base_url+company+IS_suffix
    cf_url = base_url+company+CF_suffix
    
    try : 
        # company_link를 보면 'cid='라 주소 맨 끝에 붙어져 있는, 링크가 특이한 기업들이 있다. 이런 기업들은 다루 처리를 해주어야 한다. 
        if company.__contains__('cid=') : 
            index = company.find('?')
            profile_url =  base_url+company[:index]+PROFILE_suffix+company[index:]
            bs_url = base_url+company[:index] +BS_suffix+company[index:]
            is_url = base_url+company[:index] +IS_suffix+company[index:]
            cf_url = base_url+company[:index] +CF_suffix+company[index:]

        ############## 기업 일반정보   #########
        #company profile page
        driver.get(profile_url)
        time.sleep(1)

        #  description : 기업 설명
        soup = BeautifulSoup(driver.page_source, "html.parser")
        desciption_info = soup.find('div', attrs = {'class' : 'companyProfileBody'}).text
        desciption_info = desciption_info.replace('\n','')

        profile_header = soup.find('div', attrs = {'class' : 'companyProfileHeader'}).text

        # Industry, Sector, Equity Type        
        industry_info =  profile_header.split('\n')[1].replace('Industry','')
        sector_info = profile_header.split('\n')[2].replace('Sector','')
    
        # contact info 
        address_info = soup.find('div', attrs = {'class' : 'companyAddress'}).text
        phone_info = soup.find('div', attrs = {'class' : 'companyPhone'}).text
        fax_info = soup.find('div', attrs = {'class' : 'companyFax'}).text
        webpage_info = soup.find('div', attrs = {'class' : 'companyWeb'}).text

        # 특수문자 제거 
        phone_info = phone_info.replace('\n','')
        phone_info = phone_info.replace('Phone','')
        fax_info = fax_info.replace('\n','')
        fax_info = fax_info.replace('Fax','')
        webpage_info = webpage_info.replace('\n','')
        webpage_info = webpage_info.replace('Web','')

        ############## 기업 재무정보   #########    
        # 분기별 Income Statement 
        driver.get(is_url)
        time.sleep(wait_time)

        for order, table in enumerate(pd.read_html(driver.page_source)) : 
            if len(table) > 20 :
                table_num = order
                break

        df_income_Q = pd.read_html(driver.page_source)[table_num].dropna()
        df_is_unit = driver.find_element_by_xpath('//*[@id="leftColumn"]/div[10]').text             # 통화 단위(Unit)
        company_name = driver.find_element_by_xpath('//*[@id="leftColumn"]/div[1]/h1').text             # 회사이름 추출

        # income statement dataframe preprocess
        df_income_Q = df_income_Q.T
        df_income_Q = df_income_Q.rename(columns = df_income_Q.iloc[0])         # 계정과목을 column 이름으로 설정
        df_income_Q = df_income_Q.iloc[1:, :]                                 # 0번째 row를 삭제하고 나머지만 남긴다.

        df_income_Q['is_unit'] = df_is_unit                 # 데이터프레임에 income statement 통화단위 삽입
        df_income_Q['is_time']= df_income_Q.index                  # 데이터프레임에 '시간' 추가
        df_income_Q['report_type'] = 'Quarter'                         # 데이터프레임에 분기보고서임을 표시 
        df_income_Q['company_name'] = company_name                     # 데이터프레임에 회사 이름 삽입
        df_income_Q=df_income_Q.reset_index(drop=True) 

        # 연간 Income Statement. 
        try : 
            driver.find_element_by_xpath('//*[@id="leftColumn"]/div[8]/div[1]/a[1]').click() # Annual 버튼 클릭
            time.sleep(2)
        except : 
            driver.find_element_by_xpath('//*[@id="leftColumn"]/div[9]/div[1]/a[1]').click()
            time.sleep(2)    

        for order, table in enumerate(pd.read_html(driver.page_source)) : 
            if len(table) > 20 :
                table_num = order
                break

        df_income_A = pd.read_html(driver.page_source)[table_num].dropna()

        # income statement dataframe preprocess
        df_income_A = df_income_A.T
        df_income_A = df_income_A.rename(columns = df_income_A.iloc[0])         # 계정과목을 column 이름으로 설정
        df_income_A = df_income_A.iloc[1:, :]                                 # 0번째 row를 삭제하고 나머지만 남긴다.

        df_income_A['is_unit'] = df_is_unit                 # 데이터프레임에 income statement 통화단위 삽입
        df_income_A['is_time']= df_income_A.index                  # 데이터프레임에 '시간' 추가
        df_income_A['report_type'] = 'Annual'                          # 데이터프레임에 분기보고서임을 표시 
        df_income_A['company_name'] = company_name                     # 데이터 프레임에 회사 이름 삽입
        df_income_A=df_income_A.reset_index(drop=True) 


        # balance data
        driver.get(bs_url)
        time.sleep(wait_time)

        for order, table in enumerate(pd.read_html(driver.page_source)) : 
            if len(table) > 20 :
                table_num = order


        # 분기별 balance sheet
        df_balance_Q = pd.read_html(driver.page_source)[table_num].dropna()
        df_bs_unit = driver.find_element_by_xpath('//*[@id="leftColumn"]/div[10]').text           # 통화 단위(Unit) 추출
        time.sleep(wait_time)
        # balance sheet dataframe preprocess
        df_balance_Q = df_balance_Q.T
        df_balance_Q = df_balance_Q.rename(columns = df_balance_Q.iloc[0])     # 계정과목을 column 이름으로 설정
        df_balance_Q = df_balance_Q.iloc[1:, :]                               # 0번째 row를 삭제하고 나머지만 남긴다.
        ##df_balance = df_balance[bs_targets]
        df_balance_Q['bs_unit'] = df_bs_unit                  # 데이터프레임에 cash flow 통화단위 삽입
        df_balance_Q['bs_time']= df_balance_Q.index
        #df_balance_Q['report_type'] = 'Quarter'                         # 데이터프레임에 분기보고서임을 표시 
        #df_balance_Q['company_name'] = company_name                     # 데이터 프레임에 회사 이름 삽입
        df_balance_Q=df_balance_Q.reset_index(drop=True)


        # 연간 balance sheet 
        try : 
            driver.find_element_by_xpath('//*[@id="leftColumn"]/div[8]/div[1]/a[1]').click() # Annual 버튼 클릭
        except :
            driver.find_element_by_xpath('//*[@id="leftColumn"]/div[9]/div[1]/a[1]').click() # Annual 버튼 클릭
        time.sleep(wait_time)

        for order, table in enumerate(pd.read_html(driver.page_source)) : 
            if len(table) > 20 :
                table_num = order
                break

        df_balance_A = pd.read_html(driver.page_source)[table_num].dropna()
        df_bs_unit = driver.find_element_by_xpath('//*[@id="leftColumn"]/div[10]').text           # 통화 단위(Unit) 추출
        time.sleep(wait_time)
        # balance sheet dataframe preprocess
        df_balance_A = df_balance_A.T
        df_balance_A = df_balance_A.rename(columns = df_balance_A.iloc[0])      # 계정과목을 column 이름으로 설정
        df_balance_A = df_balance_A.iloc[1:, :]                               # 0번째 row를 삭제하고 나머지만 남긴다.
        ##df_balance = df_balance[bs_targets]
        df_balance_A['bs_unit'] = df_bs_unit                  # 데이터프레임에 cash flow 통화단위 삽입
        df_balance_A['bs_time']= df_balance_A.index
        #df_balance_A['report_type'] = 'Annual'                          # 데이터프레임에 연간보고서임을 표시 
        #df_balance_A['company_name'] = company_name                     # 데이터 프레임에 회사 이름 삽입
        df_balance_A = df_balance_A.reset_index(drop=True)

        # cash flow
        driver.get(cf_url)
        time.sleep(2)

        for order, table in enumerate(pd.read_html(driver.page_source)) : 
            if len(table) > 20 :
                table_num = order
                break    

        # 분기별 cashflow 
        df_cash_flow_Q = pd.read_html(driver.page_source)[table_num].dropna()
        df_cf_unit = driver.find_element_by_xpath('//*[@id="leftColumn"]/div[10]').text           # 통화 단위(Unit) 추출
        time.sleep(wait_time)

        df_cash_flow_Q = df_cash_flow_Q.T 
        df_cash_flow_Q = df_cash_flow_Q.rename(columns = df_cash_flow_Q.iloc[0]) # 계정과목을 column 이름으로 설정
        df_cash_flow_Q = df_cash_flow_Q.iloc[1:, :]                              # 0번째 row를 삭제하고 나머지만 남긴다.
        df_cash_flow_Q['cf_unit'] = df_cf_unit                     # 데이터프레임에 cash flow 통화단위 삽입
        df_cash_flow_Q['cf_time']= df_cash_flow_Q.index        
        df_cash_flow_Q = df_cash_flow_Q.reset_index(drop=True)

        #연도별 cashflow 
        try : 
            driver.find_element_by_xpath('//*[@id="leftColumn"]/div[8]/div[1]/a[1]').click() # Annual 버튼 클릭
        except :                         
            driver.find_element_by_xpath('//*[@id="leftColumn"]/div[9]/div[1]/a[1]').click() # Annual 버튼 클릭
        time.sleep(wait_time)

        for order, table in enumerate(pd.read_html(driver.page_source)) : 
            if len(table) > 20 :
                table_num = order
                break        

        df_cash_flow_A = pd.read_html(driver.page_source)[table_num].dropna()
        df_cash_flow_unit = driver.find_element_by_xpath('//*[@id="leftColumn"]/div[10]').text            # 통화 단위(Unit) 추출

        #cash flow dataframe preprocess
        df_cash_flow_A = df_cash_flow_A.T 
        df_cash_flow_A = df_cash_flow_A.rename(columns = df_cash_flow_A.iloc[0]) # 계정과목을 column 이름으로 설정
        df_cash_flow_A = df_cash_flow_A.iloc[1:, :]                              # 0번째 row를 삭제하고 나머지만 남긴다.
        df_cash_flow_A['cf_unit'] = df_cf_unit                     # 데이터프레임에 cash flow 통화단위 삽입
        df_cash_flow_A['cf_time']= df_cash_flow_A.index  
        df_cash_flow_A = df_cash_flow_A.reset_index(drop=True) 

        # 일괄적으로 통합 열방향으로.
        company_df_A = pd.concat([df_balance_A, df_income_A, df_cash_flow_A],axis=1)# 데이터프레임에 분기보고서임을 표시 
        company_df_A['industry_info'] = industry_info
        company_df_A['sector_info'] = sector_info
        company_df_A['address_info'] = address_info
        company_df_A['phone_info'] = phone_info
        company_df_A['fax_info'] = fax_info
        company_df_A['webpage_info'] = webpage_info
        company_df_A['source'] = 'https://au.investing.com'+company+IS_suffix
        company_df_A['PIC'] = '임낙준'
        company_df_A['gathering_time'] = datetime.date.today()



        company_df_Q = pd.concat([df_balance_Q, df_income_Q, df_cash_flow_Q],axis=1)# 데이터프레임에 분기보고서임을 표시 
        company_df_Q['industry_info'] = industry_info
        company_df_Q['sector_info'] = sector_info
        company_df_Q['address_info'] = address_info
        company_df_Q['phone_info'] = phone_info
        company_df_Q['fax_info'] = fax_info
        company_df_Q['webpage_info'] = webpage_info
        company_df_Q['source'] = 'https://au.investing.com'+company+IS_suffix
        company_df_Q['PIC'] = '임낙준'
        company_df_Q['gathering_time'] = datetime.date.today()
        


        blank = pd.DataFrame(columns = all_cols)
        for code in blank.columns : 
        # 대응표의 ifrs코드로 필요한 정보를 추출한다. 
            try : 
                blank[code] = company_df_A[code] 
            except : 
                pass  

        result_df = result_df.append(blank)
        blank = pd.DataFrame(columns = all_cols)

        for code in blank.columns : 
        # 대응표의 ifrs코드로 필요한 정보를 추출한다. 
            try : 
                blank[code] = company_df_Q[code] 
            except : 
                pass  


        result_df = result_df.append(blank)
    
    except :
        # 만약 재무정보가 없어 에러가 났을 경우, 일반정보라도 추가한다. 
        ############## 기업 일반정보   #########
        #company profile page
        driver.get(profile_url)
        time.sleep(1)

        #  description : 기업 설명
        soup = BeautifulSoup(driver.page_source, "html.parser")
        try : 
            company_name = soup.find('h2').text.replace('Company Profile',"")
            #  description : 기업 설명
            desciption_info = soup.find('div', attrs = {'class' : 'companyProfileBody'}).text
            desciption_info = desciption_info.replace('\n','')
        except : 
            company_name = soup.find('h2').text.replace('Overview',"")
            company_name = soup.find('h2').text.replace('Company Profile',"")
            blank = pd.DataFrame(columns = all_cols)
            blank['company_name'] = company_name 
            result_df = result_df.append(blank)
            continue

        
        company_name = soup.find('h2').text.replace('Company Profile',"")
        desciption_info = soup.find('div', attrs = {'class' : 'companyProfileBody'}).text
        desciption_info = desciption_info.replace('\n','')

        profile_header = soup.find('div', attrs = {'class' : 'companyProfileHeader'}).text
        
        # Industry, Sector, Equity Type        
        industry_info =  profile_header.split('\n')[1].replace('Industry','')
        sector_info = profile_header.split('\n')[2].replace('Sector','')

        # contact info 
        address_info = soup.find('div', attrs = {'class' : 'companyAddress'}).text
        phone_info = soup.find('div', attrs = {'class' : 'companyPhone'}).text
        fax_info = soup.find('div', attrs = {'class' : 'companyFax'}).text
        webpage_info = soup.find('div', attrs = {'class' : 'companyWeb'}).text
        

        # 정규표현식으로 특수문자 제거 
        phone_info = phone_info.replace('\n','')
        phone_info = phone_info.replace('Phone','')
        fax_info = fax_info.replace('\n','')
        fax_info = fax_info.replace('Fax','')
        webpage_info = webpage_info.replace('\n','')
        webpage_info = webpage_info.replace('Web','')
        
        
        blank = pd.DataFrame(columns = all_cols)
        blank['company_name'] = company_name
        blank['industry_info'] = industry_info
        blank['sector_info'] = sector_info
        blank['address_info'] = address_info
        blank['phone_info'] = phone_info
        blank['fax_info'] = fax_info
        blank['webpage_info'] = webpage_info
        blank['source'] = 'https://au.investing.com'+company+PROFILE_suffix
        blank['PIC'] = '임낙준'
        blank['gathering_time'] = datetime.date.today()
        
        
        for code in blank.columns : 
            # 대응표의 ifrs코드로 필요한 정보를 추출한다. 
            try : 
                blank[code] = company_df_A[code] 
            except : 
                pass  

        result_df = result_df.append(blank)

In [ ]:
result_df.to_excel('G:/공유 드라이브/HBS_DRN/2022년 데이터 수집/인베스팅닷컴/investingDOTcom_malaysia_original_220623.xlsx', index = False)

싱가포르

In [ ]:
# 인베스팅 닷컴의 계정과목 리스트들. 일반 기업, 은행, 보험업의 계정과목이 달랐다. 
column_listup = pd.read_excel('investingDotcomColumns.xlsx')

all_bs_cols = pd.concat([column_listup['BS'],column_listup['BANK BS'], column_listup['INSURANCE BS']]).dropna()
all_is_cols =  pd.concat([column_listup['IS'],column_listup['BANK IS'], column_listup['INSURANCE IS']]).dropna()
all_cols = pd.concat([column_listup['BS'],column_listup['BANK BS'], column_listup['INSURANCE BS'],column_listup['IS'],column_listup['BANK IS'], column_listup['INSURANCE IS']]).dropna()

# 일반기업, 은행, 보험업의 계정과목들중 겹치는 부분은 제거하여 중복없는 합집합을 사용한다. 
# drop_duplicates는 중복되는 것들중 하나만 제거, 
all_cols = all_cols.drop_duplicates()

In [ ]:
# 멕시코 주식시장 정보 페이지 접속
driver = webdriver.Chrome('./chromedriver.exe')
first_url = 'https://au.investing.com/equities/singapore'    #맨 뒤에 'mexico'를 바꾸면 다른 국가에서도 재활용 할 수 있음
driver.get(first_url)

#페이지에 표시되는 주식을 'all stocks'로 바꿈 
try : 
    select_box = driver.find_element_by_xpath('//*[@id="stocksFilter"]').click()
    select_all_stock = driver.find_element_by_xpath('//*[@id="all"]').click()
    #time.sleep(8)

# Avoid error. 만약 광고 팝업창으로 인해 에러가 발생할 경우 except로 에러 회피
except : 
    # 광고 팝업창 닫기 
    driver.find_element_by_xpath('//*[@id="PromoteSignUpPopUp"]/div[2]/i').click()
    # try와 동일
    select_box = driver.find_element_by_xpath('//*[@id="stocksFilter"]').click()
    select_all_stock = driver.find_element_by_xpath('//*[@id="all"]').click()
    time.sleep(8)
    
# 인베스팅 닷컴은 동적페이지이다. 
# BeautifulSoup을 사용할수 있도록 스크롤을 한번 끝까지 내렸다 올린다.
SCROLL_PAUSE_SEC = 3

# 스크롤 높이 가져옴
last_height = driver.execute_script("return document.body.scrollHeight")

while True:
    # 끝까지 스크롤 다운
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

    # 1초 대기
    time.sleep(SCROLL_PAUSE_SEC)

    # 스크롤 다운 후 스크롤 높이 다시 가져옴
    new_height = driver.execute_script("return document.body.scrollHeight")
    if new_height == last_height:
        break
    last_height = new_height
    
time.sleep(15)
soup = BeautifulSoup(driver.page_source,"html.parser")

# 주식 테이블을 가지고 온다. 
maintable = soup.find('table', id='cross_rate_markets_stocks_1')

# 메인 주식 테이블에서 회사 페이지로
all_atag_maintable = maintable.find_all('a')

# soup의 find 메서드를 이용해서 갖고 오게 되면, 링크 뿐 아니라 다른 정보들도 같이 갖고 오게 됩니다. 
# 따라서 아래 for문으로 순수한 href 링크만을 추출하여, company_links에 저장합니다. 
company_links = []
for a in all_atag_maintable:
    company_link = a.attrs["href"] #find로 한번더 돌려준다.
    company_links.append(company_link)
    
# Version 3

wait_time = 3 # time.sleep의 변수 


# 일반기업, 은행, 보험업의 계정과목들중 겹치는 부분은 제거하여 중복없는 합집합을 사용한다. 
# drop_duplicates는 중복되는 것들중 하나만 제거, 그리고 리스트화 
all_cols = list(all_cols.drop_duplicates())
all_cols = all_cols+['is_unit','bs_unit','cf_unit','is_time','bs_time','cf_time','report_type','company_name','industry_info','sector_info',
                     'address_info','phone_info','fax_info','webpage_info','source','gathering_time','PIC']

# all_cols에 기업 이름, 일반정보 등을 추가한다. 

#cross_rate_markets_stocks_1

result_df = pd.DataFrame()
crawling_failed_companies = []
for company in company_links : 
    
    profile_url = base_url+company+PROFILE_suffix
    bs_url = base_url+company+BS_suffix
    is_url = base_url+company+IS_suffix
    cf_url = base_url+company+CF_suffix
    
    try : 
        # company_link를 보면 'cid='라 주소 맨 끝에 붙어져 있는, 링크가 특이한 기업들이 있다. 이런 기업들은 다루 처리를 해주어야 한다. 
        if company.__contains__('cid=') : 
            index = company.find('?')
            profile_url =  base_url+company[:index]+PROFILE_suffix+company[index:]
            bs_url = base_url+company[:index] +BS_suffix+company[index:]
            is_url = base_url+company[:index] +IS_suffix+company[index:]
            cf_url = base_url+company[:index] +CF_suffix+company[index:]

        ############## 기업 일반정보   #########
        #company profile page
        driver.get(profile_url)
        time.sleep(1)

        #  description : 기업 설명
        soup = BeautifulSoup(driver.page_source, "html.parser")
        desciption_info = soup.find('div', attrs = {'class' : 'companyProfileBody'}).text
        desciption_info = desciption_info.replace('\n','')

        profile_header = soup.find('div', attrs = {'class' : 'companyProfileHeader'}).text

        # Industry, Sector, Equity Type        
        industry_info =  profile_header.split('\n')[1].replace('Industry','')
        sector_info = profile_header.split('\n')[2].replace('Sector','')
    
        # contact info 
        address_info = soup.find('div', attrs = {'class' : 'companyAddress'}).text
        phone_info = soup.find('div', attrs = {'class' : 'companyPhone'}).text
        fax_info = soup.find('div', attrs = {'class' : 'companyFax'}).text
        webpage_info = soup.find('div', attrs = {'class' : 'companyWeb'}).text

        # 특수문자 제거 
        phone_info = phone_info.replace('\n','')
        phone_info = phone_info.replace('Phone','')
        fax_info = fax_info.replace('\n','')
        fax_info = fax_info.replace('Fax','')
        webpage_info = webpage_info.replace('\n','')
        webpage_info = webpage_info.replace('Web','')

        ############## 기업 재무정보   #########    
        # 분기별 Income Statement 
        driver.get(is_url)
        time.sleep(wait_time)

        for order, table in enumerate(pd.read_html(driver.page_source)) : 
            if len(table) > 20 :
                table_num = order
                break

        df_income_Q = pd.read_html(driver.page_source)[table_num].dropna()
        df_is_unit = driver.find_element_by_xpath('//*[@id="leftColumn"]/div[10]').text             # 통화 단위(Unit)
        company_name = driver.find_element_by_xpath('//*[@id="leftColumn"]/div[1]/h1').text             # 회사이름 추출

        # income statement dataframe preprocess
        df_income_Q = df_income_Q.T
        df_income_Q = df_income_Q.rename(columns = df_income_Q.iloc[0])         # 계정과목을 column 이름으로 설정
        df_income_Q = df_income_Q.iloc[1:, :]                                 # 0번째 row를 삭제하고 나머지만 남긴다.

        df_income_Q['is_unit'] = df_is_unit                 # 데이터프레임에 income statement 통화단위 삽입
        df_income_Q['is_time']= df_income_Q.index                  # 데이터프레임에 '시간' 추가
        df_income_Q['report_type'] = 'Quarter'                         # 데이터프레임에 분기보고서임을 표시 
        df_income_Q['company_name'] = company_name                     # 데이터프레임에 회사 이름 삽입
        df_income_Q=df_income_Q.reset_index(drop=True) 

        # 연간 Income Statement. 
        try : 
            driver.find_element_by_xpath('//*[@id="leftColumn"]/div[8]/div[1]/a[1]').click() # Annual 버튼 클릭
            time.sleep(2)
        except : 
            driver.find_element_by_xpath('//*[@id="leftColumn"]/div[9]/div[1]/a[1]').click()
            time.sleep(2)    

        for order, table in enumerate(pd.read_html(driver.page_source)) : 
            if len(table) > 20 :
                table_num = order
                break

        df_income_A = pd.read_html(driver.page_source)[table_num].dropna()

        # income statement dataframe preprocess
        df_income_A = df_income_A.T
        df_income_A = df_income_A.rename(columns = df_income_A.iloc[0])         # 계정과목을 column 이름으로 설정
        df_income_A = df_income_A.iloc[1:, :]                                 # 0번째 row를 삭제하고 나머지만 남긴다.

        df_income_A['is_unit'] = df_is_unit                 # 데이터프레임에 income statement 통화단위 삽입
        df_income_A['is_time']= df_income_A.index                  # 데이터프레임에 '시간' 추가
        df_income_A['report_type'] = 'Annual'                          # 데이터프레임에 분기보고서임을 표시 
        df_income_A['company_name'] = company_name                     # 데이터 프레임에 회사 이름 삽입
        df_income_A=df_income_A.reset_index(drop=True) 


        # balance data
        driver.get(bs_url)
        time.sleep(wait_time)

        for order, table in enumerate(pd.read_html(driver.page_source)) : 
            if len(table) > 20 :
                table_num = order


        # 분기별 balance sheet
        df_balance_Q = pd.read_html(driver.page_source)[table_num].dropna()
        df_bs_unit = driver.find_element_by_xpath('//*[@id="leftColumn"]/div[10]').text           # 통화 단위(Unit) 추출
        time.sleep(wait_time)
        # balance sheet dataframe preprocess
        df_balance_Q = df_balance_Q.T
        df_balance_Q = df_balance_Q.rename(columns = df_balance_Q.iloc[0])     # 계정과목을 column 이름으로 설정
        df_balance_Q = df_balance_Q.iloc[1:, :]                               # 0번째 row를 삭제하고 나머지만 남긴다.
        ##df_balance = df_balance[bs_targets]
        df_balance_Q['bs_unit'] = df_bs_unit                  # 데이터프레임에 cash flow 통화단위 삽입
        df_balance_Q['bs_time']= df_balance_Q.index
        #df_balance_Q['report_type'] = 'Quarter'                         # 데이터프레임에 분기보고서임을 표시 
        #df_balance_Q['company_name'] = company_name                     # 데이터 프레임에 회사 이름 삽입
        df_balance_Q=df_balance_Q.reset_index(drop=True)


        # 연간 balance sheet 
        try : 
            driver.find_element_by_xpath('//*[@id="leftColumn"]/div[8]/div[1]/a[1]').click() # Annual 버튼 클릭
        except :
            driver.find_element_by_xpath('//*[@id="leftColumn"]/div[9]/div[1]/a[1]').click() # Annual 버튼 클릭
        time.sleep(wait_time)

        for order, table in enumerate(pd.read_html(driver.page_source)) : 
            if len(table) > 20 :
                table_num = order
                break

        df_balance_A = pd.read_html(driver.page_source)[table_num].dropna()
        df_bs_unit = driver.find_element_by_xpath('//*[@id="leftColumn"]/div[10]').text           # 통화 단위(Unit) 추출
        time.sleep(wait_time)
        # balance sheet dataframe preprocess
        df_balance_A = df_balance_A.T
        df_balance_A = df_balance_A.rename(columns = df_balance_A.iloc[0])      # 계정과목을 column 이름으로 설정
        df_balance_A = df_balance_A.iloc[1:, :]                               # 0번째 row를 삭제하고 나머지만 남긴다.
        ##df_balance = df_balance[bs_targets]
        df_balance_A['bs_unit'] = df_bs_unit                  # 데이터프레임에 cash flow 통화단위 삽입
        df_balance_A['bs_time']= df_balance_A.index
        #df_balance_A['report_type'] = 'Annual'                          # 데이터프레임에 연간보고서임을 표시 
        #df_balance_A['company_name'] = company_name                     # 데이터 프레임에 회사 이름 삽입
        df_balance_A = df_balance_A.reset_index(drop=True)

        # cash flow
        driver.get(cf_url)
        time.sleep(2)

        for order, table in enumerate(pd.read_html(driver.page_source)) : 
            if len(table) > 20 :
                table_num = order
                break    

        # 분기별 cashflow 
        df_cash_flow_Q = pd.read_html(driver.page_source)[table_num].dropna()
        df_cf_unit = driver.find_element_by_xpath('//*[@id="leftColumn"]/div[10]').text           # 통화 단위(Unit) 추출
        time.sleep(wait_time)

        df_cash_flow_Q = df_cash_flow_Q.T 
        df_cash_flow_Q = df_cash_flow_Q.rename(columns = df_cash_flow_Q.iloc[0]) # 계정과목을 column 이름으로 설정
        df_cash_flow_Q = df_cash_flow_Q.iloc[1:, :]                              # 0번째 row를 삭제하고 나머지만 남긴다.
        df_cash_flow_Q['cf_unit'] = df_cf_unit                     # 데이터프레임에 cash flow 통화단위 삽입
        df_cash_flow_Q['cf_time']= df_cash_flow_Q.index        
        df_cash_flow_Q = df_cash_flow_Q.reset_index(drop=True)

        #연도별 cashflow 
        try : 
            driver.find_element_by_xpath('//*[@id="leftColumn"]/div[8]/div[1]/a[1]').click() # Annual 버튼 클릭
        except :                         
            driver.find_element_by_xpath('//*[@id="leftColumn"]/div[9]/div[1]/a[1]').click() # Annual 버튼 클릭
        time.sleep(wait_time)

        for order, table in enumerate(pd.read_html(driver.page_source)) : 
            if len(table) > 20 :
                table_num = order
                break        

        df_cash_flow_A = pd.read_html(driver.page_source)[table_num].dropna()
        df_cash_flow_unit = driver.find_element_by_xpath('//*[@id="leftColumn"]/div[10]').text            # 통화 단위(Unit) 추출

        #cash flow dataframe preprocess
        df_cash_flow_A = df_cash_flow_A.T 
        df_cash_flow_A = df_cash_flow_A.rename(columns = df_cash_flow_A.iloc[0]) # 계정과목을 column 이름으로 설정
        df_cash_flow_A = df_cash_flow_A.iloc[1:, :]                              # 0번째 row를 삭제하고 나머지만 남긴다.
        df_cash_flow_A['cf_unit'] = df_cf_unit                     # 데이터프레임에 cash flow 통화단위 삽입
        df_cash_flow_A['cf_time']= df_cash_flow_A.index  
        df_cash_flow_A = df_cash_flow_A.reset_index(drop=True) 

        # 일괄적으로 통합 열방향으로.
        company_df_A = pd.concat([df_balance_A, df_income_A, df_cash_flow_A],axis=1)# 데이터프레임에 분기보고서임을 표시 
        company_df_A['industry_info'] = industry_info
        company_df_A['sector_info'] = sector_info
        company_df_A['address_info'] = address_info
        company_df_A['phone_info'] = phone_info
        company_df_A['fax_info'] = fax_info
        company_df_A['webpage_info'] = webpage_info
        company_df_A['source'] = 'https://au.investing.com'+company+IS_suffix
        company_df_A['PIC'] = '임낙준'
        company_df_A['gathering_time'] = datetime.date.today()



        company_df_Q = pd.concat([df_balance_Q, df_income_Q, df_cash_flow_Q],axis=1)# 데이터프레임에 분기보고서임을 표시 
        company_df_Q['industry_info'] = industry_info
        company_df_Q['sector_info'] = sector_info
        company_df_Q['address_info'] = address_info
        company_df_Q['phone_info'] = phone_info
        company_df_Q['fax_info'] = fax_info
        company_df_Q['webpage_info'] = webpage_info
        company_df_Q['source'] = 'https://au.investing.com'+company+IS_suffix
        company_df_Q['PIC'] = '임낙준'
        company_df_Q['gathering_time'] = datetime.date.today()
        


        blank = pd.DataFrame(columns = all_cols)
        for code in blank.columns : 
        # 대응표의 ifrs코드로 필요한 정보를 추출한다. 
            try : 
                blank[code] = company_df_A[code] 
            except : 
                pass  

        result_df = result_df.append(blank)
        blank = pd.DataFrame(columns = all_cols)

        for code in blank.columns : 
        # 대응표의 ifrs코드로 필요한 정보를 추출한다. 
            try : 
                blank[code] = company_df_Q[code] 
            except : 
                pass  


        result_df = result_df.append(blank)
    
    except :
        # 만약 재무정보가 없어 에러가 났을 경우, 일반정보라도 추가한다. 
        ############## 기업 일반정보   #########
        #company profile page
        driver.get(profile_url)
        time.sleep(1)

        #  description : 기업 설명
        soup = BeautifulSoup(driver.page_source, "html.parser")
        try : 
            company_name = soup.find('h2').text.replace('Company Profile',"")
            #  description : 기업 설명
            desciption_info = soup.find('div', attrs = {'class' : 'companyProfileBody'}).text
            desciption_info = desciption_info.replace('\n','')
        except : 
            company_name = soup.find('h2').text.replace('Overview',"")
            company_name = soup.find('h2').text.replace('Company Profile',"")
            blank = pd.DataFrame(columns = all_cols)
            blank['company_name'] = company_name 
            result_df = result_df.append(blank)
            continue
            
        profile_header = soup.find('div', attrs = {'class' : 'companyProfileHeader'}).text
        
        # Industry, Sector, Equity Type        
        industry_info =  profile_header.split('\n')[1].replace('Industry','')
        sector_info = profile_header.split('\n')[2].replace('Sector','')

        # contact info 
        address_info = soup.find('div', attrs = {'class' : 'companyAddress'}).text
        phone_info = soup.find('div', attrs = {'class' : 'companyPhone'}).text
        fax_info = soup.find('div', attrs = {'class' : 'companyFax'}).text
        webpage_info = soup.find('div', attrs = {'class' : 'companyWeb'}).text
        

        # 정규표현식으로 특수문자 제거 
        phone_info = phone_info.replace('\n','')
        phone_info = phone_info.replace('Phone','')
        fax_info = fax_info.replace('\n','')
        fax_info = fax_info.replace('Fax','')
        webpage_info = webpage_info.replace('\n','')
        webpage_info = webpage_info.replace('Web','')
        
        
        blank = pd.DataFrame(columns = all_cols)
        blank['company_name'] = company_name
        blank['industry_info'] = industry_info
        blank['sector_info'] = sector_info
        blank['address_info'] = address_info
        blank['phone_info'] = phone_info
        blank['fax_info'] = fax_info
        blank['webpage_info'] = webpage_info
        blank['source'] = 'https://au.investing.com'+company+PROFILE_suffix
        blank['PIC'] = '임낙준'
        blank['gathering_time'] = datetime.date.today()
        
        
        for code in blank.columns : 
            # 대응표의 ifrs코드로 필요한 정보를 추출한다. 
            try : 
                blank[code] = company_df_A[code] 
            except : 
                pass  

        result_df = result_df.append(blank)

In [ ]:
result_df.to_excel('G:/공유 드라이브/HBS_DRN/2022년 데이터 수집/인베스팅닷컴/investingDOTcom_singapore_original_220623.xlsx', index = False)

### Question) 저번에 조사한 멕시코의 상장기업수는 140개

해결해야할 문제 :   
* 은행은 일반기업들과 다른 계정과목을 사용함. 위 for 반복문이 은행의 경우 에러가 떠버린다. 
- try except를 이용하여 회피한다. 설명하는 부분에도 이를 추가해야한다. 
* 은행의 계정과목을 테이블 명세서에 반영해야겠다. 
* 스크롤이 과연 끝까지 되는지 확인해야한다. 호주의 경우 상장사가 1000개가 넘는데, 크롤링되는 주식종목은 정확히 1000이다. 
* 테이블을 가공해서 만들어야할 
* time.sleep(waittime)의 waittime을 함수의 변수로 빼버려서 기다리는 시간을 조절하기 쉽게 만들자.

인베스팅 닷컴에서 일반 기업, 은행, 보험업종 마다 재무테이블이 조금씩다르다. 
그리고 현재, 금융기업 계정과목이 픽스되어 있지 않은 상태이다. 
따라서, 우리가 필요한 계정과목에 대응하는 칼럼명은 한국어로 바꾸고, string 형식으로 되어있는 고속버시를 낸양일ㅇ 많았다.  향후 전처리 코드를 만들어 뽑아오기로 하고,
크롤러 코드는 raw data만 수집한다.
1. 수집방식은 대강 이렇다. 일반기업, 은행업, 보험업의 계정과목을 모두 정리한 list를 만든다.(all_cols)

2. 일반기업, 은행업, 보험업의 계정과목 중 겹치는 것은 하나ㅏㄴ 있으면 충분한다. concatanate된 위의 리스트에서 중복값은 제거한다. 

3. 만들어진 리스트를 column으로 하는 빈 테이블을 만든다. 

5. 반복문을 돌아가면서, 한 기업의 연간, 분기별 데이터를 빈 테이블에 append한다. 

.

In [289]:
pd.read_html(driver.page_source)[1].dropna()

,Period Ending:,202231/03,202131/12,202130/09,202130/06
0,Total Current Assets,4646.85,4225.25,4510.63,4995.77
1,Cash and Short Term Investments 824.82 803.05 ...,Cash and Short Term Investments 824.82 803.05 ...,Cash and Short Term Investments 824.82 803.05 ...,Cash and Short Term Investments 824.82 803.05 ...,Cash and Short Term Investments 824.82 803.05 ...
2,Cash and Short Term Investments,824.82,803.05,1077.13,1527.91
3,Cash,592.86,612.82,869.25,1304.66
4,Cash & Equivalents,-,612.82,-,-
5,Short Term Investments,231.95,190.23,207.88,223.25
6,"Total Receivables, Net",2282.02,2020.89,2158.67,2173.04
7,"Accounts Receivables - Trade, Net",1793.92,1520.97,1659.4,1701.96
8,Total Inventory,1393.34,1260.67,1212.2,1132.51
9,Prepaid Expenses,-,-,-,-
10,"Other Current Assets, Total",146.67,140.64,62.63,162.31
11,Total Assets,27176.87,26650.37,26780.31,27909.86
12,"Property/Plant/Equipment, Total - Net 11354.36...","Property/Plant/Equipment, Total - Net 11354.36...","Property/Plant/Equipment, Total - Net 11354.36...","Property/Plant/Equipment, Total - Net 11354.36...","Property/Plant/Equipment, Total - Net 11354.36..."
13,"Property/Plant/Equipment, Total - Net",11354.36,11322.11,11050.64,11202.04
14,"Property/Plant/Equipment, Total - Gross",-,-,-,-
15,"Accumulated Depreciation, Total",-,-,-,-
16,"Goodwill, Net",8004.87,7984.49,7992.6,8456.32
17,"Intangibles, Net",1768.87,1778.12,1674.52,1734.05
18,Long Term Investments,671.22,616.18,619.69,629.36
19,Note Receivable - Long Term,180.05,161.78,164.82,162.84
20,"Other Long Term Assets, Total",550.65,562.44,767.4,729.48
21,"Other Assets, Total",-,-,-,-
22,Total Current Liabilities,5393.8,5380.32,5163.13,5763.93
23,Accounts Payable 2771.33 2761.88 2633.6 2653.2...,Accounts Payable 2771.33 2761.88 2633.6 2653.2...,Accounts Payable 2771.33 2761.88 2633.6 2653.2...,Accounts Payable 2771.33 2761.88 2633.6 2653.2...,Accounts Payable 2771.33 2761.88 2633.6 2653.2...
24,Accounts Payable,2771.33,2761.88,2633.6,2653.25
25,Payable/Accrued,-,-,-,-
26,Accrued Expenses,352.64,324.13,340.73,340.75
27,Notes Payable/Short Term Debt,-,-,-,-
28,Current Port. of LT Debt/Capital Leases,358.83,319.4,350.24,394.97
29,"Other Current liabilities, Total",1910.99,1974.9,1838.56,2374.96
30,Total Liabilities,17117.11,16823.11,17241.04,17920.48
31,Total Long Term Debt 8592.79 8216.89 8623.81 8...,Total Long Term Debt 8592.79 8216.89 8623.81 8...,Total Long Term Debt 8592.79 8216.89 8623.81 8...,Total Long Term Debt 8592.79 8216.89 8623.81 8...,Total Long Term Debt 8592.79 8216.89 8623.81 8...
32,Total Long Term Debt,8592.79,8216.89,8623.81,8720.8
33,Long Term Debt,7669.72,7305.78,7757.94,7830.09
34,Capital Lease Obligations,923.07,911.11,865.87,890.71
35,Deferred Income Tax,484.5,484.5,643.26,657.7
36,Minority Interest,456.61,443.86,452.23,451.65
37,"Other Liabilities, Total",2189.41,2297.54,2358.62,2326.4
38,Total Equity,10059.76,9827.26,9539.27,9989.39
39,"Redeemable Preferred Stock, Total - - - - Pre...","Redeemable Preferred Stock, Total - - - - Pre...","Redeemable Preferred Stock, Total - - - - Pre...","Redeemable Preferred Stock, Total - - - - Pre...","Redeemable Preferred Stock, Total - - - - Pre..."
40,"Redeemable Preferred Stock, Total",-,-,-,-
41,"Preferred Stock - Non Redeemable, Net",-,-,-,-
42,"Common Stock, Total",318.16,318.16,318.16,318.3
43,Additional Paid-In Capital,7491.94,7491.94,7491.94,7575.01
44,Retained Earnings (Accumulated Deficit),3585.51,3387.42,3192.62,3568.78
45,Treasury Stock - Common,-,-,-,-
46,ESOP Debt Guarantee,-,-,-,-
47,Unrealized Gain (Loss),-,-,-,-
48,"Other Equity, Total",-1335.85,-1370.26,-1463.46,-1472.7
49,Total Liabilities & Shareholders' Equity,27176.87,26650.37,26780.31,27909.86
50,Total Common Shares Outstanding,43524.98,44186.91,44186.91,44186.91
51,Total Preferred Shares Outstanding,-,-,-,-